### ISSUE TITLE
Podspec seems to be missing some file exclusions

### ISSUE THREAD

**Issue by amethystdeceiver** [libpd/libpd#102]
libpd doesn't build when used via CocoaPods, because some of the pure data source files contain includes of headers that don't exist on Apple platform.

Namely:
d_fft_fftw.c
s_audio_alsa.c
s_audio_alsamm.c
s_audio_mmio.c
s_audio_oss.c
s_audio_pa.c
s_midi_alsa.c
s_midi_mmio.c
s_midi_mmio.c
s_midi_pm.c

I have noticed that these are omitted from the libpd Xcode project, which makes me think it was the reason the issue has been overlooked.

**Comment by danomatika** [comment]
https://github.com/libpd/libpd/wiki/Unused-Source-List

**Comment by amethystdeceiver** [comment]
Thanks! I missed that.

**Comment by danomatika** [comment]
Those files exist in the pure-data upstream sources, but are not built with libpd since they are mainly platform specific implementations for things (audio & midi) which libpd abstracts through dummy interfaces.

**Comment by amethystdeceiver** [comment]
Yep, I understand that. I believe the podspec should reflect that, but currently it doesn't. 
Also, I've just found out that the spec doesn't include the 'extra' folder, while the compiler flags have -DLIBPD_EXTRA, which again leads to failed build.

**Comment by danomatika** [comment]
The current spec is not up to date. See #99.

**Comment by amethystdeceiver** [comment]
OK, I see.

**Comment by danomatika** [comment]
This was just fixed by a PR from @yairsz. Can you check it and close this issue if everything is working now?
