### ISSUE TITLE
iPhone 6s audio out of tune

### ISSUE THREAD

**Issue by cerupcat** [libpd/libpd#108]
I'm not sure if this is related to libpd or openframeworks, but I thought I'd here just in case.
All of my users on the new iPhone 6s are reporting that my tuning app is now reported / playing sound significantly flat. Has anyone else had reports of this (I don't yet have an iPhone 6s to test).

**Comment by danomatika** [comment]
Probably related to the iPhone 6S forcing a 48k sameplerate: https://forum.audiob.us/discussion/10362/ab-reports-warning-low-latency-on-iphone6s

**Comment by cerupcat** [comment]
Thanks @danomatika that's exactly the issue. When setting up the audio sample rate in OF / libPd, we have to get the sample rate from AVAudioSession after it's active to get the true sample rate of the device at the time.

**Comment by danomatika** [comment]
Well, that's true for the 6S, setting the sr should still work on other devices. Maybe we can query the device's desired samplerate. Quick hack would be to check device version and just use 48k (or whatever desired sr is returned) for 6S explicitly.

**Comment by cerupcat** [comment]
Yeah, that's a quick hack. The solution I'm using is what Apple recommends which is setting the preferred samplerate, but then actually getting the true one (in case it fails - like iPhone 6s) and using that one as the real one.

```
  // http://devmonologue.com/ios/tutorials/avaudiosession-bluetooth-support/
    // https://developer.apple.com/library/ios/qa/qa1799/_index.html
    NSError *audioSessionError = nil;
    AVAudioSession *session = [AVAudioSession sharedInstance];
    
    // disable active
    [session setActive:NO error:&audioSessionError];
    if (audioSessionError) {
        NSLog(@"Error %ld, %@",
              (long)audioSessionError.code, audioSessionError.localizedDescription);
    }
    
    // set category
    [session setCategory:AVAudioSessionCategoryPlayAndRecord withOptions:AVAudioSessionCategoryOptionAllowBluetooth|AVAudioSessionCategoryOptionMixWithOthers|AVAudioSessionCategoryOptionDefaultToSpeaker error:&audioSessionError];
    if (audioSessionError) {
        NSLog(@"Error %ld, %@",
              (long)audioSessionError.code, audioSessionError.localizedDescription);
    }
    
    double sampleRate = 48000; // I would prefer a sample rate of 44.1kHz
    [session setPreferredSampleRate:sampleRate error:&audioSessionError];
    if (audioSessionError) {
        NSLog(@"Error %ld, %@", (long)audioSessionError.code, audioSessionError.localizedDescription);
    }
    
    // *** Activate the audio session before asking for the "Current" values ***
    [session setActive:YES error:&audioSessionError];
    if (audioSessionError) {
        NSLog(@"Error %ld, %@", (long)audioSessionError.code, audioSessionError.localizedDescription);
    }
    
    NSLog(@"Sample Rate:%0.0fHz I/O Buffer Duration:%f", session.sampleRate, session.IOBufferDuration);

    // setup OF sound stream
    ofSoundStreamSetup(2, 1, this, session.sampleRate, 512, 3);
```

**Comment by danomatika** [comment]
Ok cool. Does this happen with libpd + the ObjC wrapper? If not, I'll add it.

**Comment by cerupcat** [comment]
I modified the code about slightly to show the pd.init line. 

In my code before I was setting the sample rate to just 44100 and that's the error. The value should come from AVAudioSession after activation to ensure you have the value the device is running at. Same should probably go for inputs and outputs, but haven't really seen an issue (for now) setting it to 2 output and 1 input hardcoded (it is possible to query though).

**Comment by danomatika** [comment]
Ok cool. t the least, I'll add that to the ofxPd iOS example.

**Comment by danomatika** [comment]
You should probably open an issue on the main OF repo since this is something that should be fixed for 0.9.0.

**Comment by danomatika** [comment]
Just to confirm for the record, it looks like we are indeed handling this in the libpd objc wrapper (https://github.com/libpd/libpd/blob/master/objc/PdAudioController.m#L136). I'll close the issue since the problem resides in OF's iOS implementation.

**Comment by cerupcat** [comment]
Will do. I created an issue there as well and will also point to here for a reference point.

**Comment by danomatika** [comment]
I added this to the ofxPd iOS example and the readme: https://github.com/danomatika/ofxPd/commit/3137c5cbda741d1216e233ede829c7915fdcb28f
