### ISSUE TITLE
C# 64bit DLL compilation

### ISSUE THREAD

**Issue by n1zzo** [libpd/libpd#110]
Unity 5 requires 64 bit DLLs, but using mingw-w64 for compilation leads to a broken DLL.
Is it possible to compile the csharp api to a 64 bit dll?

**Comment by danomatika** [comment]
How is the DLL broken? It should be possible but the C# wrapper may need to be updated. Probably not a lot of work, but we don't have a dedicated Windows developer right now.

**Comment by Stocarson** [comment]
I think it's a problem related to the MinGW-W64 compilation,
if I compile everything with MinGW (32bit), it all works fine.
If in mingw_build.bat I edit the MINGW variable pointing it to MinGW-W64
it seems to compile succesfully but in Unity I can't hear any sound.
How can I test my 64 bit DLL to give you more informations?

**Comment by djnewty** [comment]
Yes, I also have this problem. I need to build as 64. Everything works - apart from the sound. Please is there anything you can do to help???

**Comment by kuniea** [comment]
Yes, I also have this problem. I need to build as 64. Everything works - apart from the sound. Please is there anything you can do to help???

**Comment by Stocarson** [comment]
I needed the DLL for a Unity project and I bypassed the problem like others did:
by using the 32bit version of Unity on Windows.
While on linux and OSX the library compiles fine at 64 bit, so there I can use the 64 versions of Unity.
Sorry not to be more helpful than this.

**Comment by danomatika** [comment]
I don't have a windows machine, so we need some more information beyond "it doesn't work" :)

**Comment by danomatika** [comment]
Also, what did you change in the Makefile to build for 64 bit?

**Comment by kuniea** [comment]
Hi danomatika,

I changed this line in mingw_build.bat

From:
SET PATH=%MINGW32%\bin;%MINGW%\bin;%MSYS%\bin

To:
SET PATH=%MINGW64%\bin;%MINGW%\bin;%MSYS%\bin

I also had to install ming 64 for msys. Not sure exactly how I did that, but I now have an extra folder in msys that I didnt have before "/mingw64/" . With this installed I can use the mingw64_shell.bat to compile the libpd.dll (before there were linker errors).

**Comment by danomatika** [comment]
Ok thanks.

**Comment by danomatika** [comment]
I added a batch script to build a 64bit libpd on mingw: minnow_buil64.bat. Please test.

**Comment by danomatika** [comment]
I just merged a major PR that overhauls building libpd for C# including both 32 and 64 bit versions.
