### ISSUE TITLE
Can libpd display the GUI of the patch?

### ISSUE THREAD

**Issue by Mviljamaa** [libpd/libpd#116]
Is there anything in libpd that can be used to display the GUI of the loaded pd patch?

**Comment by danomatika** [comment]
On desktop, yes, see: https://github.com/libpd/libpd/pull/97

On mobile, no. PdDroidParty & PDParty emulate the Pd guis by intercepting send and receives messages to/from the widgets and implementing them in the platform graphical environment. PdParty, for instance, draws the widgets using Obj-C & CoreGraphics: https://github.com/danomatika/PdParty/tree/master/src/gui
