### ISSUE TITLE
PdTest leads to Undefined symbols for architecture x86_64.

### ISSUE THREAD

**Issue by Mviljamaa** [libpd/libpd#117]
I'm trying to replicate the project here:
https://github.com/libpd/libpd/tree/master/samples/cpp/pdtest/src

I've downloaded PdObject.h and PdObject.cpp.

My mainprogram.cpp has lines:

```
#include "PdBase.hpp"
#include "PdObject.h"

pd->subscribe("toCPP");
  
pd->setReceiver(pdObject);
pd->setMidiReceiver(pdObject);
```

My mainprogram.h has lines:

```
#include "PdBase.hpp"
#include "PdObject.h"

pd::PdBase * pd; // Pd engine
PdObject * pdObject; // Pd receiver
```

The lines:

~~~
pd->setReceiver(pdObject);
pd->setMidiReceiver(pdObject);
~~~

Give:

Running ld for x86_64 ...
Undefined symbols for architecture x86_64:
  "pd::PdBase::setReceiver(pd::PdReceiver*)", referenced from:
      PdPlug::PdPlug(IPlugInstanceInfo) in PdPlug.o
  "pd::PdBase::setMidiReceiver(pd::PdMidiReceiver*)", referenced from:
      PdPlug::PdPlug(IPlugInstanceInfo) in PdPlug.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by danomatika** [comment]
Are you building libpd with C++ support?

**Comment by Mviljamaa** [comment]
It should be OK, the lib is taken from a project that used it in C++. I didn't build it.

**Comment by Mviljamaa** [comment]
I was thinking that do I need to add something more, than merely the library and header paths that make

`#include "PdBase.hpp"
#include "PdObject.h"
`
found.

In StackOverflow it was claimed that this is commonly related to "not having linked the headers and libraries" or e.g. "not having included the files in the project".

**Comment by danomatika** [comment]
You need to include the correct paths to the libpd & cpp headers as well. Look in the sample project makefile.

**Comment by Mviljamaa** [comment]
I believe I have included them. Since e.g. lines:

`pd::PdBase * pd; // Pd engine
PdObject * pdObject; // Pd receiver`

and

`pd->subscribe("toCPP");`

compile fine.

**Comment by danomatika** [comment]
No, I mean in have you included the paths to the compiler itself? As in something using the C/CXXFLAGS like:

   gcc -I../path/to/libpd/cpp

See https://github.com/libpd/libpd/blob/master/samples/cpp/pdtest/Makefile#L27

**Comment by Mviljamaa** [comment]
I think that's in Xcode done by adding the library to Build Phases -> Link Binary With Libraries.

**Comment by Mviljamaa** [comment]
Adding the libpd-osx.a file to Build Phases -> Link Binary With Libraries does not solve the problem.

**Comment by Mviljamaa** [comment]
Oddly I cannot see any libpd headers under Build Phases -> Headers.

**Comment by Mviljamaa** [comment]
The paths are set under Build Settings however.

**Comment by danomatika** [comment]
Well, I couldn't tell how you are working with it as you didn;t provide info such as what OS your working on and how you're building it.

The Xcode lib does *not* build the CPP layer, it only builds and links the C libpd library. In the same manner, it doesn't include Obj-C layer either. You need to manually add the libpd/cpp folder to your project so it will build the cpp layer as well.

**Comment by Mviljamaa** [comment]
I haven't had the need to add manually under Build Phases -> Headers. In some other projects I've made in Xcode.

**Comment by Mviljamaa** [comment]
I have the cpp sources including e.g. PdBase.h in the Xcode paths. They should be fine.

**Comment by Mviljamaa** [comment]
But do you think I need to additionally make it explicitly referenced in the project. I.e. add it to the project, not merely give paths to the folder?

**Comment by danomatika** [comment]
I think we are talking about two separate things now. By "you need to manually add the libpd/cpp folder to your project" I mean you need to add those files directly to your project, not just a header include path.

>But do you think I need to additionally make it explicitly referenced in the project. I.e. add it to the project, not merely give paths to the folder?

Yes. That's what I mean by "the libpd Xcode project does not include the cpp files".

This is how the pdtest Xcode project looks:

<img width="259" alt="screen shot 2016-02-11 at 4 22 44 pm" src="https://cloud.githubusercontent.com/assets/480637/12994173/c09a0e08-d0db-11e5-8206-e60e62b4d17d.png">

Note that the cpp folder is added to the project itself as it's not part of the libpd.xcodeproj. This is because there are plenty of cases to where you don't need the cpp layer.

**Comment by Mviljamaa** [comment]
Upon dragging and dropping those files to the same level as my mainprogram, the error count goes up to 40-60.

**Comment by danomatika** [comment]
Sorry, I don;t have much time right now and "the error count goes up to 40-60" is not helpful to solving a problem at all. Maybe include a screenshot?

**Comment by Mviljamaa** [comment]
Here I'm adding PdBase.cpp and PdBase.h

![screen shot 2016-02-12 at 01 30 46](https://cloud.githubusercontent.com/assets/1913544/12994312/4e75fbd2-d128-11e5-9580-dc0b267652b5.png)
![screen shot 2016-02-12 at 01 30 25](https://cloud.githubusercontent.com/assets/1913544/12994311/4e73fc1a-d128-11e5-94a4-79580d66e33e.png)

**Comment by Mviljamaa** [comment]
I'm thinking that I might have to add a lot more files. Since it seems like PdBase.cpp and PdBase.h are referencing something more, that should be included.

**Comment by danomatika** [comment]
Yes. You need to add all the files in `libpd/cpp` since that is the entire cpp wrapper, not just PdBase. Just drag the cpp folder init Xcode.

**Comment by Mviljamaa** [comment]
Ok so now it looks like:

![screen shot 2016-02-12 at 01 40 23](https://cloud.githubusercontent.com/assets/1913544/12994475/a72643c6-d129-11e5-85f2-7ab5ad476391.png)

**Comment by danomatika** [comment]
Yup. Now you are missing libpd itself. You need to drag the libpd.xcodeproj into Xcode and make sure the checkboxes are checked when assed to "Add to target".

**Comment by danomatika** [comment]
You don;t need to add the libpd C files into your project, they are handled by the xcodeproject. You only needed to manually add the contents of `libpd/cpp`.

**Comment by Mviljamaa** [comment]
Weird. The one I was copying regarding the folder structure, didn't have the libpd xcodeproject anywhere.

https://github.com/logsol/Pd-Pulp

**Comment by Mviljamaa** [comment]
Is that perhaps constructed by adding all .c files? There's a lot of them under the folder 'libpd'.

**Comment by danomatika** [comment]
They are using a precompiled library. IMO it's better to use libpd itself and the xcodeproject as you can more easily update to newer versions.

**Comment by Mviljamaa** [comment]
So you think I'll need to add this one now:

https://github.com/libpd/libpd/tree/master/libpd.xcodeproj

?

**Comment by danomatika** [comment]
Uh yes. That's what I mean by "libpd.xcdeproj". It basically includes all the files needed to build libpd with the correct settings and builds a state library which you then link to your project. Drawing it into Xcode and checking the add to target box sets up everything.

**Comment by Mviljamaa** [comment]
![screen shot 2016-02-12 at 01 50 27](https://cloud.githubusercontent.com/assets/1913544/12994683/0c815ff2-d12b-11e5-8e69-8be6dfd5fbcf.png)

Changed nothing.

**Comment by Mviljamaa** [comment]
Weird.

I removed the .xcodeproj and did Clean.

Now:

![screen shot 2016-02-12 at 01 53 52](https://cloud.githubusercontent.com/assets/1913544/12994775/893e513a-d12b-11e5-9aac-7ef005761e77.png)

And

![screen shot 2016-02-12 at 01 54 43](https://cloud.githubusercontent.com/assets/1913544/12994784/9ec3fe24-d12b-11e5-8714-1d0b6aa9604c.png)

**Comment by danomatika** [comment]
Did you check the "add to targets" option? Probably not.

You are still not linking the libpd static library. Try this:

* Click on PdPlug in the tree
* Click on PdPlug under the Targets list
* Scroll down to linked Frameworks and Libraries
* Click the + icon
* Select libpd-ios from the list

Good luck. I have class now. I'd suggest reading some Xcode how to's as adding and using a static library is a pretty common requirement for projects.

**Comment by Mviljamaa** [comment]
Why libpd-ios? I'm not developing for ios.

**Comment by danomatika** [comment]
That was a typo. If you're building for OS X, use libpd-osx.

**Comment by Mviljamaa** [comment]
Okay so this is what I have (I reverted the changes done earlier in this thread) after adding the src folder and the .xcodeproject.

![screen shot 2016-02-12 at 02 37 23](https://cloud.githubusercontent.com/assets/1913544/12995642/9f42c0be-d131-11e5-8fc8-928231cc592b.png)

Upon doing this:

> 
    Click on PdPlug in the tree
    Click on PdPlug under the Targets list
    Scroll down to linked Frameworks and Libraries
    Click the + icon
    Select libpd-ios or lib-osx from the list (depending on what platform you need)

And Clean.

The warnings seem to supress but the build still fails:

![screen shot 2016-02-12 at 02 40 15](https://cloud.githubusercontent.com/assets/1913544/12995684/0713feec-d132-11e5-923a-e8196fb6662a.png)

**Comment by Mviljamaa** [comment]
Ok after switching to 32-bit and back to 64-bit (no other changes) there seems to be warning produced after all.

![screen shot 2016-02-12 at 02 44 35](https://cloud.githubusercontent.com/assets/1913544/12995772/a5914534-d132-11e5-8b6a-ce644b759312.png)

**Comment by Mviljamaa** [comment]
I think it'd be helpful if the build instructions were more clearly available in some libpd's site.
I.e. how to to the stuff (including headers and all) that I'm trying to do here.

**Comment by danomatika** [comment]
The wiki contains the essential info for understanding how to work with libpd & the language wrappers. As with many open source projects, there is a requirement for a certain amount of knowledge in order understand working with the lower level aspects of the library including how makefiles and build systems work. As such, it doesn't cover every detail for every OS / development environment, which can often change leaving outdated documentation.

in this case, you're issue seems to stem from having problems adding the libpd static library xcodeproject into your main xcodeproject. The following will probably be helpful:

* [Making Musical Apps: Real-time audio synthesis on Android and iOS](http://libpd.cc/read-the-book/) (the libpd book)
* [Learning libPD for iOS: 03. Importing libPD into Xcode](https://www.youtube.com/watch?v=l5GQqCDmBZY) (video)
* [Linking a static library to an iOS project in XCode 4](http://stackoverflow.com/questions/6124523/linking-a-static-library-to-an-ios-project-in-xcode-4) (via Google search)

**Comment by danomatika** [comment]
We do have some basic info for working with Xcode on the pd-for-ios page: https://github.com/libpd/pd-for-ios/wiki/ios

I took that and wrote up a general how to to the wiki: https://github.com/libpd/libpd/wiki/libpd-xcode

**Comment by Mviljamaa** [comment]
After succesfully adding and building libpd like described here:
https://github.com/libpd/libpd/issues/121

This problem still persists.

I can #include "PdBase.h" but upon making any function calls, the error described in this thread pops up.

**Comment by Mviljamaa** [comment]
I've included libpd as described here:
https://github.com/libpd/libpd/issues/121

And the problem described in this thread persists.

MyPlug.h:

`pd::PdBase * pdengine; // pd engine`

In MyPlug.cpp

```
pdengine = new pd::PdBase(); (this creates the ld_symbol error)
pdengine->subscribe("toCPP") (if the above line is removed, then this doesn't create the error)
```

The project is open source and seen here:
https://github.com/Mviljamaa/PdPlug
