### ISSUE TITLE
How to build on both OSX and Windows?

### ISSUE THREAD

**Issue by Mviljamaa** [libpd/libpd#118]
How to build libpd on both OSX and Windows?

Do I need to use the C library?

Do I need to use MinGW on Windows?

**Comment by danomatika** [comment]
>How to build libpd on both OSX and Windows?

https://github.com/libpd/libpd#androidmk-makefile-libpdxcodeproj-libpd_winsln

There is also the libpd.xcodeproject for working with Xcode.

>Do I need to use the C library?

libpd *is* a C library. All of the language wrappers use the C library as their core & they will not function without it.

>Do I need to use MinGW on Windows?

Thats the easiest way to build libpd as a .dll. I *think* it will build in Visual Studio now, but I haven't tried in a while so can;t say personally.
