### ISSUE TITLE
Upon commiting a project that has libpd added (the static library build), Git Desktop gives error: Failed to add file libs/libpd/jni/opensl_stream/ to index.

### ISSUE THREAD

**Issue by Mviljamaa** [libpd/libpd#121]
I have added libpd to my project using these instructions:
https://github.com/libpd/libpd/wiki/Working-with-libpd-in-Xcode#add

Now I'm trying to commit the additions I made to Git.

Upon commiting a project that has libpd added (the static library build), Git Desktop gives error: 

`Failed to add file libs/libpd/jni/opensl_stream/ to index.`

Is this related to libpd or Git Desktop?

**Comment by danomatika** [comment]
If you're utilizing libpd, I would ad it as a submodule instead of including the files directly. This makes it easier update libpd.

**Comment by Mviljamaa** [comment]
Like this?

```
git clone https://github.com/libpd/libpd.git
cd libpd
git submodule init
git submodule update
```

Or

`git submodule https://github.com/libpd/libpd.git` while in MyProject folder?

**Comment by danomatika** [comment]
The second.

**Comment by Mviljamaa** [comment]
It seems to not include the pure-data folder contents.

**Comment by danomatika** [comment]
It does but you need to update the submodule within libpd as well.

**Comment by Mviljamaa** [comment]
Like how?

**Comment by Mviljamaa** [comment]
I did:

In the folder MyProject/libs/
```
git submodule add https://github.com/libpd/libpd.git
cd libpd
git submodule init
git submodule update
```


Now upon commiting Git Desktop gives:

Failed to add file libs/libpd/ to index

**Comment by Mviljamaa** [comment]
Ok I got over the error

`Failed to add file libs/libpd/ to index`

By doing the "add libpd as submodule" correctly. I had done some error in it.
