### ISSUE TITLE
Using libpd as a git submodule / Adding cpp headers / Commiting changes

### ISSUE THREAD

**Issue by Mviljamaa** [libpd/libpd#122]
I have added libpd as a submodule to my project. And now trying to do this:
https://github.com/libpd/libpd/wiki/Working-with-libpd-in-Xcode#c-wrapper

When adding the libpd/cpp folder to my project under libpd.xcodeproj (the cpp folder hasn't been added by default)

![screen shot 2016-02-13 at 15 30 42](https://cloud.githubusercontent.com/assets/1913544/13027835/c988c4d2-d266-11e5-80d8-99a9a1230c60.png)

Git asks me to commit some changes to the libpd folder separate from the "main branch" commit I just made.

![screen shot 2016-02-13 at 15 32 10](https://cloud.githubusercontent.com/assets/1913544/13027857/55d0b15c-d267-11e5-9e1f-ec1bf0c1588b.png)

It doesn't ask separately about commits to libpd folder if I don't add the cpp folder under libpd.xcodeproj, but rather just under MyProj.

i.e. like

![screen shot 2016-02-13 at 15 36 04](https://cloud.githubusercontent.com/assets/1913544/13027865/8f45cada-d267-11e5-8695-98afd5892307.png)

However I'd like the folder to be under libpd.xcodeproj, because I think it's cleaner.

**Comment by danomatika** [comment]
Please stop spamming us with issues related to setting up your individual project. I suggest looking at online tutorials on how to use git & git submodules. Only post issues that are verifiable bugs with libpd itself. This is an open source project and any time spent on it is done for free.

**Comment by Mviljamaa** [comment]
I think this is related to the usage of libpd. It'd be more senseful to have the cpp under the libpd.xcodeproj. But it doesn't seem to be feasible.

**Comment by Mviljamaa** [comment]
Now I can move these questions to a forum or something as well, if there's such.
