### ISSUE TITLE
Please add receiver example code to pdtest/src/main.cpp

### ISSUE THREAD

**Issue by Mviljamaa** [libpd/libpd#124]
Please add code to

https://github.com/libpd/libpd/blob/master/samples/cpp/pdtest/src/main.cpp

for how the receivers are supposed to be used.

**Comment by danomatika** [comment]
That would the PdObject class which are the two files in the same folder: https://github.com/libpd/libpd/blob/master/samples/cpp/pdtest/src/PdObject.h

**Comment by Mviljamaa** [comment]
Yes I know, but I don't understand the functions (specifically their parameters) in PdObject.h.

E.g.

void receiveMessage(const std::string& dest, const std::string& msg, const pd::List& list);

What are the parameters?

**Comment by danomatika** [comment]
[string](http://lmgtfy.com/?q=C%2B%2B+std%3A%3Astring)

[pd::List](https://github.com/libpd/libpd/blob/master/cpp/PdTypes.hpp#L103) (also noted in the [Wiki](wiki/C---Wrapper-for-libpd#overview))

**Comment by danomatika** [comment]
Also, "dest" in the name of the receiver that you sent the message to in the pd patch aka

[message<
|
[s some-receiver]

and everything else is the contents of the message itself, whether it's a single float, or a list of things, etc.

receiveMessage receives explicit messages sent via message boxes aka:

[bang<
|
[ ; some-receiver message hello]

In this case, "some-receiver" will be dest and "message" will be msg.

**Comment by Mviljamaa** [comment]
I see that the PdObject is just printing its parameters.

How is that reading from messages received from Pd? Or is this functionality hidden somewhere?

**Comment by danomatika** [comment]
Well, to "just print it's parameters" involves actually receiving the messages. PdObject implements the pd::PdReceiver & pd::PdMidiReceiver classes whose functions are used as [callback functions](pd::PdReceiver, public pd::PdMidiReceiver).

**Comment by Mviljamaa** [comment]
So how should I be receiving e.g. note ons?

By calling receiveNoteOn on every process-loop call? The values are then saved at the parameters that I passed as parameters, yes?

**Comment by danomatika** [comment]
No, you have it backwards.

libpd calls those functions itself, you do not call them yourself. You implant those functions in your class, and tell libpd to use that class as a receiver. In those function you then implement code to handle the received messages.

**Comment by Mviljamaa** [comment]
Aha, so I'm supposed to replace the cout prints with my own way of dealing with them.

So e.g. I receive

void receiveMessage(const std::string& dest, const std::string& msg, const pd::List& list);

Where dest tells which object sent it, message is the message, but what's the list?

**Comment by danomatika** [comment]
list is the actual data that is sent aka a list of floats & symbols, if any

Again, receive message only processes things sent from message boxes. Most of the tie, you handle things via receiveBang, receiveFloat, receiveSymbol, & receiveList.

**Comment by Mviljamaa** [comment]
I assume that I need to write filters myself.

Since e.g. receiveFloat would get all "float messages" from all destinations. So if I wish to pick floats from only a certain destination, then I need to filter them out of the rests of the floats that I may receive?

**Comment by danomatika** [comment]
Well, you will only receive things sent to send names you allow via subscribing to them: https://github.com/libpd/libpd/blob/master/cpp/PdBase.hpp#L180

If you don't subscribe to anything, you won't receive anything. If you subscribe to multiple send names, filtering them is easy via something like:

    if(dest == "send1") {
        /// do something
    }
    else if(dest == "send2") {
       // do something else
    }
