### ISSUE TITLE
Does libpd use voice allocation / how does libpd handle polyphony?

### ISSUE THREAD

**Issue by Mviljamaa** [libpd/libpd#125]
Do I need to do something in order to have libpd support polyphony or can I merely send notes to sendNote?

**Comment by danomatika** [comment]
Please stop opening new issues when you have basic questions. Please ask on the pd forum or the pd list.

Again, the issue system is used for bug reports not for general questions.

**Comment by Mviljamaa** [comment]
So pd-list is for libpd questions as well? Ok.
