### ISSUE TITLE
(setup.py needs updating) pylibpd expr~ won't compile

### ISSUE THREAD

**Issue by mmxgn** [libpd/libpd#128]
Hello,

Just so you know, recent pulls of pure-data apparently have expr~ in the base source and not as 
an extra (if I say that correctly, I am a total pd noob), but setup.py still looks in pure-data/extra/expr~ for the files needed. I managed to make it build by changing setup.py to point to the appropriate pure-data/src files but I thought you might want to change that upstream.

Thanks and regards

Manos

**Comment by nettoyeurny** [comment]
Thanks, Manos! Do you want to create a pull request?

**Comment by danomatika** [comment]
I have recently updated the master branch to start using the latest pure-data. I'd suggest using the last stable release tag instead of the master since not all of the wrappers have been updated yet.

**Comment by mmxgn** [comment]
Hello,
Thanks for the replies.

@nettoyeurny I am not sure I should do that. The wrapper compiles like this but I told you I am a total pd (and libpd) noob so something might break in the runtime. I am not sure how to test.

@danomatika I think the help file (for the python at least) should specifically specify that.
