### ISSUE TITLE
Multiple instance support

### ISSUE THREAD

**Issue by wtholliday** [libpd/libpd#13]
What would be involved in extending libpd to support multiple instances in a single process?

**Comment by jcelerier** [comment]
It looks like there was some work done in order to achieve multiple instances : http://comments.gmane.org/gmane.comp.multimedia.puredata.devel/12660

**Comment by danomatika** [comment]
I'm aware. The work so far was still marked as "tentative", so I was waiting to see if it would stabilize ... that and I only updated to vanilla 0.46 recently.

**Comment by danomatika** [comment]
Note: we added Millers upstream work on (prelim) multiple instance support in libpd 0.8.0. See the [pdtest_mulit sample](https://github.com/libpd/libpd/tree/master/samples/c/pdtest_multi).

**Comment by wtholliday** [comment]
Is the plan to just have the global called `pd_this`? That isn't a thread-safe way to do multiple instances. Could thread-local storage be used?

**Comment by danomatika** [comment]
No that is not the plan. The access is currently in the experimental stage and the api wile wrapped by a libpd call at some point. If you have specific ideas on how best to do this, I would start a discussion on the pd-dev list as this support is largely coming form upstream.

**Comment by jcelerier** [comment]
with the current code, is there a possibility to set "audio inputs" per instance ? I'd like to be able to use multiple Pd patches to process audio in my software as if each patch was similar to a VST plug-in or something like this.

thanks!

**Comment by danomatika** [comment]
Set the instance and then process the samples. It's up to you where the samples come from or go to...

Note: multi instance support is kind of working but there are still some issues with it.

**Comment by martinfinke** [comment]
> Note: multi instance support is kind of working but there are still some issues with it.

What kind are these issues? Do they cause undefined behaviour, or can you somehow work around them by taking certain precautions etc.?

**Comment by danomatika** [comment]
I don't know exactly. Again, this is *prelim* work so it may crash. Ask on the pd-list as there are a few people who are using it but I think they had to add some things or it to work best. It would be good to restart the discussion and see if we can get some of that work integrated back into pd.

**Comment by jcelerier** [comment]
Is changing the number of audio i/o per instance possible ? Or should `libpd_init_audio` be called only once ?

**Comment by danomatika** [comment]
Pd instance support was expanded with the latest Pd update. See the pdtest_multi C sample.

**Comment by danomatika** [comment]
We have multiple instance support more or less working thanks to major changes in upstream pd. See the pdtest_multi and pdtest_thread C samples.
