### ISSUE TITLE
Outdated podspec

### ISSUE THREAD

**Issue by Apolotary** [libpd/libpd#131]
Hi,

I noticed that on cocoapods the latest version of libpd 0.7.0 https://cocoapods.org/pods/libpd

but the latest version in your readme is 0.8.3, is it possible to update the podspec?

Thanks!

**Comment by danomatika** [comment]
We don't maintain that pod spec, we have our own which is currently up to date. You'll need to contact the maintainer of that pod spec.

**Comment by Apolotary** [comment]
Ah didn't know that, could you please share a link to your current podspec? Sorry for the trouble

**Comment by Apolotary** [comment]
nevermind, found it in the readme, apologies for the noise
