### ISSUE TITLE
messages and threads

### ISSUE THREAD

**Issue by giuliomoro** [libpd/libpd#134]
The wiki reads

> Moreover, only one thread may assemble a compound message at any given time

Surely this applies to messages assembled with

``` c
int libpd_start_message(int max_length)
void libpd_add_float(float value)
void libpd_add_symbol(const char *symbol)
int libpd_finish_list(const char *destination)
int libpd_finish_message(const char *destination, const char *symbol)
```

does it also apply to the ``flexible approach'' which involves

``` c
        t_atom v[2];
        libpd_set_float(v, 3.14);
        libpd_set_symbol(v + 1, "zzz");
        libpd_message("foo", "bar", 2, v);
```

??

**Comment by danomatika** [comment]
>Surely this applies to messages assembled with

Yes. The low level C library is not thread safe. Thread safety is left up to the programmer and the various language wrappers/environments for now. Hopefully this will change in the future upstream...

>does it also apply to the ``flexible approach'' which involves

Yes.
