### ISSUE TITLE
set delay for message

### ISSUE THREAD

**Issue by giuliomoro** [libpd/libpd#135]
Is it possible to send a message with a given delay?
For instance, before calling the libpd_process_float I analyze one of  the input buffers and decide that there should be a bang at, say, sample 10. Can I schedule the bang so that it gets delivered at sample 10, or am I limited by the granularity of one tick (DEFDACBLKSIZE) ?

**Comment by giuliomoro** [comment]
This behaviour could probably be emulated with 
```pd
[r message-bang]
|        [r message-delay]
|        |
[delay ]
```

and 

```c
libpd_float("message-bang", delay_time_ms);
libpd_bang("message-content");
```

**Comment by danomatika** [comment]
No, the sending is as immediate as possible.
