### ISSUE TITLE
Allow direct access to sys_soundin and sys_soundout

### ISSUE THREAD

**Issue by giuliomoro** [libpd/libpd#137]
In my application I have some interleaved buffers that have a number of frames different from DEFDACBLKSIZE. Currently I have to copy my samples to an intermediate buffer which is in the format expected by `libpd_process_raw()`.

If I had direct access to Pd's `sys_soundin` and `sys_soundout`, I would, instead, populate these directly (instead of having it done in `libpd_process_raw()`), saving quite a few memory operations.

This would also benefit anyone who needs to rearrange their buffers before calling libpd_process_raw() 
e.g.:  those who have non-interleaved buffers and would, as they have to wrap the call to `libpd_process_raw()` into memory operations that could be save if they had direct access to `sys_soundin` and `sys_soundout`.

I would therefore suggest the following additions to the API:

``` c
t_sample* libpd_get_soundin(){
  return sys_soundin;
}
t_sample* libpd_get_soundout(){
  return sys_soundout;
}
void libpd_process_sys(){
  sys_microsleep(0);
  memset(sys_soundout, 0, sys_outchannels*DEFDACBLKSIZE*sizeof(t_sample));
  SCHED_TICK(sys_time + sys_time_per_dsp_tick);
}
```

although I see how this would break encapsulation because Pd's internal sample format t_sample would need to be known to the calling application.

**Comment by danomatika** [comment]
You have direct access if you want, just include `m_pd.h`.

**Comment by giuliomoro** [comment]
Thanks @danomatika 
`sys_soundin` and `sys_soundout` are declared in m_stuff.h, which, as described in the file itself 
```
/* NOTE: this file describes Pd implementation details which may change
in future releases.  The public (stable) API is in m_pd.h. */  
```

I tried to sys_soundin and sys_soundout in my application. I include m_stuff.h, it compiles and links ok, but every time I try to access these varaiables they are set to NULL (even while the audio is running correctly, e.g. with `libpd_process_float()`), while if I printf them from within libpd_process_float() they display their correct value.

When printing the address of the sys_soundin variable form within libpd and myapp with, e.g.:
```c
	printf("myapp sys_soundin 0x%x 0x%x\n", &sys_soundin, sys_soundin);
```
I get:
```
libpd sys_soundin: 0xb6f7eda0 0x54980
libpd sys_soundout: 0xb6f7eda8 0x54ac8
myapp sys_soundin 0x29888 0x0
myapp sys_soundout 0x299b0 0x0
```
so ti looks like there exist two global variables with that same name, one used by libpd and one used by myapp.

I should also mention that if I try to use `get_sys_soundin()` and `get_sys_soundout()` (also defined in s_stuff.h), I get an error when I link my application against libpd:  
`render.cpp:(.text+0x4a6): undefined reference to `get_sys_soundin()'`  
this is unexpected,as they actually show up in the exported symbols of libdp.so

This is the relevant content of my libpd.so . I am on arm-linux-gnueabihf (32bit)
```bash
$ nm /usr/lib/libpd.so | grep sys_sound
0005a050 T get_sys_soundin
0005a03c T get_sys_soundout
000a9040 B sys_soundin
000a0220 b sys_soundindevlist
000a9048 B sys_soundout
000a0230 b sys_soundoutdevlist
```

**Comment by danomatika** [comment]
@nettoyeurny

**Comment by danomatika** [comment]
This is a lower level question best looked into by @millerpuckette. Do your suggested API additions work if you add them?

**Comment by nettoyeurny** [comment]
Late to the party, but here's my take: Exposing sys_sound{in,out} in the API is bad because in a concurrent setting, those buffers aren't safe to use without synchronization. There's a reason for the defensive copying in the processing callback; it avoids races when accessing internal buffers, and the extra copy is a small price to pay for safety and ease of use.

**Comment by giuliomoro** [comment]
agreed. As to why it did not work for me in the first place: turned out my issue was pretty and I had no `extern "C"{}` around `#include <s_stuff.h>` in my C++ program.
