### ISSUE TITLE
adding 3rd party externals to libpd

### ISSUE THREAD

**Issue by batchku** [libpd/libpd#140]
i'm working on a libpd based iOS app with MobMuPlat.
i see that a few additional externals (like fiddle~ and bonk~) are included;
i'm trying to compile another 3rd party external to include in libpd for my app.

could anyone point me to any instructions for how to go about doing that?

-ali

**Comment by danomatika** [comment]
This is from ofxPd, but it's the same idea: https://github.com/danomatika/ofxPd#adding-pure-data-external-libraries-to-ofxpd

**Comment by batchku** [comment]
Thanks for your help Dan;
I looked at the instruction in your link; I accordingly found the places in the MobMuPlat project where the setup functions of the externs are executed; they are in

z_libpd.c:
...
// (optional) built in pd externals setup functions
#ifdef LIBPD_EXTRA
  void bob_tilde_setup();
  void bonk_tilde_setup();
  void choice_setup();
  void expr_setup(); // also loads expr~ & fexpr~
  void fiddle_tilde_setup();
  void loop_tilde_setup();
  void lrshift_tilde_setup();
  void pique_setup();
  void sigmund_tilde_setup();
  void stdout_setup();
  void resonators_tilde_setup();   //  i added this line
#endif
...

and

MMPViewController.m:
...
extern void expr_setup(void);
extern void bonk_tilde_setup(void);
extern void choice_setup(void);
extern void fiddle_tilde_setup(void);
extern void loop_tilde_setup(void);
extern void lrshift_tilde_setup(void);
extern void sigmund_tilde_setup(void);
extern void pique_setup(void);
extern void resonators_tilde_setup(void);      //   i added this line
...

I also added the .c file for my extern to the "Compile Sources" list in xcode, for the target i'm building.

I'm able to build both libpd-ios and mobmuplat with no errors; however, the pd console in mobmuplat on my ios device indicates that it's not able to create an instance of my external.

am i missing any steps?

a

**Comment by batchku** [comment]
update:
Got this working.
