### ISSUE TITLE
Receiving values from PD with C++

### ISSUE THREAD

**Issue by helenacelle** [libpd/libpd#145]
Having some issues understanding how to receive a float value from PD using C++ and assigning it to a variable. The value changes so I'd need to update it in a loop to reflect this. I'm having no issues with sending values to PD at all but I think I need to see an example of how to receive a float value and assign it, apologies if I've missed out on something in documentation, any help is massively appreciated.

**Comment by danomatika** [comment]
You need to implement a subclass of the PdReceiver and/or PdMidiReceiver abstract classes and then implement the callback function for receiving messages aka `receiveBang`, `receiveFloat, etc.

See the [pdtest cpp sample](https://github.com/libpd/libpd/tree/master/samples/cpp/pdtest)

**Comment by helenacelle** [comment]
Thanks! I had a look at the example and I've managed to get the value I need outputting via receiveMessages, but I'm not sure how to implement it in order to then output this value received into a temporary variable. I know it's probably something glaringly obvious or simple but I'm hitting a wall with it right now.
