### ISSUE TITLE
iPhone 6S cannot set hardware sample rate

### ISSUE THREAD

**Issue by monkeyswarm** [libpd/libpd#148]
Apps on iPhone6s cannot set the sample rate via PdAudioController (via setPreferredSampleRate), as the hardware rate is fixed at 48K. (Once headphones or another audio device is plugged in, the sample rate can be changed.)

See discussions at 
http://forum.theamazingaudioengine.com/discussion/944/important-announcement-taae-and-the-iphone-6s#latest
and
https://forums.developer.apple.com/message/72961#72961

Fix is non-trivial, to leave hardware rate as-is and do sample rate conversion in the audio unit chain (which I believe is what TAAE does). Or to remove the ability to set hardware sample rate unless the current audio hardware supports it.
Though arguably not a big deal at the moment, if upcoming Apple audio hardware continues this fixed-rate trend (headphone jack RIP), it may be worth discussing.

**Comment by danomatika** [comment]
Yup. See https://github.com/libpd/libpd/issues/108

**Comment by danomatika** [comment]
As it is now, the audio controller does it the recommended way: try to set a desired sameplerate and then check what the actual value is afterward. On the user end, you can check what the audio controller sample rate is and see if it jives with what you intended. I don't really see a compelling reason to add a sample rate conversion step as this has been the case for over a year and seems to be working for most people.

**Comment by monkeyswarm** [comment]
Ah thanks for the link. I agree that there is not a compelling case at the moment. But if we are moving into a future of fixed-rate audio hardware, then _eventually_ there will be less of a case to have libpd sample rate be settable at all (if it won't work most of the time).
Closing...for now...

**Comment by danomatika** [comment]
I'd still like to support those devices which aren't locked to 48k. At the least, we could set the default to 48k...

**Comment by ashshaosh** [comment]
Looks like obj-c now need this fix too. New iPhone8 have 48000 by default.
On simulator, when I set SR to 48000 I hear wrong noises :)
After resetting audio-session with hardware SR, all works fine. 
Waiting for beta-testers approval now :)

**Comment by o-g-sus** [comment]
I think this issue is not fixed yet. I updated to the newest Object-C version, but I hear glitches on my effect app on my iPhone 6s, not on all my iPads ...

**Comment by danomatika** [comment]
There are a number of issues with newer devices that need to be fixed, including variable buffer sizes. Hopefully We (I) can get to this soon. It would be jive to get some help as I don't actually have a newer device which exhibits these issues.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by monkeyswarm** [comment]
I still agree with Dan's assessment in post #3: user can request a sample rate, but the rate may not be supported, and user has to see what the actual rate is. That is how audio devices have always worked. I still don't think an in-software sample rate conversion is warranted (but I am biased in that regard...do others want a CPU-eating conversion?)

I'm unclear as to what the new issue or feature request is here, and what, if anything has changed since the initial post. If you want to deploy a patch to iOS, it needs to run correctly at both 44.1K and 48K: devices may default to either on startup, and the audio rate may change at any time. 

Or is there another issue? Inter-app audio routing? Patches wanting to know when rate has changed? etc?

**Comment by danomatika** [comment]
See #228 and please test. I don't have a newer iOS device without a headphone jack and am waiting for people to confirm the PR is working before putting out the next release.
