### ISSUE TITLE
Restructuring the C# API

### ISSUE THREAD

**Issue by residuum** [libpd/libpd#153]
The C# API in its current form is not idiomatic: It is just an abstraction of the C API into one large static class. It does the job, but sticks out like a sore thumb, when you try to use it.

I have built some small demo and test projects, and have also started to [document](https://github.com/libpd/libpd/wiki/C%23) the API.

I would like to keep the current API alive, as [libpd4unity](https://github.com/patricksebastien/libpd4unity) et al. depend on it. The new API would be a supplement to the existing one.

I would like to change that, and propose the following structure:
- The new API should return objects for loaded patches and bound receivers. 
- These new classes should be `IDisposable` to facilitate releasing of resources (`Patch.Dispose()` should call `libpd_closefile()`, etc.).
- PdManager in the Python API is an example of a new class that I have in mind.
- Static methods should be reduced to a minimum, maybe even eliminated.

Is anyone willing to help with this project, even only for a discussion of the new design?

**Comment by danomatika** [comment]
Most of the language wrapper find a balance between sticking with the C API and for adding language-specific support, etc. I think your proposal sounds like such.

The C++ wrapper, for instance, wraps the C API but through classes and provides convenience classes around files and lists. It also avoids a global static class in order to hopefully support multi instances later on.

Also, APIs change over time so I think it's reasonable to make improvements and mark things deprecated for a period of time, then remove the old interfaces.

**Comment by nettoyeurny** [comment]
Quick note on timing: I entirely agree that this is a worthwhile project, but the real question is when to do this. While the current C API of libpd has been holding up really well, it does reflect Pd as it was six years ago. I've been waiting for two substantial changes to Pd, multi-instance support and a clear separation between the GUI and the audio core.

Once those are in place (multi-instance support seems to be well on its way), that'll be an opportunity to create libpd 2.0, and then it'll make a lot of sense to get rid of all the static stuff in the object-oriented bindings.

(I'm not objecting to doing this now, just pointing out that if we do this now, we may end up doing it yet again in the not too distant future.)

**Comment by residuum** [comment]
@nettoyeurny I would say that restructuring of the C# API should be done now, while deprecating the old API, so that all users already use the non-static, multi-instance ready version.

**Comment by danomatika** [comment]
The same is true of the Obj-C wrapper which uses a main static class. I'm fine with waiting for an overall API update of that as people with legacy stuff can stick with "libpd 0.#.#" and then later port to "libpd 1.#.#".

**Comment by danomatika** [comment]
Close via merging #154.
