### ISSUE TITLE
Avoid sending NaN and Inf to unsupported objects

### ISSUE THREAD

**Issue by cerupcat** [libpd/libpd#156]
I know this isn't libpd specific, but I'm wondering if there's a libpd compiler flag to fix this issue...

Currently, I'm using a ADC on iOS and when I disable input (temporarily) within my application, it sends `NaN` or `Inf` to `hip~` the hip~ never recovers. I've read something about compiling with `PD_BIGORSMALL` but when compiling on iOS it complains. Is there a way of avoiding sending NaN and Inf to objects that shouldn't receive them? The solutions I've found don't seem to work and I'm not sure if that's related to not turning on certain compiler flags or not.

**Comment by danomatika** [comment]
This *might* be something resolved in the new Pd release. The libpd master now uses those sources if you want to test.

**Comment by danomatika** [comment]
I think this is indeed something more in the upstream pd sources. Pinging @millerpuckette

**Comment by danomatika** [comment]
Is this still an issue?

**Comment by cerupcat** [comment]
I think we can mark it closed; I haven't run into it again (though I might have worked around it - I don't recall).
