### ISSUE TITLE
Makefile install in sandbox

### ISSUE THREAD

**Issue by wimmuskee** [libpd/libpd#159]
I'm trying to package libpd for Gentoo, and when compiling and installing a package, Gentoo uses a sandbox to do the work before moving the result to the actual filesystem.

To make this work I had to do two things in the Makefile:
- prefix the prefix declaration with $(DESTDIR), to be able to provide Gentoo's sandbox root
- make a $(prefix)/lib dir, in the sandbox it does not exist, and otherwise the library file is copied to /lib, not in /lib

If the Makefile is currently working as intended, close this issue, otherwise I can provide a merge request.

**Comment by wimmuskee** [comment]
never mind on the $(DESTDIR), simply providing the prefix=$(DESTDIR)/usr when calling to install works

**Comment by danomatika** [comment]
The install target is not super fancy right now, for sure. We're thinking about moving the project to Autotools which provides most of this functionality in a more standard way.
