### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by squarefrog** [libpd/libpd#163]
Would you be interested in [Carthage](https://github.com/Carthage/Carthage) support for Xcode projects?

I have added support in [my `libpd` fork](https://github.com/squarefrog/libpd/tree/carthage) so I can use it, but wondered if it was of any use to the `libpd` community.

The main disadvantage to adding support would mean the minimum deployment targets raise to iOS 8, although 92% of iOS users are using version [9 or above](https://developer.apple.com/support/app-store/).

If you'd rather not merge in support, then no problem, people can still use Carthage by adding my fork to their `Cartfile`:

    github "squarefrog/libpd" "carthage"

I don't believe this would negatively affect users who are adding the project 'the hard way'.

**Comment by danomatika** [comment]
Two points I see:

1. As with Cocoapods before, the main concern is keeping things up to date. None of the main devs use CP but thus we're maintaining a pod spec & the same would go with a Cartfile, and the same with yet another package manager. Sure it's *easy* but still another thing for us to manage.

2. I still have a project which runs on iOS 6 devices which I recently got on the App Store in Nov. I believe I ended up having to raise the deployment target but it still works... Raising at this point may make sense but I wouldn't want to do it without double checking some things.

**Comment by squarefrog** [comment]
Valid points for sure.

However, from a project manager point of view, Carthage requires less maintenance. Essentially, all the library needs to do is be able to build as a framework. Only end users need to worry about `Cartfile`. This is in contrast to CocoaPods where you have to update the `.podspec`, then commit, push, and finally push to trunk. The only requirement on your part would be to tag releases with `git tag`.

I completely understand reluctance to update deployment targets. If that's what you'd want to do, I'm happy to keep my fork separate, as I can migrate to ARC, add better Swift support etc without affecting the main repo. The only other option I've seen in other projects would be to keep a legacy branch around for users with older deployment requirements.

Feel free to close this issue if you'd rather keep things separate 👍

**Comment by danomatika** [comment]
>The only requirement on your part would be to tag releases with git tag.

We do that already :)

>The only other option I've seen in other projects would be to keep a legacy branch around for users with older deployment requirements.

This might be a good approach. I've been thinking about updating to ARC actually.

**Comment by squarefrog** [comment]
I figured you would for CocoaPods.

I haven't manually reference counted in years, which I'm thankful for!

Scanning through the implementation files, it seems all you'd need to do to improve Swift compatibility would be to use [audited regions](https://developer.apple.com/swift/blog/?id=25), then add in `_Nullable` for any parameter where `nil` is acceptable. This would raise the minimum Xcode support to 7 or higher though. I cant find any clear guidance for the minimum Xcode required to submit to the App Store, but I'd be very surprised if it was less than 7.

**Comment by squarefrog** [comment]
On second thoughts, I'm not actually sure that adding support for Frameworks would increase the deployment target for the static libraries.

The Framework target has its own Deployment Target, so it may not affect the static libraries. I don't have any older versions of Xcode installed to check that however.

**Comment by danomatika** [comment]
We should revisit this at some point as the Obj-C wrapper could use an update. I'm planning on moving the deployment target forward.

**Comment by squarefrog** [comment]
I have done this on [my fork](https://github.com/squarefrog/libpd/commits/carthage). It was pretty painless. 

If you're updating the Obj-C wrapper, then adding [nullability identifiers](https://developer.apple.com/swift/blog/?id=25) would help Swift users too 😉 

Let me know if you need a hand.

**Comment by danomatika** [comment]
If you want to provide a PR, that would be great. I need to get out a final stable release of my app for old devices and then update the min deployment.

**Comment by squarefrog** [comment]
Done.

**Comment by danomatika** [comment]
Sure. We can take nullability. I'd like to have the current Obj-C sources work nicely with Swift at this point.

Also, if you want to provide a swift sample project (and test), that would be helpful. It could simply be a port of `samples/objc/ios/pdtest` to swift. I'd place it in `samples/swift/ios/pdtest` or some such. It helps to have these simple tests when checking builds. Larger, more elaborate samples go in the separate *pd-for-ios* and *pd-for-android repos*.

**Comment by danomatika** [comment]
How does this look with libpd now? If you think it's easy to integrate, I'd include it in the release we are working on.
