### ISSUE TITLE
Crash on Windows 10 64-bit

### ISSUE THREAD

**Issue by ssfrr** [libpd/libpd#164]
I'm using LibPD inside Unity. I've built a 64-bit DLL using mingw64 as per the README instructions.

I get a crash when the DSP tick starts running, specifically when it runs the `block_prolog` function, which is the first process function in the `pd_this->dsp_dspchain` list.

```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x0000000028d6f122 in block_prolog (w=0xd2e6c440)
    at pure-data/src/d_ugen.c:237
237         int phase = x->x_phase;
```

The backtrace is:
```
#0  0x0000000028d6f122 in block_prolog (w=0xd2e6c440)
    at pure-data/src/d_ugen.c:237
#1  0x0000000028d6f71e in dsp_tick () at pure-data/src/d_ugen.c:341
#2  0x0000000028dc817f in sched_tick () at pure-data/src/m_sched.c:431
#3  0x0000000028e07815 in libpd_process_float (ticks=16, inBuffer=0x249c7220,
    outBuffer=0x249c6020) at libpd_wrapper/z_libpd.c:190
#4  0x000000009754b2c9 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

(I'm pretty sure the corrupt stack complaint is just because that's where it's being called from the C# code that GDB doesn't understand).

The problem is that when it's built `long` is only 4 bytes long, but the pointers are 8. I confirmed this in GDB:

```
(gdb) p sizeof(w)
$8 = 8
(gdb) p sizeof(w[1])
$9 = 4
(gdb) p sizeof(t_int *)
$10 = 8
(gdb) p sizeof(t_int)
$11 = 4
(gdb) p sizeof(long)
$12 = 4
(gdb) p sizeof(long long)
$13 = 8
```

`t_int` is `typedef`ed to `long`, which apparently is 32-bit.

[this stackoverflow post](http://stackoverflow.com/questions/7607502/sizeoflong-in-64-bit-c) confirms that `long` is 32-bits on mingw64.

So in this environment I think the right solution is to define `PD_LONGINTTYPE` to `long long`. I modified the Makefile to add `-DPD_LONGINTTYPE="long long"` to `PLATFORM_CFLAGS` for `Windows_NT`, and it seems to fix things, but that will only work on 64-bit windows.  I'm not sure what the best way to only include the definition for 64-bit windows.

**Comment by danomatika** [comment]
Thanks for looking into this.

I'd think a quick solution would be to pass the long int type override to the main Makefile inside the 64 bit build bat file ala:

    make csharplib -DPD_LONGINTTYPE="long long"

The better solution, as you suggest, would be to detect the architecture and choose based on that in the main Makefile.

**Comment by danomatika** [comment]
Were you able to get it to work?

**Comment by ssfrr** [comment]
I don't remember which of the above solutions I ended up using (modifying the Makefile vs. using the command-line define override) but I think either way would work.

**Comment by danomatika** [comment]
Ok cool. I went ahead and added it to 64bit bat file for now as added arch detection to the Makefile might be overly complicated and best done later when we move to a different build system (autotools).
