### ISSUE TITLE
Changing Pd's Block Size

### ISSUE THREAD

**Issue by ariadnasc** [libpd/libpd#166]
I am currently working with LibPD on Unity and I need to change the Pd's Block Size (right now is, by default, 64). Is there any way to change it? I am using libpd4unity (https://github.com/patricksebastien/libpd4unity) and I don't think there is any way to set, it only exists the function LibPD.BlockSize.

**Comment by residuum** [comment]
You cannot set it from the wrapper code, but only from Pd itself with `[block~]`.

**Comment by ariadnasc** [comment]
Thank you for the answer.
Is there anywhere I can look how this object works?

**Comment by residuum** [comment]
Open Pd, add a `[block~]` object, right click -> help. In Pd, the blocksize can be set from a command line flag, but AFAIK, not in libpd.

**Comment by danomatika** [comment]
Also, if you're experiencing audio dropouts, look into increasing the number of ticks when initing libpd.

**Comment by ariadnasc** [comment]
Yes, my main problem is that when LibPD is opened in Unity, after around 30 seconds my audio starts clicking. It has to be a problem of buffering but I still can't figure out a solution

**Comment by danomatika** [comment]
Changing the block size is not the solution. It sounds like you need to check for general performance issues like turning off DSP you don't need by moving it into subpatches and using [switch~], removing unneeded GUI objects in the chain, etc.

**Comment by residuum** [comment]
Maybe you are computing too often with libpd, have a look at buffering in the NAudio example:

https://github.com/libpd/libpd/blob/master/samples/csharp/naudio/PdProvider.cs

**Comment by danomatika** [comment]
Any updates on this?

**Comment by danomatika** [comment]
As a followup, if the buffer duration is not a multiple of Pd's block size, you can use FIFO ring buffers to make sure you have enough blocks to fill the buffer each render call. This is what we're now using in #228 for a similar problem on iOS.
