### ISSUE TITLE
[feature request] setting internal timer position

### ISSUE THREAD

**Issue by jcelerier** [libpd/libpd#168]
The docs hint that Pd manages time by incrementing some internal value by block_size at every run.

Would it be possible to give a hook through libpd to set the "internal time" at a given arbitrary value (in samples I would guess) ? 
The use case is for instance to allow synchronizing instances with an external metronome.

If for instance a pd patch runs during callback 1, 2, 3, not during callback 4, and runs again during callback 5 I'd like to make up for the "missed" time.

**Comment by danomatika** [comment]
ping @nettoyeurny

**Comment by nettoyeurny** [comment]
I don't understand the use case. Why wouldn't the Pd patch run during callback 4?

**Comment by jcelerier** [comment]
hmm, maybe this wasn't the best of examples. 
It's more clear with two patches: 
let's say that I have two patches generating midi notes: 
`[metro 60] -> [random 80] -> [s $0-out]` and `[metro 80] -> [random 80] -> [s $0-out]` 
Now, I would to get the first patch to execute at t=10 seconds of a song, the second patch at t=20 seconds, and have their internal metronome synced. I don't want to run the patchs at each tick: it would waste resource for nothing.

Maybe it needs some explanation of the project I'm working on. [i-score](http://i-score.org/) is an OSC sequencer when parts of the score can start & stop at arbitrary time. So currently to have "scripting power" I'm using javascript: someone can write than a JS script will run in a box for a given duration at a given point in the timeline (c.f. screenshot of the page); I'm trying to do the same with libpd.

**Comment by mgsx-dev** [comment]
maybe you could use an external clock to sync your generators ? : 
`[r clock] -> [% 80] -> [change] -> [random 80]...`
`[r clock] -> [% 60] -> [change] -> [random 80]...`

**Comment by jcelerier** [comment]
certainly, but it would be one more thing to remember for the people using the software :p ideally I'd like not to break existing pd patches.

**Comment by danomatika** [comment]
As mgsx-dev points out, the common way to do this is to send/recieve a clock/pos message without needing to dig into Pd's internals.

**Comment by danomatika** [comment]
Closing do to lack of activity.
