### ISSUE TITLE
Difficulty adding externals (C++)

### ISSUE THREAD

**Issue by helenacelle** [libpd/libpd#170]
I'm following the steps outlined at:
https://github.com/danomatika/ofxPd#adding-pure-data-external-libraries-to-ofxpd

But am continually ending up with undefined reference errors despite following as closely as possible. I am compiling in C++ on RPI with a makefile, using a simple test patch which works without externals. As soon as I attempt to include externals with the above method the program is unable to compile.

I've been trying to compile with Freeverb, but am intending to use Cyclone externals such as Midiparse, Thresh and Seq.  Here is the simple test program I use to check my RPI / soundcard setup, all I'm doing differently when attempting to include Freeverb is adding it on the end of the patch before the dac~ output.

https://github.com/helenacelle/pd_tester

Any help would be much appreciated, as I'm unsure as to where I'm going wrong. Only things I can think of are relating to my makefile, but I'm unsure as the information I'm following doesn't mention this as a requirement. 

Kind regards

**Comment by danomatika** [comment]
What's the compiler error? Please copy & paste.

**Comment by helenacelle** [comment]
Thanks for the response, have uploaded the program to my git as per my workflow: https://github.com/helenacelle/pd_ext

Compiler error is 
"src/main.o: In function 'initAudio()':
main.cpp(.text+0x5c): undefined reference to 'freeverb_tilde_setup'"

**Comment by danomatika** [comment]
You need to define PD in your makefile, judging from the #ifdef around the freeverb_tilde_setup function definition: https://github.com/helenacelle/pd_ext/blob/master/src/externals/freeverb%7E.c#L197

**Comment by helenacelle** [comment]
I'm not totally sure how to do that, any pointers? Sorry

**Comment by danomatika** [comment]
Add something like the following to your makefile (Line 30 would be a good place):

    CFLAGS += -DPD

**Comment by danomatika** [comment]
Also, your Makefile does not look finished as it doesn't seem to include building the freeverb sources. You probably want to add freeverb~.c to your SRC_FILES variable.

**Comment by helenacelle** [comment]
Oh, thanks! I really don't know enough to figure out where I'm going wrong.

I'm just getting a "no rule to make target "src/freeverb~.c" needed" error now, will this just be another issue with my makefile?

**Comment by danomatika** [comment]
Yes. It's a common problem when writing makefiles and there should be lots of info around Google, stackoverflow, etc. It basically means the compiler doesn't know what to do with the .c file, since the makefile only knows how to build .cpp files as specified on line 35: https://github.com/helenacelle/pd_ext/blob/master/Makefile#L35

You'll probably need to build the c externals first as a separate build target, then link with the main program in another step.

**Comment by helenacelle** [comment]
Oh shit I really have no idea, been Googling around but finding understanding Makefiles completely impenetrable.

**Comment by danomatika** [comment]
Best to start with a tutorial from scratch. That's what I did, but I don't remember which one. Hard to apply individual solutions when you're still fuzzy on how the whole thing works.

**Comment by helenacelle** [comment]
Cool, so I should be able to solve this problem entirely by getting the Makefile correct? Thanks for the help!

**Comment by danomatika** [comment]
Yup. Except for the missing define, the project should build ok once the Makefile it set up correctly.

**Comment by helenacelle** [comment]
I think I might have fixed that issue but ran into another problem, to do with the conditional #IFDEF statement at the start of freeverb~.c that relates to (I think) whether PD or Max is being used. The compiler is looking for the Max related includes, would this again relate to the Makefile? 

"#ifdef PD
#include "m_pd.h"
#else	// Max/MSP
#include "ext.h"
#include "z_dsp.h"
#define t_floatarg double
#endif"

Thinking of just giving up on this and using a reverb pedal, will try with other externals.

**Comment by danomatika** [comment]
Yup. When building for Pd, you need to set the PD define via -DPD to the compiler.

**Comment by danomatika** [comment]
Also, note that libpd can load precompiled externals like regular desktop Pd if you add a search path to where the externals are located. Looks like you are on an rpi, so you can add a path to `/usr/local/lib/pd/extra` and use [declare] in your patch to load freeverb.

**Comment by helenacelle** [comment]
I didn't know you could do that! I had a look at the [declare] help file, would I have it set up like [declare -lib /usr/local/lib/pd/extra], then just put the required externals in the extra folder?

**Comment by danomatika** [comment]
If you set the path, you should only need [declare -lib freeverb].

**Comment by helenacelle** [comment]
Oh I'm not sure where you'd set the path, I thought you maybe did it inside of the declare object?

**Comment by danomatika** [comment]
https://github.com/libpd/libpd/blob/master/cpp/PdBase.hpp#L97

**Comment by helenacelle** [comment]
oh thanks!

**Comment by danomatika** [comment]
For a quick reference, this is good for Makefiles: https://www.cs.swarthmore.edu/~newhall/unixhelp/howto_makefiles.html

**Comment by danomatika** [comment]
Closing for now. Open a new issue if you run into bugs in libpd itself.
