### ISSUE TITLE
Zip, the only method of file compression?

### ISSUE THREAD

**Issue by Arifd** [libpd/libpd#172]
It is not uncommon for pd projects to contain WAV/AIFF files (obviously).

Zip does a poor job compressing these files.

Would it be possible to create an IoUtils method that extracts a different type of resource, similar to IoUtils.extractZipResource, but say for Rar files instead?

If not, is there something I can do on my end to shrink the size of the audio files?

Thanks.

**Comment by danomatika** [comment]
I'd that is outside of the scope of libpd and best done in your own project or as some sort of library add-on/wrapper for libpd.

**Comment by Arifd** [comment]
Okay. Then I think the best solution is probably to get the [readanysf~] external in my patch and work directly with FLAC files instead.

Thanks.

**Comment by Arifd** [comment]
This is beyond me. I have been at this all day. I have managed to get [readanysf~] to compile and run on my computer - but it required compiling two other libraries also, and it appears to only accept absolute paths to files. So there certainly are some barriers ahead of me.

Another option that I can think of is to have Android (which can natively handle compressed audio formats) somehow populate tables in pd using libpd's writeArray() method. But I wouldn't know where to begin with this either.

**Comment by danomatika** [comment]
There was a request for a way to fill array buffers directly for this reason ie. load a sound via built-in Android/iOS methods and then pump the samples into libpd. We don't have that yet, so your only way to access this so far is via setArray which involves making a copy of the buffer.

**Comment by Arifd** [comment]
Okay, thanks Dan. If the feature you describe is something in the works for libpd then I'm totally satisfied with that as a solution, and you can go ahead and close this issue.
