### ISSUE TITLE
Some queries regarding MIDI functionality 

### ISSUE THREAD

**Issue by helenacelle** [libpd/libpd#174]
Hi, I'm wondering if anyone could possibly help me clear up some issues I'm having regarding MIDI functionality. 

I've been running a wavetable sequencer program on my RPI3, and decided to add MIDI output functionality to interface with my MS20 mini over USB. The PD patch (without LibPD) utilises a midi-dialog prompt which, when on my Macbook, automatically connects the patch with my MS20 upon startup, and plays the data connected to a [noteout] object. Everything works fine there.

When I run it on the RPI3 through LibPD, everything else runs perfectly, but there's no response from my MS20. The MS20 is being detected as an ALSA midi output, and I can play MIDI files outside of PD on the RPI without a hitch, which are automatically recognised by the synth. It's just when I run the patch through PD, it ceases to automatically register the MS20 as an output.

Is this an issue with LibPD? Does MIDI functionality differ when I run my patch through LibPD, as opposed to just running it in PD? Does it have anything to do with ALSA, and is there any way I can use PD command line options listed here (https://puredata.info/docs/faq/commandline) with LibPD? I've been wondering if using some of those would help make the connection.

Any ideas? Is it going to be easier in the end to just send the values from PD to C++, then send them to the MS20 over serial? Or am I missing something obvious out, and this functionality should work like it does on my Mac?

Kind regards

EDIT: My code is here if it helps. Keeping in mind it works perfectly when I run the patch in PD on Mac, and retains all functionality except for MIDI output on RPI. The [noteout] object being utilised is hidden inside [pd Channel_1].
https://github.com/helenacelle/playback_system

Might be helpful to mention that the midi-dialog stuff came from here, and that it works perfectly on Mac, but seemingly fails to connect on RPI despite generating the same midi-dialog message on both platforms when the MS20 is connected. https://www.reddit.com/r/puredata/comments/4qmhfh/need_pd_to_have_midi_controller_selected_by/

**Comment by mgsx-dev** [comment]
It would be nice to keep your first issue description and explain briefly how did you figured it out ... some people could face same issue ...

**Comment by helenacelle** [comment]
Solution had nothing to do with LibPD. I just wrote my own serial classes for writing and read MIDI from hardware cause it was easier than doing it with LibPD.

**Comment by danomatika** [comment]
You're issue probably comes from the fact that libpd does not come with the default audio & MIDI backends that vanilla Pd has. These were left out on purpose as it makes the library more flexible for embedding at the cost of requiring a bit of plumbing if your app does not have either already. This explains why MIDI did not work ... it simply cannot unless you:

* add a MIDI I/O library to your project (ALSA, CoreAudio, RtMidi, etc)
* implement the libpd MIDI message callbacks and forward MIDI from PD to the MIDI I/O library
* forward messages form the MIDI I/O library to libpd

I can whip up a C++ example using RtMidi at some point.

**Comment by helenacelle** [comment]
Hey! It's cool, I wrote my own C++ classes outside of libpd to implement MIDI over serial, but I'd certainly be interested in seeing the RtMidi example, if only for the benefit of other people.
