### ISSUE TITLE
Android build not setting -DLIBPD_EXTRA

### ISSUE THREAD

**Issue by danomatika** [libpd/libpd#175]
The Android.mk makefile seems to build the included externals (bob~, bonk~, etc) but does not set the LIBPD_EXTRA define which is used in libpd_init to call the external setup functions. This means the external sources are built, but the objects are not loaded and cannot be instantiated.

I believe the simple fix is to add the define -DLIBPD_EXTRA to line 38 in Android.mk, but I would need one of the Android dev to check if this works and if it works in Android Studio.

**Comment by danomatika** [comment]
Pinging @tkirshboim and @chr15m

**Comment by tkirshboim** [comment]
@danomatika I could test this if you make your suggested change, but how could I reproduce the issue? How did you find this out?
As far as I remember (but I should double check) `bonk`~ and `bob~` work when using the [PdTest example app](https://github.com/libpd/pd-for-android/tree/master/PdTest).

pinging @joebowbeer

**Comment by porres** [comment]
Hi, this came up with me sending an email to the Pure Data list.

I'm testing the usage of externals with libpd, sarting with the ones that come with Pd, like [bob~].

I'm using libpd for android. I'm on a MacOS Sierra, and using Android Studio's emulator. I made it through Rafael's tutorial https://www.youtube.com/watch?v=cinOFA1pT1k&list=PLn3ODBv0ka5hS5areRFSTi2aydPMiUq3B - I got a simple patch that turns on by a switch. The emulator uses a Nexus 5 API 24, x86 architecture. So now I just have another simple patch with [noise~] going through [bob~] that I wanted to try and make it happen. 

So, [bob~] is an extra, and you don't get it by default in libpd, so it seems. I checked around, and was able to compile pd's extra as .so files. In my projects PdCore I got a libs folder with all these compiled externals for armeabi / armeabi-v7a / x86! The binary for bob seems to be "libbob_tilde.so". But having this is not enough for loading it and playing it... what else am I missing?

I also did try using PdBase.addToSearchPath in my code in MainActivity.java, I got the idea that would do it, but it didn't, here's how I tried it.

private void initPD() throws IOException{
    int sampleRate = AudioParameters.suggestSampleRate();
    PdAudio.initAudio(sampleRate, 0, 2, 8, true);

    PdBase.addToSearchPath("/Users/porres/Desktop/LearningLibPd/HelloPd/PdCore/libs/x86");

    dispatcher = new PdUiDispatcher();
    PdBase.setReceiver(dispatcher);
}

**Comment by porres** [comment]
this next comment is my reply to Dan on the Pd-list

---------

2017-06-23 10:25 GMT-03:00 Dan Wilcox <danomatika@gmail.com>:

I believe the Android build uses Android.mk and not the main Makefile.

Yeah, that seems to be the thing that happens. In my project folder I have the PdCore/jni/libpd/Android.mk file with build instructions.

Looking inside, I see it’s building the included externals but I think it’s missing the LIBPD_EXTRA define which is used to tell libpd to automatically call the setup function for the externals ie. bob~, bonk~, choice, etc.

I don't see LIBPD_EXTRA either

Is Android Studio building libpd via the Android.mk file? I haven’t done any Android development, so I’m not sure. If it is, you can try adding -DLIBPD_EXTRA to the end of line 38 in Android.mk and rebuilding.

This leaves me with:

"PD_CFLAGS := -DPD -DHAVE_UNISTD_H -DHAVE_LIBDL -DUSEAPI_DUMMY -w DLIBPD_EXTRA "


To build the "extra" binaries, I go to the PdCore folder on the terminal and do "~/Library/Android/sdk/ndk-bundle/ndk-build". So, when I try to build it now, I get the error: 
"clang: error: no such file or directory: 'DLIBPD_EXTRA'"

So then I tried: 
"PD_CFLAGS := -DPD -DHAVE_UNISTD_H -DHAVE_LIBDL -DUSEAPI_DUMMY -w -DLIBPD_EXTRA "

Now, when building, it does something, it seems to compile the basic internals, then I get an error. Oh, and now I see I don't have anymore the compiled .so binaries I did have before for the extra objects, so they got deleted/cleaned up somehow in this process.

This is the error I get, btw: 

[armeabi] SharedLibrary  : libpd.so

jni/libpd/libpd_wrapper/z_libpd.c:92: error: undefined reference to 'bob_tilde_setup'

jni/libpd/libpd_wrapper/z_libpd.c:93: error: undefined reference to 'bonk_tilde_setup'

jni/libpd/libpd_wrapper/z_libpd.c:94: error: undefined reference to 'choice_setup'

jni/libpd/libpd_wrapper/z_libpd.c:95: error: undefined reference to 'fiddle_tilde_setup'

jni/libpd/libpd_wrapper/z_libpd.c:96: error: undefined reference to 'loop_tilde_setup'

jni/libpd/libpd_wrapper/z_libpd.c:97: error: undefined reference to 'lrshift_tilde_setup'

jni/libpd/libpd_wrapper/z_libpd.c:98: error: undefined reference to 'pique_setup'

jni/libpd/libpd_wrapper/z_libpd.c:99: error: undefined reference to 'sigmund_tilde_setup'

jni/libpd/libpd_wrapper/z_libpd.c:100: error: undefined reference to 'stdout_setup'

clang++: error: linker command failed with exit code 1 (use -v to see invocation)

make: *** [obj/local/armeabi/libpd.so] Error 1

**Comment by joebowbeer** [comment]
As I mentioned in my comment below Rafael's tutorial, the recommended build process for pd-for-android apps has changed.

I advise starting with a project that uses pd-for-android as a jCenter dependency. This will eliminate the many errors resulting from NDK setup issues.

Tal's PdTest project is a good starting place. Its patch instantiates bob~ and boink~

https://github.com/tkirshboim/pd-for-android-test.git

I just cloned this project and installed the debug apk, and it appears to work.

**Comment by danomatika** [comment]
Closing as this is a build process issue which, I believe, was already resolved on pd-list.

**Comment by porres** [comment]
yep, solved, thanks :)
