### ISSUE TITLE
char* vs t_symbol*

### ISSUE THREAD

**Issue by pierreguillot** [libpd/libpd#176]
What's the point of using __char*__ instead of __t_symbol*__? 
I know that the use a table of symbols to compare messages is no longer as optimized compared to using strings of characters but using strings in a symbol-table context is the worst of both worlds because we call _gensym_ even when we don't need.
Perhaps (surely) it's too late to change it but I think that explaining this choice in documentation could be good idea.

**Comment by danomatika** [comment]
The main reason is to keep a consistent API without using too many Pd-isms. That was the original idea, at least. I would ask MSP if there are any real performance issues.

**Comment by danomatika** [comment]
>Perhaps (surely) it's too late to change it but I think that explaining this choice in documentation could be good idea.

What kind of explanation? Note that the documentation is a wiki page after all...

**Comment by danomatika** [comment]
Closing for now. We could revisit at a later date.
