### ISSUE TITLE
Issue with latest update

### ISSUE THREAD

**Issue by jcelerier** [libpd/libpd#180]
I'm seeing something quite weird...

This works: 
![ok](https://user-images.githubusercontent.com/2772730/28502977-009c2244-6ffe-11e7-80db-cae6a95d0db1.png)

This does not: (I only get zeroes in my array after `libpd_process_float`).
![pd](https://user-images.githubusercontent.com/2772730/28502973-f082b38c-6ffd-11e7-9414-35905a96a2e4.png)

**Comment by mgsx-dev** [comment]
Hi, I had the same issue few times ago, I just recompile it with LOCALE=true and it fixed the issue.

Without this option, float parsing expect a comma instead of a dot, that's why I had no sounds at all like you.

@danomatika Why this compiling option is not the default ? it should be at least recommended in the read me file, this issue is hard to figure out.

**Comment by danomatika** [comment]
From the [readme](https://github.com/libpd/libpd):

>* Setting the number locale explictly may be necessary if you run into certain numbers not being read correctly when opening patches. See https://github.com/libpd/libpd/issues/130 for more info.

**Comment by jcelerier** [comment]
thanks! I agree that it should be the default (else it's just not compatible with most of the patches that one would exchange on the internet if you happen to live in a non-english-locale country)

**Comment by danomatika** [comment]
The discussion ins in #130. Forcing the locale is not something we want to do in a library that may be used within other code that requires something different, that's why it's left up to the user as a make option.

**Comment by mgsx-dev** [comment]
@danomatika Sorry I didn't noticed it in the read me. I just read #130 again and keep wondering why it is a problem to have this option enabled by default...

**Comment by mgsx-dev** [comment]
OK, you answered before my question :-)

**Comment by danomatika** [comment]
Ok, y'all changed my mind. I decided to change the default to set LC_NUMERIC. There is info in the readme about this and the compiler define is now "LIBPD_NO_LOCALE" as it is now used to negate this default.

I figured that the number of people running into tis issue will be a lot more than those who are setting their own numeric locales.

**Comment by residuum** [comment]
I will change the README for building the C# library.
