### ISSUE TITLE
usage of pdinstance_free ?

### ISSUE THREAD

**Issue by jcelerier** [libpd/libpd#181]
If at the end of pdtest_multi I add 

```C
  pdinstance_free(pd1);
  pdinstance_free(pd2);
```

I get a double-linked list / corruption error. 
How to prevent this (and not leak memory) ? 

Running with AddressSanitizer tells : 

    ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x613000088620 in thread T0
        #0 0x7fbe1e1f94c8 in free _asan_rtl_:0
        #1 0x55bb8de4b3d0 in pdinstance_free ??:0:0

Edit: recompiled in debug mode: 
```
#0  0x00007f72715a98c0 in raise () from /usr/lib/libc.so.6
#1  0x00007f72715aaf72 in abort () from /usr/lib/libc.so.6
#2  0x00007f72715e8be2 in __libc_message () from /usr/lib/libc.so.6
#3  0x00007f72715ef2ec in malloc_printerr () from /usr/lib/libc.so.6
#4  0x00007f72715f06d1 in _int_free () from /usr/lib/libc.so.6
#5  0x000055555555d50f in freebytes (fatso=0x5555558850b0, nbytes=24) at pure-data/src/m_memory.c:79
#6  0x0000555555559f08 in pdinstance_free (x=0x555555884f50) at pure-data/src/m_class.c:221
#7  0x0000555555559419 in main ()
```

**Comment by danomatika** [comment]
This is a question for @millerpuckette 

Also, check out #178

**Comment by millerpuckette** [comment]
This should be fixed in latest Pd (553d3ffbeb13e4131dcca01ef0f0b9abb5d01467).

**Comment by danomatika** [comment]
Confirmed.

**Comment by jcelerier** [comment]
thanks! :)
