### ISSUE TITLE
Xcode 9 build failure - 'system' is unavailable: not available on iOS

### ISSUE THREAD

**Issue by sinewave440hz** [libpd/libpd#187]
A project (with a switch turning a sine wave on and off) that builds and runs fine on Xcode 8 doesn't build on Xcode 9. Apparently 'system' has been deprecated for some time and is now unavailable on iOS 11. 

The offending call is:

`    system(cmdbuf);
`
It also seems that we have some suggestions on how to fix this: 
```
__swift_unavailable_on("Use posix_spawn APIs or NSTask instead.", "Process spawning is unavailable")
__API_AVAILABLE(macos(10.0)) __IOS_PROHIBITED
__WATCHOS_PROHIBITED __TVOS_PROHIBITED
int	 system(const char *) __DARWIN_ALIAS_C(system);
```

**Comment by danomatika** [comment]
iOS 11 was released about 6 hours ago, so I'm not sure when we will get to this. You are way ahead!

It's most likely a tweak needed to the Xcode project. Note: the current master branch is not really production ready, so try with the latest release tag.

**Comment by danomatika** [comment]
I'm not seeing this with the Obj-C example in `samples/objc/ios/pdtest` and I'm guess it's a Swift interpreter issue with the Posix API, which would be surprising to see deprecated. In any case, this is a non-issue as system is only used in s_file.c in the Pd sources which libpd does not use.

Which version of libpd are you using? The current master no longer builds s_file.c.

**Comment by sinewave440hz** [comment]
I just used the pd-for-ios repo, so I will try the latest libpd instead with that.

**Comment by sinewave440hz** [comment]
Hmm. Latest libpd and running samples/objc/ios/pdtest gives me a bunch of "Use of undeclared identifier 'STUFF' in Xcode 9.

An example:   `STUFF->st_soundin = NULL;` in z_libpd.c.

**Comment by sinewave440hz** [comment]
Cool. Everything builds ok now, so this can be closed I guess. Libpd running on iPhone X. Nice :)

**Comment by sinewave440hz** [comment]
Closing now, but should I raise an issue in pd-for-ios to update libpd?

**Comment by danomatika** [comment]
Probably. Those example projects are getting a bit old ut should still work when the next libpd version is released.

**Comment by sinewave440hz** [comment]
Well, all except the link and dispatcher examples build and run fine in latest Xcode 9 with latest libpd, so it's looking promising.

**Comment by eplans** [comment]
I just found this thread very helpful, so thank you.

I just cloned the pd-for-ios repo, and updated the submodules, and still got the "system unavailable" error.  As a complete newbie, and not knowing what I'm doing, I went into s_file.c and commented out the line that calls "system".  My project now builds without the error!

I am using Xcode 9.1 (B55), and following the esteemed "Cheetomoskeeto" tutorials on YouTube.

**Comment by danomatika** [comment]
The pd-for-ios repo has the libpd repo as a submodule. Currently, the libpd version is set to the latest test release version tag (0.10.0) which has the system issue in Xcode 9. To update to the current master, you basically go into the libpd folder with git and checkout the master:

    cd libpd
    git pull
    git checkout master

**Comment by eplans** [comment]
Ahh!  That's brilliant!  Thank you so much! :)
(Your answer clarified the aspects of this thread that I didn't previously understand!)

**Comment by danomatika** [comment]
Sure.

Submodules in git are a subject that don't make much sense at first, but it's basically just a reference to another repo. When you check out the main repo and update the submodules, they then checkout the submodule to the commit it currently references. But inside the submodule folder it self, it's just another git repo so you can checkout different versions as well. :)
