### ISSUE TITLE
libpd/pd-for-ios » 'system' is unavailable: ... on iOS error - with the recent Xcode 9

### ISSUE THREAD

**Issue by Dassine** [libpd/libpd#191]
Hi !  

s_file.c creates the following error with system(cmdbuf); 

'system' is unavailable: not available on iOS

At  line #279  : system(cmdbuf); 

static void sys_putpreference(const char key, const char value)
{
char cmdbuf[MAXPDSTRING];
snprintf(cmdbuf, MAXPDSTRING,
"defaults write org.puredata.pd %s \"%s\" 2> /dev/null\n", key, value);
**system(cmdbuf);**
}

**Comment by Dassine** [comment]
The solution is : 

[
#include <spawn.h>

extern char **environ;

void run_cmd(char *cmd)
{
    pid_t pid;
    char *argv[] = {"sh", "-c", cmd, NULL};
    int status;

    status = posix_spawn(&pid, "/bin/sh", NULL, NULL, argv, environ);
    if (status == 0) {
        if (waitpid(pid, &status, 0) == -1) {
            perror("waitpid");
        }
    }
}
]( https://www.bountysource.com/issues/49829690-system-is-unavailable-on-ios-error-with-the-recent-xcode-9?show_profile_modal=1)

**Comment by danomatika** [comment]
libpd does not need to build s_file.c. See #187

**Comment by Dassine** [comment]
I added libpd pod in oct 2015. this error showed up since the last XCode update.

**Comment by Dassine** [comment]
I also have another copy with a copy of libpd clone added in my project.

**Comment by danomatika** [comment]
As with #192, this is more or less fixed in the current master.

**Comment by cerupcat** [comment]
@danomatika I'm getting this same error using the latest cocoapod. Is that up to date with master or does it not apply to cocoapod usage?

**Comment by danomatika** [comment]
There is no current release yet, so the podfile still refers to the last release which does not have the fix.

(I'm starting to hate dealing with cocoapods.)

**Comment by cerupcat** [comment]
@danomatika gotcha. I can point the pod at the latest master commit for now and see if that works.
