### ISSUE TITLE
xcode project with thread/instance support

### ISSUE THREAD

**Issue by pierreguillot** [libpd/libpd#194]
The current Xcode project doesn't have the appropriate flags for the multi-threading and multi-instances support (**-DPDINSTANCE** and **-DPDTHREADS** in the C and C++ flags). Perhaps another target is necessary (it seems that the only way to create a static library on MacOS is to use the Xcode project #7). I can create a PR if it seems a good solution.

**Comment by danomatika** [comment]
The xcode project is meant for "regular" non-instance usage, at least for ios.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by pierreguillot** [comment]
What is the reason? An "instance" target for MacOS is compatible with the two actual "regular"  targets...

**Comment by danomatika** [comment]
The reason is that this wasn't yet tested and things were still changing before. We can look into changing it now, but I'd also argue that most users do not need multi instance support by default.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by pierreguillot** [comment]
I understand. Nevertheless, if you make the choice to improve the support for multi instance, feel free to contact me. And you can close the issue, I'll use command line to overwrite the default settings.

**Comment by danomatika** [comment]
My thinking is that it should not be the default. However, it could be a second build target: libpd-maces and libpd-macos-multi, for instance. I will work on libpd this afternoon after I finish up some other things.

**Comment by danomatika** [comment]
Ok, I've added prelim multiple instance support to libpd via function wrappers and multi builds, both in the makefile and the Xcode project. See the latest commits in the master branch.

**Comment by pierreguillot** [comment]
Great thanks ! I've fix a small problem #197. Perhaps it's not essential but what about setting the default architecture to **Universal 32/64bits intel**. It's complicated to change the arch to universal with command line but it easy to change it to something  like x64 or i386. Perhaps I should create another issue? I'll check my multi-thread fix #178 now.

**Comment by danomatika** [comment]
>Perhaps it's not essential but what about setting the default architecture to Universal 32/64bits intel.

Done.

**Comment by danomatika** [comment]
I'm going to close this as it's more or less in there now.
