### ISSUE TITLE
Problem in making javalib in Win7/64bit

### ISSUE THREAD

**Issue by PvonMoradi** [libpd/libpd#195]
I've installed `msys2` and through it, `MinGW32`, `MinGW64` and `make`. I've changed my `PATH` to `MinGW64`. So my `gcc` is the 64bit one. Now, I want to create a .jar file to include to my project in Eclipse.
I `cd`ed into the `libpd` directory and executed `make javalib`. Here is the error I'm getting:
```
C:\Users\Name\Documents\GitHub\libpd>make javalib
gcc -DPD -DHAVE_UNISTD_H -DUSEAPI_DUMMY -I./pure-data/src -I./libpd_wrapper -I./libpd_wrapper/util  -DWINVER=0x502 -DWIN
32 -D_WIN32 -DPD_INTERNAL -I"C:\Program Files\Java\jdk1.8.0_45/include" -I"C:\Program Files\Java\jdk1.8.0_45/include/win
32" -O3   -c -o jni/z_jni_plain.o jni/z_jni_plain.c
In file included from jni/z_jni_shared.c:8:0,
                 from jni/z_jni_plain.c:8:
jni/z_jni.h:2:10: fatal error: jni.h: No such file or directory
 #include <jni.h>
          ^~~~~~~
compilation terminated.
make: *** [<builtin>: jni/z_jni_plain.o] Error 1
```
How can I resolve it?
related SO post: 
[https://stackoverflow.com/questions/46999347/how-to-setup-libpd-for-use-in-java](url)
Thanks

**Comment by danomatika** [comment]
Judging from `jni/z_jni.h:2:10: fatal error: jni.h: No such file or directory`, you either don't have the java compiler installed and/or your path is not configured to find it.

**Comment by danomatika** [comment]
This is most likely not a libpd issue, but an issue with how you have your environment set up: https://stackoverflow.com/questions/13466777/jni-h-no-such-file-or-directory#13467057

**Comment by PvonMoradi** [comment]
It seems my JAVA_HOME directed to the old jdk directory instead of the updated one. I've changed it but now I'm getting this error:
```
C:/msys32/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64                                     -mingw32/bin/ld.exe: i386 architecture of input file `libpd_wrapper/util/z_print                                     _util.o' is incompatible with i386:x86-64 output
libpd_wrapper/util/z_print_util.o:z_print_util.c:(.text+0x3a): undefined referen                                     ce to `_strlen'
libpd_wrapper/util/z_print_util.o:z_print_util.c:(.text+0x75): undefined referen                                     ce to `_strncat'
libpd_wrapper/util/z_print_util.o:z_print_util.c:(.text+0xad): undefined referen                                     ce to `_strncat'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:163: java-build/org/puredata/core/natives/windows/x86_64//pd                                     native.dll] Error 1
```
Should I open another `issue` discussing this problem?

**Comment by danomatika** [comment]
That's strange. Is your compiler not linking the C stdlib? Maybe your environment needs to be upgraded ala https://stackoverflow.com/questions/18649173/how-to-solve-undefined-reference-to-chkstk-ms-on-mingw

**Comment by PvonMoradi** [comment]
@danomatika I've tested the following program and it compiles and runs file with or without `#include <stdio.h>` : 
```
int main() {
	printf("Hello!\n");
	int n = rand();
	printf("n = %d", n);
	return 1;
}
```
Are you sure the error I'm getting is related to this? 
I've also changed my gcc to 32 bit MinGW, here is `gcc -v` : 
```
C:\Users\Name>gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=C:/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.2.0/lto-wrapper.exe
Target: i686-w64-mingw32
Configured with: ../gcc-7.2.0/configure --prefix=/mingw32 --with-local-prefix=/mingw32/local --build=i686-w64-mingw32 --host=i686-
w64-mingw32 --target=i686-w64-mingw32 --with-native-system-header-dir=/mingw32/i686-w64-mingw32/include --libexecdir=/mingw32/lib
--enable-bootstrap --with-arch=i686 --with-tune=generic --enable-languages=c,lto,c++,objc,obj-c++,fortran,ada --enable-shared --en
able-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-time=yes
--disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --e
nable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv -
-with-system-zlib --with-gmp=/mingw32 --with-mpfr=/mingw32 --with-mpc=/mingw32 --with-isl=/mingw32 --with-pkgversion='Rev1, Built
by MSYS2 project' --with-bugurl=https://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld --disable-sjlj-exceptions --wit
h-dwarf2
Thread model: posix
gcc version 7.2.0 (Rev1, Built by MSYS2 project)
```

**Comment by danomatika** [comment]
>Are you sure the error I'm getting is related to this?

I don't know, I'm making informed guesses based on the compiler errors. I didn't write the Java wrapper and haven't worked much with Java in many years.

**Comment by PvonMoradi** [comment]
It seems I've managed to solve it. Here is what I did in in general:
1- First I've installed msys2 and thorough it, `MinGW32` and `MinGW64` and `make`
*Note:* Remove `mingw32` if you've got it from old original site. It is no longer updated and you may encounter dependency issues.
2- Changed PATH to use MinGW32 (so `gcc -v` should report 32 bit version)
3- Changed JAVA_HOME to the updated jdk directory. It seems updating java does not automatically update env. variables.
2- `make clean`
3- `make clean libpd`
4- `make clean javalib`

**Comment by danomatika** [comment]
Ok cool. Closing for now.
