### ISSUE TITLE
object [text define] makes libpd crash

### ISSUE THREAD

**Issue by pierreguillot** [libpd/libpd#196]
Using the object [text define] in a patch makes libpd crash. The crash happens in [text_define_new](https://github.com/pure-data/pure-data/blob/master/src/x_text.c#L280) because **scalar_new(canvas_getcurrent(), gensym("pd-text"));** returns a NULL pointer. The reason is that **template_findbyname(templatesym);** also returns a NULL pointer in [scalar_new](https://github.com/pure-data/pure-data/blob/master/src/g_scalar.c#L113).

**Comment by danomatika** [comment]
Sounds like a problem upstream.

**Comment by pierreguillot** [comment]
I create an issue on Pd repository so I close this one. Thx
