### ISSUE TITLE
wrapper updates

### ISSUE THREAD

**Issue by danomatika** [libpd/libpd#203]
@nettoyeurny @chr15m @residuum @joebowbeer etc

With the changes to the upstream Pd sources and the C core, libpd is now thread safe by default. Also, we've added some functions for multiple instance support and for opening a Pd gui from libpd.

At this point, I'm wonder which language wrappers should/need to be updated for any of this functionality. For example, I've removed the locking in the C++ and ObjC wrappers. As I designed the C++ wrapper to create instances instead of a static interface, I should be able to add transparent instance support. Other wrappers might just wrap the libpd_*_instance calls instead.

In any case, I'm wondering if this is perhaps a good time to consider a libpd 1.0.0 to coincide with all of these new features. So far, I'm considering a prelim 0.11.0 release for now which doesn't factor in major wrapper updates and then we can bring things up to speed for a libpd 1.0.0.

* [ ] Java
* [ ] C++
* [ ] ObjC
* [ ] CSharp
* [ ] Python

**Comment by chr15m** [comment]
Sounds good!

**Comment by residuum** [comment]
Once https://github.com/libpd/libpd/pull/154 is merged, adding multiinstance support to the C# wrapper is trivial. But before that, I would like to update the documentation for C# first.

**Comment by danomatika** [comment]
I think we're getting closer to 0.11.0. A number of issues have been closed and I'm waiting on a feedback for #212 now.

**Comment by danomatika** [comment]
@tkirshboim @joebowbeer I'm thinking of a slight reorganization of the java wrapper layout:

~~~
java                    -> java/classes
jni                       -> java/jni
javatests            -> samples/java/javatests
libs/*java stuff* -> java/libs (optional)
~~~

I'll update the makefile with the new locations, of course.

What do you think? Are there projects external to the repo that rely on the current layout?

**Comment by tkirshboim** [comment]
@danomatika As far as I can see, we'll need to update the 'jni' paths in this repo's [Android.mk file](https://github.com/libpd/libpd/blob/master/Android.mk) and the 'java' path in a [build.gradle file](https://github.com/libpd/pd-for-android/blob/master/PdCore/build.gradle#L28) pd-for-android repo.
I'm not aware of other projects that rely on the current layout.
@joebowbeer ?

**Comment by joebowbeer** [comment]
@danomatika I recommend not folding jni under a java hierarchy. jni and partner libpd_wrapper are used independently of Java. This will also avoid any changes to the Android.mk file.

For changes to the Java hierarchy, which would have no impact on pd-for-android, I would avoid naming any folder `classes` to avoid confusion with the .class files and the classes folder that is created by the build.

I suggest something along the lines of the [standard maven layout](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html).

    java/src/main/**/*.java
    java/src/test/**/*.java
    java/libs

**Comment by danomatika** [comment]
I decided to keep it simple and fit with the existing layout for other wrappers:

~~~
java/**/*.java
samples/java/test/**/.java
~~~

I removed `dist/libpd.jar` and updated the Makefile & Eclipse files. Anything else needed?

**Comment by danomatika** [comment]
Java reorg now in a PR: #221

**Comment by danomatika** [comment]
I'm moving toward just pushing out what we have now as 0.11. It's been sitting long enough (a small child takes priority!) and I'd rather "release early, release often."

**Comment by danomatika** [comment]
As a followup, I've updated the pd-for-ios examples for modern Obj-C and a min iOS 8.0 version.

**Comment by danomatika** [comment]
This issues is out of date. Moving to #317 for libpd 0.12.1.
