### ISSUE TITLE
Multi instance support for MIDI out / Messages receiver / Print

### ISSUE THREAD

**Issue by pierreguillot** [libpd/libpd#204]
What do you think to integrate a multi instance support for this. I already explained the main idea in this Pd [issue](https://github.com/pure-data/pure-data/issues/253). I've implemented it for my plugin: [x_libpd_multi.h](https://github.com/pierreguillot/Camomile/blob/dev/v0.1.0/Source/Pd/x_libpd_multi.h) and and [x_libpd_multi.c](https://github.com/pierreguillot/Camomile/blob/dev/v0.1.0/Source/Pd/x_libpd_multi.c). Things need to be cleaned and adapted before being integrated (there is also a small trick to correct this Pd [bug](https://github.com/pure-data/pure-data/issues/243)) but I think it would be cool!
Tell me an I'll create a PR (Perhaps one for each problem?)

**Comment by danomatika** [comment]
This does look like a good idea in general. I have a few suggestions but will need a week before I can get to it.

**Comment by pierreguillot** [comment]
Alright! Let me know if I can do something. Here are the files [x_libpd_multi.h](https://github.com/pierreguillot/Camomile/blob/master/Source/Pd/x_libpd_multi.h) and [x_libpd_multi.c](https://github.com/pierreguillot/Camomile/blob/master/Source/Pd/x_libpd_multi.c) (the previous links are broken).

**Comment by danomatika** [comment]
In looking at this again, I don't think it would be hard to add per-instance hook variables within libpd itself.

**Comment by danomatika** [comment]
I made ["multi-hooks" branch](https://github.com/libpd/libpd/tree/feature/multi-hooks) with basic per-instance message hooks. We will need to dig deeper for print and MIDI, as you point out.

**Comment by danomatika** [comment]
Well, it's not quite working yet as there are some initial issues. The print hook issue can be solved by making the print hook per-instance in the Pd core. As for MIDI, we might need to do the same, somehow.

**Comment by danomatika** [comment]
We should now have a working implementation via #282.

**Comment by danomatika** [comment]
Howdy again, please test the `feature/multi-hooks` branch which I believe should have most of the kinks worked out.
