### ISSUE TITLE
Building on Windows with mingw

### ISSUE THREAD

**Issue by pierreguillot** [libpd/libpd#209]
Here are my errors [build result](https://ci.appveyor.com/project/pierreguillot/camomile/build/1.0.154/job/krbjc6tsergnf3gy):
```
In file included from pure-data/src/s_inter.c:32:0:
/usr/include/w32api/winsock.h:299:34: error: conflicting types for ‘select’
   WINSOCK_API_LINKAGE int WSAAPI select(int nfds,fd_set *readfds,fd_set *writefds,fd_set *exceptfds,const PTIMEVAL timeout);
```
and
```
pure-data/src/s_inter.c:1189:28: error: ‘P_NOWAIT’ undeclared (first use in this function)
         spawnret = _spawnl(P_NOWAIT, wishbuf, WISH, scriptbuf, portbuf, 0);
```
Here is what I do [script](https://github.com/pierreguillot/Camomile/blob/abc6684a7bb6fba5f75324d0ea9cb9fe553ba34c/appveyor.yml):
```
pacman --noconfirm -S msys/make mingw32/mingw-w64-i686-gcc mingw64/mingw-w64-x86_64-gcc
pacman --noconfirm -S msys/mingw-w64-cross-winpthreads-git
make -C libpd UTIL=true EXTRA=true
```
Do you have any idea of the problem and the solution?

**Comment by danomatika** [comment]
Looks like a bug for upstream pd.

**Comment by danomatika** [comment]
However, other people are building it just fine, so I suspect it's something related to your sys setup.

**Comment by residuum** [comment]
Have you updated upstream pd via `git submodule update` and cleaned with `make clobber` before building?

**Comment by pierreguillot** [comment]
> I've build libpd using MinGW in msys2, not msys.
Me too, I use *msys2* from Appveyor, my command start with
```
C:\msys64\usr\bin\bash
```
that corresponds to msys2 ([documentation](https://www.appveyor.com/docs/build-environment/))

> Have you updated upstream pd via git submodule update
yes

**Comment by pierreguillot** [comment]
And `make clobber` doesn't change anything. Should I create an issue on the pure-data repository?

**Comment by danomatika** [comment]
If you're able to build it fine *not* on Appveyer, that leads to believe it's more of an issue either with the Appveyer setup...

**Comment by pierreguillot** [comment]
The fact is that I don't have a windows computer anymore so I do everything "online". I'll try to find a solution...

**Comment by danomatika** [comment]
I have a windows machine in front of me right now and am trying the build.

**Comment by danomatika** [comment]
Built fine for me in msys2 using MinGW64. Did run into one error, but that was fixed by updating the pure-data sources with `git submodule update`. This is with the current master on Windows 10.

Also, UTIL=true & EXTRA=true are now the defaults, so you can just run `make`.

**Comment by pierreguillot** [comment]
Ok, it's surely a Appveyor problem. I close the issue to avoid to much noise. And keep you informed. If I achieved to compile on Appveyor (that I believe is feasible, I'll surely create a PR with Appveyor support). Thanks!
