### ISSUE TITLE
Static library on Windows with Mingw doesn't work

### ISSUE THREAD

**Issue by pierreguillot** [libpd/libpd#211]
I compile libpd using the Mingw, for example:
```
SET MSYS=C:\msys64
SET MINGW=%MSYS%\mingw32
SET PATH=%MINGW%\bin;%MSYS%\usr\bin
make libpd clobber
make libpd MULTI=true
```
I don't have problem to compile anymore. The compilation gives a dynamic library (dll) and a static library (lib). So I guess I can link with it statically (with lib) but it doesn't work. I try on Visual Studio and try to force the static link but libpd is still missing from the final binaries. So I'm not sure if the lib is really a static library. I note that there is "-shared" option for MINGW_LDFLAGS in the makefile, should I try without it? If it works without it perhaps the static library could be an option? Anyway, if I'm right (I'm not sure) and the lib is not a static library it shouldn't be generated (only the dll would be sufficient)... Any help would be appreciated, I'm confused

**Comment by danomatika** [comment]
It *probably* doesn't work as this has not really been tested that much. I did get the .dll to work with Visual Studio, but did not really try the .lib. Also, I believe there is a "-static" flag as well.

**Comment by pierreguillot** [comment]
Ok. I'll try to figure out the problem. I think the lib is just a dll. I'll keep you informed and will create a PR if I find a solution that seems good. Also if the multi flags is enable, perhaps the lib should be named libpdmulti to avoid conflicts with the classical libpd? Question: Is pthread statically or dynamically linked ?

**Comment by pierreguillot** [comment]
It seems that I'm not competent to create this static library (I'm lost in the makefile). After better investigation, it seems that the lib is not a static library but an import library that calls the dll. That's why it didn't work well for me.

**Comment by pierreguillot** [comment]
I achieved to compile the static library using `$(AR) ...` and removing all the linker flags. But it results by unresolved symbols when I link the lib on MSVC. I'll keep you informed with the next tests (sorry for the noise)

**Comment by danomatika** [comment]
Hrm, I was able to build libpd and use it with an openframeworks project in VS over the summer. Just a regular `make`. It's been awhile but I did fold those changes into the current master.

**Comment by danomatika** [comment]
According to <http://www.mingw.org/wiki/sampleDLL>, "-shared" only specifies building a dll insead of an exe.

**Comment by pierreguillot** [comment]
Yes, I know now. I guess I was confused because the **.lib** isn't a static library. Using the **ar** command seems to be the right approach to build real static libraries but the binary doesn't seem to be compatible with MSVC. I read [this](https://www.codeproject.com/Articles/84461/MinGW-Static-and-Dynamic-Libraries).

**Comment by danomatika** [comment]
I'm looking into it. I know it was working over the summer, but maybe only with the dll.

**Comment by pierreguillot** [comment]
Yes, the dll works for me too. I would have prefer a static library to avoid asking users to install the libpd.dll in the Windows lib folder and to re-install it after updates. But for now, I use the approach. Another solution would been to keep the libpd.dll next to my plugins but most of the DAWs don't like that (they think it's another plugin...). So if you find a solution I would be really pleased! Thanks!

**Comment by danomatika** [comment]
From what I've read, the plain C ABI is portable between MinGW and MSVC so building a libpd.a with the right settings should work in MSVC by simply renaming it to pd.lib.

**Comment by danomatika** [comment]
Well, I got close with the following:

~~~
%.o : %.c
	$(CC) -c $(CFLAGS) $< -o $@ \
	-fno-stack-check -fno-stack-protector -mno-stack-arg-probe \
	-Wl,--export-all-symbols -static-libgcc \
	-static -lpthread -lm

static: libs/libpd.lib
	
libs/libpd.lib: ${PD_FILES:.c=.o} ${UTIL_FILES:.c=.o} ${EXTRA_FILES:.c=.o}
	ar rcs $@ $^
~~~

But ofxPd fails to build in VS 2015 due to missing pthread and a few MS-specific C symbols.

**Comment by pierreguillot** [comment]
Thanks, I'll try to restart some tests based on this.

**Comment by danomatika** [comment]
See also the discussons related to the -static flag at the pdlibbuilder repo: https://github.com/pure-data/pd-lib-builder/issues

**Comment by pierreguillot** [comment]
I managed to compile a static library using Visual Studio. I compiled the pthread library from this repository https://github.com/GerHobbelt/pthread-win32.git and then libpd using CMake to generate the project. I compiled everything with the static runtime library (`/MT`) but if your Windows target is superior or equal to Windows 10, you can compile with the dynamic runtime library (`/MD`). You can have a look at the Appveyor configuration [file](https://github.com/pierreguillot/Camomile/blob/master/appveyor.yml) of my plugin [Camomile](https://github.com/pierreguillot/Camomile). And the CMakeList to generate the Visual Studio project is in the submodule `Dependencies/LibPd`. And you can also have a look at the PR #226 for CMake support on libpd.  

Even if it's not with Mingw, for my part you can close the issue but feel free to keep it open if you prefer.

**Comment by danomatika** [comment]
Closing for now.
