### ISSUE TITLE
change log level

### ISSUE THREAD

**Issue by pierreguillot** [libpd/libpd#217]
*sys_debuglevel* is set to 0 during libpd initialization (l.75 in z_libpd.c). I think it could be great if we could set this to another value with a funtion like *void libpd_setdebuglevel(int level)* for example. It would help people debugging their patches in Camomile.

**Comment by danomatika** [comment]
Maybe we need a set:

    void libpd_set_loglevel(int level);
    int libpd_get_loglevel();

**Comment by pierreguillot** [comment]
In fact this is sys_verbose that needs to be changeable. I create a PR.

**Comment by danomatika** [comment]
Closed with #218.
