### ISSUE TITLE
libpd message wrapper not thread safe

### ISSUE THREAD

**Issue by pierreguillot** [libpd/libpd#219]
The functions `libpd_start_message()`, `libpd_add_float()`, `libpd_add_symbol()`,  and `libpd_finish_list()` are not thread as they use the static variable `argv, argc, curr, argm` (l.56-57 in z_libpd.c). Perhaps a solution would be to use the `PERTHREAD` macro of Pd:
```
static PERTHREAD t_atom *argv = NULL;
static PERTHREAD t_atom *curr = NULL;
static PERTHREAD int argm = 0;
static PERTHREAD int argc = 0;
```

**Comment by danomatika** [comment]
Ok. Done.
