### ISSUE TITLE
LibPD latency in slow in Java

### ISSUE THREAD

**Issue by pvonmoradi** [libpd/libpd#223]
I made a simple patch which generates a cosine function with varying `frequency` and `volume` for each channel. 
Here is what my patch is like:
[my patch](https://imgur.com/a/uVRRG)
Here is my Java code:
```
private void setUpLibpdBasedSound() {
        audioThread = new JavaSoundThread(44100, 2, 4);
        try {
            patch = PdBase.openPatch("...");
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        audioThread.start();
```
Now, when I want to change for example the volume from 1 to 0 , I use this code:
```
PdBase.sendFloat("leftVolume", (float) 0);
PdBase.sendFloat("rightVolume", (foat) 0);
```
But with this method, I have like 0.5 seconds latency (in this case from sound to no sound) which is too much in my application. The same also happens when I want to change any of my patch parameters.
What should I do to decrease latency? 
Should I use some other methods in Java side (libpd) or pd side (patch) ?

Thanks

**Comment by danomatika** [comment]
I didn't write that sample, but looking at the code, you need to change the buffer size for the thread: https://github.com/libpd/libpd/blob/master/samples/java/com/noisepages/nettoyeur/libpd/sample/JavaSoundThread.java#L40

It's currently 16 ticks when created with:

    JavaSoundThread audioThread = new JavaSoundThread(44100, 2, 16);

The block size per tick is 64 samples, so 16 * 64 gives us a latency of 1024 which is pretty long for interactive stuff. Try something like 4 ticks which is a buffer size of 256 samples.

    JavaSoundThread audioThread = new JavaSoundThread(44100, 2, 4);

If it's too short and ou get audio dropouts/clicks, increase the number of ticks.

**Comment by pvonmoradi** [comment]
@danomatika But as you can see in my original post, I've already changed `Tick` to 4 and I'm still getting a 500ms lag between my interactions
Here is another code:
```
audioThread = new JavaSoundThread(44100, 2, 4);
        patch = PdBase.openPatch("src/com/noisepages/nettoyeur/libpd/sample/test2.pd");
        audioThread.start();
        System.out.println(LocalDateTime.now());
        System.out.println(PdBase.sendFloat("volume", (float) 1));
        System.out.println(LocalDateTime.now());
        Thread.sleep(1000);
        System.out.println(LocalDateTime.now());
        System.out.println(PdBase.sendFloat("volume", (float) 0));
        **System.out.println(LocalDateTime.now());**
        Thread.sleep(1000);
        System.out.println(LocalDateTime.now());
```
And here is its console output:
```
2018-01-16T15:57:19.736
0
2018-01-16T15:57:19.737
2018-01-16T15:57:20.737
0
**2018-01-16T15:57:20.737**
2018-01-16T15:57:21.737
```
As soon as the bold lines run, I should hear PD becoming silent but it does so with a ~500ms lag.
latency@(tick) = 1000 * tick * 64 / 44100 // in milli-seconds

**Comment by danomatika** [comment]
I don't know. It might be related to the message polling frequency?

**Comment by pvonmoradi** [comment]
@danomatika do you know where can I change that?

**Comment by danomatika** [comment]
I don't know, only a thought. Probably within the JNI somewhere. Pinging @nettoyeurny

**Comment by pvonmoradi** [comment]
@danomatika Also, what if I decrease block size in PureData->Audio settings from 64 to something like 16?

**Comment by pvonmoradi** [comment]
Tested with a bluetooth headphone, I'm getting ~700ms latency now!

**Comment by Ant1r** [comment]
>
> what if I decrease block size in PureData->Audio settings from 64


Pd internal block size should have no effect on this.

Audio latency is a major concern on Android. OpenSL can help lowering it,
see for example:
https://github.com/nettoyeurny/opensl_stream_sample


Antoine Rousseau
  http://www.metalu.net <http://metalu.net> __
http://www.metaluachahuter.com/
<http://www.metaluachahuter.com/compagnies/al1-ant1/>


2018-01-16 13:47 GMT+01:00 Pooya Moradi <notifications@github.com>:

**Comment by pvonmoradi** [comment]
@Ant1r I'm working on a Win7/64-bit with Java/JavaFX. I'm not using Android at the moment.

**Comment by mgsx-dev** [comment]
from my experience JavaSound doesn't provide low latency (see here : http://www.jsresources.org/faq_audio.html#min_buffersize). There are several layers after LibPD in your case depending on your OS, driver and hardware. And unfortunately JavaSound doesn't provide configuration neither.

FYI, I created a [wrapper for libgdx](https://github.com/mgsx-dev/gdx-pd) which uses OpenAL. It provides buffer size configuration and I have low latency on Linux right now.

**Comment by danomatika** [comment]
Seems the answer is "JavaSound is slow." :P

**Comment by pvonmoradi** [comment]
@mgsx-dev What if I use JavaFX's audio functions? Would that be better? But I couldn't do "synthesis" much with those methods and classes I think

**Comment by mgsx-dev** [comment]
@pvonmoradi I don't know, I'm only using libgdx now.

**Comment by danomatika** [comment]
If this is less of an issue with libpd itself and more with Java and/or it's audio backends, can we close this?
