### ISSUE TITLE
Problems in building libpd for python

### ISSUE THREAD

**Issue by pvonmoradi** [libpd/libpd#224]
I'm trying to build `libpd` for Python 3.5.2. Three dependencies are needed (According to [here](https://github.com/libpd/libpd/wiki/Python-API)):

1. swig: generates Python wrapper from the C code
2. portaudio: audio api library
3. pyaudio: python portaudio bindings

1- I installed swig by downloading ready-made windows builds from [http://www.swig.org/download.html](http://www.swig.org/download.html) and added it to my system PATH env. variable
3- Installed pyaudio using `pip install pyaudio` with success.
2- Now for portaudio, `pip install portaudio` throws the following error:
`λ pip install portaudio
Collecting portaudio
  Could not find a version that satisfies the requirement portaudio (from versions: )
No matching distribution found for portaudio`

OK. Maybe `portaudio` is not needed. I try to `make` with these commands and again I'm getting a complaint about a most weird "vcvarsall.bat"

```
C:\Users\Pooya\Documents\GitHub\libpd (HEAD detached at c847512 -> origin)
λ cd python

C:\Users\Pooya\Documents\GitHub\libpd\python (HEAD detached at c847512 -> origin)
λ make
python setup.py build
running build
running build_py
creating build
creating build\lib.win-amd64-3.5
copying pylibpd.py -> build\lib.win-amd64-3.5
running build_ext
building '_pylibpd' extension
swigging pylibpd.i to pylibpd_wrap.c
C:\swigwin-3.0.12\swig.exe -python -o pylibpd_wrap.c pylibpd.i
error: Unable to find vcvarsall.bat
make: *** [Makefile:22: build] Error 1
```
Any help is appreciated

**Comment by cpuloader** [comment]
This is because you didn't tell python to use mingw compiler.
Workaround is described [here](https://github.com/pypa/setuptools/issues/1118#issuecomment-345878960).

I'm building libpd on Windows 7 x64 with mingw64.
Everything was fine, but in the end of compiling i got a lot of these errors:
```
.......
build/temp.mingw-2.7/../pure-data/extra/stdout/stdout.o:stdout.c:(.text+0x59d): undefined reference to `__imp_gensym'
build/temp.mingw-2.7/../pure-data/extra/stdout/stdout.o:stdout.c:(.text+0x5d2): undefined reference to `__imp_class_new'
build/temp.mingw-2.7/../pure-data/extra/stdout/stdout.o:stdout.c:(.text+0x5ee): undefined reference to `__imp_class_addanything'
collect2.exe: error: ld returned 1 exit status
error: command 'D:\\msys64\\mingw64\\bin/x86_64-w64-mingw32-gcc.exe' failed with exit status 1

```
Any solutions?

**Comment by danomatika** [comment]
Any updates on this? The error looks like the linker can't link to the pd.dll. This *should* be fixed now with some recent updates to the Makefile.

**Comment by cpuloader** [comment]
I made working .pyd file this way finally:
1. Run make file in libpd directory (it worked fine)
2. Run make in python directory (with errors)
3. Replace *.o files created in step 2 with files created in step 1

4. Compile pylibpd_wrap:  `D:\msys64\mingw64\bin\gcc.exe -DPD -DHAVE_UNISTD_H -DUSEAPI_DUMMY -I../libpd_wrapper -I../pure-data/src -I../pure-data/extra -DWINVER=0x502 -DMS_WIN64 -DPD_INTERNAL -I"C:\Program Files\Java\jdk1.8.0_131/include" -I"C:\Program Files\Java\jdk1.8.0_131/include/win32" -ffast-math -funroll-loops -fomit-frame-pointer -O3 -DLIBPD_EXTRA  -Ic:/Python27/include -c pylibpd_wrap.c -o build/temp.win-amd64-2.7/Release/pylibpd_wrap.o`

5. Make pyd: `D:\msys64\mingw64\bin\gcc.exe -shared -Wl,--enable-auto-image-base -pipe -s -s build\temp.win-amd64-2.7\Release\pylibpd_wrap.o build\temp.win-amd64-2.7\libpd_wrapper\s_libpdmidi.o build\temp.win-amd64-2.7\libpd_wrapper/x_libpdreceive.o build\temp.win-amd64-2.7\libpd_wrapper/z_hooks.o build\temp.win-amd64-2.7\libpd_wrapper/z_libpd.o build\temp.win-amd64-2.7\pure-data/src/d_arithmetic.o build\temp.win-amd64-2.7\pure-data/src/d_array.o build\temp.win-amd64-2.7\pure-data/src/d_ctl.o build\temp.win-amd64-2.7\pure-data/src/d_dac.o build\temp.win-amd64-2.7\pure-data/src/d_delay.o build\temp.win-amd64-2.7\pure-data/src/d_fft.o build\temp.win-amd64-2.7\pure-data/src/d_fft_fftsg.o build\temp.win-amd64-2.7\pure-data/src/d_filter.o build\temp.win-amd64-2.7\pure-data/src/d_global.o build\temp.win-amd64-2.7\pure-data/src/d_math.o build\temp.win-amd64-2.7\pure-data/src/d_misc.o build\temp.win-amd64-2.7\pure-data/src/d_osc.o build\temp.win-amd64-2.7\pure-data/src/d_resample.o build\temp.win-amd64-2.7\pure-data/src/d_soundfile.o build\temp.win-amd64-2.7\pure-data/src/d_ugen.o build\temp.win-amd64-2.7\pure-data/src/g_all_guis.o build\temp.win-amd64-2.7\pure-data/src/g_array.o build\temp.win-amd64-2.7\pure-data/src/g_bang.o build\temp.win-amd64-2.7\pure-data/src/g_canvas.o build\temp.win-amd64-2.7\pure-data/src/g_clone.o build\temp.win-amd64-2.7\pure-data/src/g_editor.o build\temp.win-amd64-2.7\pure-data/src/g_graph.o build\temp.win-amd64-2.7\pure-data/src/g_guiconnect.o build\temp.win-amd64-2.7\pure-data/src/g_hdial.o build\temp.win-amd64-2.7\pure-data/src/g_hslider.o build\temp.win-amd64-2.7\pure-data/src/g_io.o build\temp.win-amd64-2.7\pure-data/src/g_mycanvas.o build\temp.win-amd64-2.7\pure-data/src/g_numbox.o build\temp.win-amd64-2.7\pure-data/src/g_readwrite.o build\temp.win-amd64-2.7\pure-data/src/g_rtext.o build\temp.win-amd64-2.7\pure-data/src/g_scalar.o build\temp.win-amd64-2.7\pure-data/src/g_template.o build\temp.win-amd64-2.7\pure-data/src/g_text.o build\temp.win-amd64-2.7\pure-data/src/g_toggle.o build\temp.win-amd64-2.7\pure-data/src/g_traversal.o build\temp.win-amd64-2.7\pure-data/src/g_vdial.o build\temp.win-amd64-2.7\pure-data/src/g_vslider.o build\temp.win-amd64-2.7\pure-data/src/g_vumeter.o build\temp.win-amd64-2.7\pure-data/src/m_atom.o build\temp.win-amd64-2.7\pure-data/src/m_binbuf.o build\temp.win-amd64-2.7\pure-data/src/m_class.o build\temp.win-amd64-2.7\pure-data/src/m_conf.o build\temp.win-amd64-2.7\pure-data/src/m_glob.o build\temp.win-amd64-2.7\pure-data/src/m_memory.o build\temp.win-amd64-2.7\pure-data/src/m_obj.o build\temp.win-amd64-2.7\pure-data/src/m_pd.o build\temp.win-amd64-2.7\pure-data/src/m_sched.o build\temp.win-amd64-2.7\pure-data/src/s_audio.o build\temp.win-amd64-2.7\pure-data/src/s_audio_dummy.o build\temp.win-amd64-2.7\pure-data/src/s_inter.o build\temp.win-amd64-2.7\pure-data/src/s_loader.o build\temp.win-amd64-2.7\pure-data/src/s_main.o build\temp.win-amd64-2.7\pure-data/src/s_path.o build\temp.win-amd64-2.7\pure-data/src/s_print.o build\temp.win-amd64-2.7\pure-data/src/s_utf8.o build\temp.win-amd64-2.7\pure-data/src/x_acoustics.o build\temp.win-amd64-2.7\pure-data/src/x_array.o build\temp.win-amd64-2.7\pure-data/src/x_arithmetic.o build\temp.win-amd64-2.7\pure-data/src/x_connective.o build\temp.win-amd64-2.7\pure-data/src/x_gui.o build\temp.win-amd64-2.7\pure-data/src/x_interface.o build\temp.win-amd64-2.7\pure-data/src/x_list.o build\temp.win-amd64-2.7\pure-data/src/x_midi.o build\temp.win-amd64-2.7\pure-data/src/x_misc.o build\temp.win-amd64-2.7\pure-data/src/x_net.o build\temp.win-amd64-2.7\pure-data/src/x_scalar.o build\temp.win-amd64-2.7\pure-data/src/x_text.o build\temp.win-amd64-2.7\pure-data/src/x_time.o build\temp.win-amd64-2.7\pure-data/src/x_vexp.o build\temp.win-amd64-2.7\pure-data/src/x_vexp_if.o build\temp.win-amd64-2.7\pure-data/src/x_vexp_fun.o build\temp.win-amd64-2.7\pure-data/extra/bob~/bob~.o build\temp.win-amd64-2.7\pure-data/extra/bonk~/bonk~.o build\temp.win-amd64-2.7\pure-data/extra/choice/choice.o build\temp.win-amd64-2.7\pure-data/extra/fiddle~/fiddle~.o build\temp.win-amd64-2.7\pure-data/extra/loop~/loop~.o build\temp.win-amd64-2.7\pure-data/extra/lrshift~/lrshift~.o build\temp.win-amd64-2.7\pure-data/extra/pique/pique.o build\temp.win-amd64-2.7\pure-data/extra/sigmund~/sigmund~.o build\temp.win-amd64-2.7\pure-data/extra/stdout/stdout.o build\temp.win-amd64-2.7\Release/_pylibpd.def -Ld:/msys64/mingw64/lib -Lc:/Python27/libs -lm -ldl -lpthread -lpython27 -lws2_32 -o build\lib.win-amd64-2.7\_pylibpd.pyd`

**Comment by cpuloader** [comment]
I tried this and it worked:
In python/setup.py:
`                  define_macros = [
                    ('PD', 1),
                    ('HAVE_UNISTD_H', 1),
                    ('HAVE_LIBDL', 1),
                    ('USEAPI_DUMMY', 1),
                    ('LIBPD_EXTRA', 1),
                    ('WINVER', 0x502),
                    ('MS_WIN64', 1),
                    ('PD_INTERNAL', 1)
                  ],`
and
`                  libraries = [
                    'm',
                    'dl',
                    'pthread',
                    'ws2_32'
                  ],
`

**Comment by danomatika** [comment]
Please try the `bugfix/win64-pybuild` [branch](https://github.com/libpd/libpd/tree/bugfix/win64-pybuild). I added some of the commonly-required flags for windows except for MS_WIN64. If you end up needing to define it, you could do so via:

~~~
cd python
make CFLAGS="-DMS_WIN64=1"
~~~

**Comment by danomatika** [comment]
I've gone ahead and merged the branch as well as added a note about the `MS_WIN64` flag [to the readme](d0a73dd3d00d444d6249d3b61401e4005c5cd092). Closing this for now.
