### ISSUE TITLE
How to get the libpdcsharp.dll

### ISSUE THREAD

**Issue by out-of-pixel** [libpd/libpd#23]
Hello,

hope here the right place for my Question.
I want to use the libpd for my C# Project under Windows but i don't know to compile the Dll.
Here is what i tried:
1. Compile the LibPDBinding Project with VS -> Don't work, Project need the Dll.
2. Run the Makefile with Cygwin -> Syntax Error: `ifeq ($(UNAME), Darwin)  # Mac'
3. Run the Makefile under OSX -> Error(don't have the Message here)

What else can i try? How to get the Dll?

**Comment by WorshipCookies** [comment]
Hey guys I am having a very similar issue to this one. I added the libpdcsharp.dll to my Debug folder where my main .exe is but I am still getting this error when i do LibPD.OpenAudio().

Unable to load DLL 'libpdcsharp.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

Not really sure what could be the problem, as I had been using this code without a problem on my previous computer, but with the switch it seems that something is wrong with my references. I am using VS2015.

**Comment by residuum** [comment]
Can you try the changes from the PR #113, especially the change to the Makefile: https://github.com/residuum/libpd/commit/1bea7716e4e8e424caa066681a552ece7e408010#diff-b67911656ef5d18c4ae36cb6741b7965L28

**Comment by WorshipCookies** [comment]
Yes I made those changes, and I actually was able to solve the problem, based on something else entirely. For some reason my version of MinGW wasn't included in the PATH, so by including it I was able to fix my problem.

Thanks for the quick reply!
