### ISSUE TITLE
iOS app with libpd rejected because of 'the use of non-public API'

### ISSUE THREAD

**Issue by marineturtle** [libpd/libpd#231]
I have an iOS app with libpd, which has been on App Store for a few years. When I submitted an update to Apple recently, it was rejected because of 'the use of non-public API in Guideline 2.5.1 - Performance'. The App review comment says, 

> your app uses or references non-public APIs, which is not permitted on the App Store. Specifically, your app's PdBase class (which appears, but is not guaranteed, to be part of the Pure Data libpd library) implements the non-public selector _setup from the CoreSpeech.framework. It would be appropriate to remove this reference before resubmitting for review.

Is it true that libpd or pure-data uses the '_setup' method of the CoreSpeech.framework?

I tried to find a reference to CoreSpeech in libpd and pure-data, but couldn't find any so far. One thing I found during the search was a string, '_setup', is used at [the line 143 in s_loader.c under pure-data](https://github.com/pure-data/pure-data/blob/master/src/s_loader.c#L143), although I am not sure if this is related to CoreSpeech.framework or not.

Thank you very much for your time for this. Any help would be appreciated.

**Comment by danomatika** [comment]
>PdBase class (which appears, but is not guaranteed, to be part of the Pure Data libpd library) implements the non-public selector _setup from the CoreSpeech.framework

That's BS. There is no call to a "_setup" function but this is used for the pd class naming in C ala "bang_setup()." The loader uses this fact to determine the setup functions naming on the run when loading an external. It looks like an automatic check false positive as we do not use the CoreSpeech framework.

**Comment by marineturtle** [comment]
Thank you very much for your prompt reply! I am more confident now, and am going to appeal the rejection to the app review board.

**Comment by marineturtle** [comment]
Although I appealed to the app review board, the decision was not changed. However, I got more detailed information of the actual issue. The reply says:

> we continue to notice that the dynamic loading the the 'setup' or '_setup' selector on line 219 and 232 of https://github.com/pure-data/pure-data/blob/1c60a514eab4141b708c5df5e6f401d796500088/src/s_loader.c is the cause of this issue. It would be appropriate to statically call the selector you are wishing to use instead of invoking dlopen() or dlsym() to access them.

**Comment by danomatika** [comment]
If they read the preprocessor defines, neithr of those lines are compiled for or used on iOS:

* Line 219 is within #ifdef _WIN32
* Line 232 is within #elif defined(HAVE_LIBDL) || defined(__FreeBSD__)

libpd is *not* compiled with HAVE_LIBDL defined, therefor dynamic loading has been disabled. This has *always* been the case.

**Comment by marineturtle** [comment]
Thank you very much for the information. I found my app use that flag also for ios. I resubmitted the app after removing the flag. And, it was approved. Thanks again for your help on this!

**Comment by danomatika** [comment]
Cool I.f you're compiling the libdl part, then it make more sense that they raised an issue. AN easy fix at least and we'll add some info to the readme/wiki as a reminder.

**Comment by danomatika** [comment]
Added here: https://github.com/libpd/libpd/wiki/Working-with-libpd-in-Xcode#have_libdl
