### ISSUE TITLE
LibPDBinding Nuget package missing namespace

### ISSUE THREAD

**Issue by berdle** [libpd/libpd#236]
When I use Nuget to install the LibPDBinding under Visual Studio 2017, only the root namespace of LibPDBinding is visible. I've downloaded the source and rebuilt LibPDBinding.dll myself and if I do that then the rest of the namespace (eg. Managed, etc.) is visible.

Running Windows 10, Visual Studio 2017 Community, Version 15.2

**Comment by LukasPirkl** [comment]
I think this is because of the version with `LibPDBinding.Managed` namespace is not released, yet. Latest version on nuget.org is 0.10.0 but from the code, it looks like the new API is planned to version 0.11.

**Comment by residuum** [comment]
@LukasPirkl is correct.

**Comment by berdle** [comment]
Thanks

**Comment by danomatika** [comment]
Should be coming soon.

**Comment by residuum** [comment]
Soon is today ;) 

https://www.nuget.org/packages/LibPDBinding/0.11.0

**Comment by danomatika** [comment]
Fixed via #254.
