### ISSUE TITLE
Unity iOS

### ISSUE THREAD

**Issue by unbounded26** [libpd/libpd#238]
Kindly can you provide instructions to make a build from Unity for iPhone and iPad

**Comment by danomatika** [comment]
We don't provide direct Unit support as none of the main libpd developers use Unity. In essence, we don't know what the instructions would be. As libpd is a plain C library, it should be possible but you'll need to ask Unity developers about the details.

**Comment by unbounded26** [comment]
Thanks for your reply.

It seems [libpd/pd-for-ios](https://github.com/libpd/pd-for-ios), is very old and still has `release` and `autorelease` calls which are obsolete due to ARC.

**Comment by danomatika** [comment]
>It seems libpd/pd-for-ios, is very old and still has release and autorelease calls which are obsolete due to ARC.

This is a separate issue which should be opened at that repo instead.

**Comment by danomatika** [comment]
>It seems libpd/pd-for-ios, is very old and still has release and autorelease calls which are obsolete due to ARC.

All pd-for-ios examples have now been updated.
