### ISSUE TITLE
Multi-instance Support Using The C++ Wrapper

### ISSUE THREAD

**Issue by JeffersonBledsoe** [libpd/libpd#239]
It would be quite useful to have multiple patches run in different classes using C++, and the multi-instance support from the C library allows this. Could we extend this to the C++ wrapper?

**Comment by danomatika** [comment]
Yes, that's the idea. We just haven't updated the wrapper yet as I want to make sure the changed won't break anything for existing projects.

**Comment by mathieugarcia** [comment]
Hi there !

Just chiming in to inquiry about the current status of this request.

Thanks.
Mathieu.

**Comment by danomatika** [comment]
For now, you can always call the libpd_*_instance C functions in C++.

**Comment by mathieugarcia** [comment]
@danomatika That's what I ended up doing. Working perfectly !

**Comment by danomatika** [comment]
Please look into the `feature/multi-hooks` branch which includes a revamped PdBase with built-in instance support. There is also a pdtest_multi example in `samples/cpp`.

These updates will most likely result in changes to existing projects which are using libpd_*_instance C functions manually, so it would be good to get some feedback.
