### ISSUE TITLE
Refactor C pdtest_gui to be platform-independent

### ISSUE THREAD

**Issue by eldruin** [libpd/libpd#246]
The sample program `samples/c/pdtest_gui` is POSIX-dependent because it uses `gettimeofday()`.
It should be possible to refactor the code to get rid of this dependency as it is only used to sleep for some time.

**Comment by danomatika** [comment]
Possible easy fix: https://stackoverflow.com/a/26085827

**Comment by danomatika** [comment]
Somehow it doesn't. It opens the gui and loops until you close the gui. I'm not quite sure how it does that either.

**Comment by danomatika** [comment]
I added the `gettimeofday()` wrapper as a header. Please test and reopen if it doesn't work.
