### ISSUE TITLE
Print hook can't be reset after libpd_init has run

### ISSUE THREAD

**Issue by NiallMoody** [libpd/libpd#247]
Hi,

I'm developing a [Unity wrapper](https://github.com/LibPdIntegration/LibPdIntegration) for libpd incorporating libpd's new multi-instance support. In order to get libpd working with Unity though, I had to modify libpd_set_printhook to set the sys_printhook variable directly instead of waiting until libpd_init is called.

To explain, here's the typical development process if you're making a game (with libpd) in Unity:

1. Do some work in the Unity editor.
2. Run the game within the editor to test it.
a. From the game, run a script that calls the various libpd functions. Set up a print hook so we can debug patches if necessary.
3. Quit the game, return to the editor.
a. Note: The Unity editor does not unload dlls once they've been loaded. libpd is still active, though any hooks we've passed libpd have now been deleted.
4. Make some changes to the game's assets.
5. Run the game within the editor again to test.
6. Unity crashes.

The problem is that since libpd is already running, and libpd_init returns immediately if it's already been initaialized, our print hook never gets updated to point to the new hook we've set for the second instance of the game, and Unity crashes as a result.

Apologies if this should have been a pull request. I wasn't sure what the eitquette for pull requests was, and it's not clear to me if resetting the print hook after libpd_init has run might introduce unforeseen consequences (I haven't encountered any issues as a result of it myself).

**Comment by danomatika** [comment]
Why not clear the hooks on quit?

**Comment by NiallMoody** [comment]
Ah, yeah, I'm actually already doing that. The problem I've found is that calling libpd_set_printhook just sets the libpd_printhook variable, which is used in libpd_init (and only in libpd_init) to set the sys_printhook  variable from pure data.

And because libpd_init returns immediately if it's already been called, there's no way of resetting sys_printhook once libpd_init has been called.

**Comment by danomatika** [comment]
Ok, I see what you mean. Two things to try:

1. Set the print hook after calling libpd_init(). The print hook is NULL by default and it seems that pd simply prints to stderr if sys_printhook is NULL.

2. Can you build libpd for C# yourself? Comment out the `sys_printhook = (t_printhook) libpd_printhook;` line in z_libpd.c and rebuild both libpd and the C# wrapper.

In either case, I don't think that sys_printhook needs to be set there at all, so I will probably remove that line after some more testing.

**Comment by danomatika** [comment]
@nettoyeurny Any thoughts on removing https://github.com/libpd/libpd/blob/master/libpd_wrapper/z_libpd.c#L72?

**Comment by nettoyeurny** [comment]
I'd like to make sure that libpd_init initializes sys_printhook. The simplest solution might be to just move this line to the top of libpd_init, so that it'll always be called, regardless of whether the initialized flag is set.

That flag only serves to protect calls that may have funny effects when invoked repeatedly (such as buffer allocations or external setup), otherwise it should be perfectly fine to reinitialize things.

**Comment by danomatika** [comment]
How about setting sys_printhook in libpd_set_printhook? I'm preparing a PR which does this or is this overkill?

**Comment by danomatika** [comment]
As @nettoyeurny suggested, I moved `sys_printhook = (t_printhook) libpd_printhook;` up so it is always performed when running libpd_init().

**Comment by nettoyeurny** [comment]
Thanks, Dan!

**Comment by nettoyeurny** [comment]
On second thought, I think @danomatika's proposal was better. I thought I was regularizing things by introducing the libpd_printhook variable (since we need all kinds of other hooks for libpd), but in fact libpd_printhook is a bit irregular because unlike the other hooks, it is only a proxy for a built-in property of Pd and writing to it has no immediate effect, as Niall observed.

So, I now believe that it would be cleaner to just nuke libpd_printhook altogether and have libpd_set_printhook assign to sys_printhook directly.

What do you think?

**Comment by nettoyeurny** [comment]
Another thing is that there's a weird little path dependency here. Originally the hook variables were exposed to developers and there were no libd_set_*hook functions. At that time, libpd_printhook sort of made sense to developers wouldn't have to remember that printing is different somehow.

Then this approach caused some linking issue on Windows if I recall correctly, and so we invented the libpd_set_*hook functions. Now libpd_printhook is just an implementation detail, and so we can safely change it :)

**Comment by NiallMoody** [comment]
That seems like a good solution, thanks!

**Comment by danomatika** [comment]
@NiallMoody Let's leave this open until you have a chance to build/test the C# wrapper.

**Comment by NiallMoody** [comment]
@danomatika Just built and tested it, and it's working fine for me. I should clarify that I'm not actually using the libpd C# wrapper, as I couldn't get it working with Unity. I don't know if that's an issue with Unity or my own relative unfamiliarity with C#.

Also, I wanted multi-instance support. I've noticed you've got a pull request to add that to the C# wrapper though. Once that's merged and I have some time I'll come back to it and see if I can figure out what the problem was.

**Comment by danomatika** [comment]
Fixed with latest commits.

**Comment by danomatika** [comment]
Multi-instance support is rolling out slowly and the C# stuff will probably not be in the 0.11 release. I think we want to move to separate libpd variables per instance (hooks, queues, etc) and we're not at what I would consider a finished state yet, although it does work with the global hooks.
