### ISSUE TITLE
pylibpd Not Producing Sounds

### ISSUE THREAD

**Issue by bkamino1** [libpd/libpd#256]
I am having an issue with my pylibpd installation not making sound. I have everything installed correctly (I can import the pylibpd module), but when running even a simple test, I am unable to produce sound. I have the following basic Pd sketch:
![test pd](https://user-images.githubusercontent.com/30415057/49453134-886dc480-f7b0-11e8-91f9-7e6a5943543c.png)
and the following python code:
```
import pylibpd as pd
import time

def pd_receive(*s):
    print 'received:', s

pd.libpd_set_print_callback(pd_receive)

ch = 1
sr = 44100

m = pd.PdManager(ch, ch, sr, 1)
pd.libpd_open_patch('test.pd')

time.sleep(10)

pd.libpd_release()
```
When I run `python test.py` from the command line, I get the following output:
`received: ("'sdf': bang\n",)`
with the terminal hanging for the appropriate amount of time.

I have tested my pyaudio installation by playing a sine wave generated with numpy, and I hear the sound being played.

I am running portaudio version 19.6.0, pyaudio version 0.2.11, libpd version 0.11.0, and Python 2.7.15 in an MSYS2 environment on Windows 10. If anyone has any ideas on what might be wrong or what I can do to troubleshoot, that would be very appreciated. Thanks!

**Comment by Ant1r** [comment]
I think you just have to send "dsp 1" to pd; simplest way would be to loadbang a message` [;pd dsp 1(` in your patch, but you could also do it from the python script.

**Comment by bkamino1** [comment]
Thanks for the response! I added that message box into the patch, but I'm still getting the same results, whereas when I load the patch in Pd it works as expected.

**Comment by Ant1r** [comment]
Did you connect a [loadbang] to it?
![loadbangdsp](https://user-images.githubusercontent.com/3748246/49472976-17122e00-f811-11e8-8e3b-450578751674.png)

**Comment by bkamino1** [comment]
Yes, the message box is connected to a loadbang. It works properly when I open it in Pd (i.e. the osc~ starts playing as soon as the patch opens), but not when I open the patch in pylibpd.

**Comment by danomatika** [comment]
I have not really used the Python wrapper, but if you compare your file with one of the Python samples, say "echo.py", it seems you are missing the most important part: audio processing, ie. calls to one of the process functions via a sound API. This isn't done by default in the background for you, so what your file is doing is: 1. init, 2. load a file, 3. wait 10 seconds, close.

I will close this for now. Re-open if there is a further issue.
