### ISSUE TITLE
Run libpd in batch mode. Is it possible to run "offline".

### ISSUE THREAD

**Issue by cerupcat** [libpd/libpd#257]
I'd like to use pd to analyze an audiofile (extract pitch information) faster than real-time. My understanding is this could be possible using -batch argument when opening pd. Is there an example of this with libpd?

**Comment by cerupcat** [comment]
Looks like this is the code for PD in batch mode

```
int m_batchmain(void)
{
    while (sys_quit != SYS_QUIT_QUIT)
        sched_tick();
    return (0);
}```

Does that mean we could just send processFloatWithInputBuffer (or equivalent) outside of the audio thread to run through sample data as fast as the system will allow?

**Comment by mgsx-dev** [comment]
@cerupcat i made a ruby wrapper a while ago precisely for that need, maybe you could give it a try : https://github.com/mgsx-dev/pd-offline

**Comment by cerupcat** [comment]
Thanks, @danomatika @mgsx-dev I'll take a look.

I'm looking to do this on iOS/Android, but I'll take a look at those examples to see if I can get a test up and running.

**Comment by danomatika** [comment]
The algorithm is the same, regardless: simply run libpd in a loop with a dummy buffer.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by virusys** [comment]
When you're running patches in batch mode, would pitch-detection objects such as helmholtz~ behave differently than in real-time?

**Comment by danomatika** [comment]
Except for some timer and threaded objects, Pd is deterministic and execution order should be the same.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by virusys** [comment]
Alright, so would I be correct in assuming that a pitch-tracking rhythm game built with a bunch of [timer] and [delay] objects would behave differently in batch mode, or are those timer objects unaffected?

**Comment by danomatika** [comment]
delay his fine and regular timer, system timer will naturally have issues. Why not try a patch with Pd’s batch mode startup flag?

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by virusys** [comment]
Alright, I'll do that. Thanks for clearing that up!

**Comment by danomatika** [comment]
I can also say I made a little C tool using libpd which reads a sound file path from the command line, plays it through bonk~, and records the output with delta times to a file. Works fine using dummy buffers and a simple while loop until a done message is received from libpd.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by virusys** [comment]
Good to know — the project I'm working on is an iOS app and my client wanted me to create an automated "batch testing" system for it (testing all the levels exhaustively with different key/speed/instrument options); if I can get the patch to run standalone (without the iOS portion of the app) then this might be feasible. Thanks again for your help!

**Comment by virusys** [comment]
> I can also say I made a little C tool using libpd which reads a sound file path from the command line, plays it through bonk~, and records the output with delta times to a file. Works fine using dummy buffers and a simple while loop until a done message is received from libpd. 

Is this code you wouldn't mind sharing? I'm having trouble figuring out how the dummy buffers + while loop should work; does the while loop just contain the system call to libpd with the -batch flag (and subsequently waits for it to finish execution?) Or am I missing something?

**Comment by danomatika** [comment]
https://github.com/libpd/libpd/blob/master/samples/c/pdtest/pdtest.c#L35

**Comment by virusys** [comment]
Amazing, thank you!

**Comment by danomatika** [comment]
>Amazing, thank you!

That's the original example from 2011-12. :P

**Comment by virusys** [comment]
Ahhhh you are right, I think I just never had the need to navigate into those folders until just now!
