### ISSUE TITLE
Import errors with Python 0.11.0

### ISSUE THREAD

**Issue by creativecontrol** [libpd/libpd#260]
I've successfully built pylibpd on both Linux and OSX, however neither are able to run the samples. Running them returns an error about missing symbols in _pylibpd.so related to canvas. 
On OSX 10.13.6 (built with Xcode) I receive the following error running test.py:

> Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from pylibpd import *
  File "/usr/local/lib/python2.7/site-packages/pylibpd.py", line 17, in <module>
    _pylibpd = swig_import_helper()
  File "/usr/local/lib/python2.7/site-packages/pylibpd.py", line 16, in swig_import_helper
    return importlib.import_module('_pylibpd')
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/_pylibpd.so, 2): Symbol not found: _canvas_triggerize
  Referenced from: /usr/local/lib/python2.7/site-packages/_pylibpd.so
  Expected in: flat namespace
 in /usr/local/lib/python2.7/site-packages/_pylibpd.so

On Linux Ubuntu Rodete I receive the following error running test.py:

> Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from pylibpd import *
  File "/usr/local/lib/python2.7/dist-packages/pylibpd.py", line 21, in <module>
    _pylibpd = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/pylibpd.py", line 20, in swig_import_helper
    return importlib.import_module('_pylibpd')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: /usr/local/lib/python2.7/dist-packages/_pylibpd.so: undefined symbol: canvas_undo_undo

**Comment by daveriedstra** [comment]
strangely, I'm getting this issue with python 3.7.3 but _not_ python 2.7.16 (tested on `master` @ b6c4d1b, `0.11.0`, and `0.10.0`, on Pop!_OS 19.04)

**Comment by danomatika** [comment]
It was missing an source file while building. Can you test again? I'm able to build a run the test.py sample.

Honestly, the python wrapper needs some serious love from a pythonista. None of the current main devs use Python very much...

**Comment by danomatika** [comment]
Also, see a little bit of work in this direction in the `update/python` branch: https://github.com/libpd/libpd/tree/update/python

*Please* feel free to add on to this. :)

**Comment by danomatika** [comment]
I've gone ahead and merged the branch. I will close this issue for now. Please re-open if the issue persists.
