### ISSUE TITLE
Python3 fix

### ISSUE THREAD

**Issue by JPfeP** [libpd/libpd#265]
Hello, 

I got the same pbm than issue #129, here with python 3.6. I found a fix by myself that allowed me after that to run successfully one of the pygame samples.

So, the pbm concern the array at the end of the pylibpd.py file in the class PdManager.  
```
    self.__outbuf = array.array('h', '\x00\x00' * outch * libpd_blocksize())
```
Just adding a 'b' seems to do the trick pretty well, you might found a better solution. I don't know if it's retro compatible with python 2. 
```
    self.__outbuf = array.array('h', b'\x00\x00' * outch * libpd_blocksize())
```

**Comment by danomatika** [comment]
Got it in latest commit. Thanks for tracking it down. This fix should be fine for Python 2.6+ & 3.
