### ISSUE TITLE
Google warning: org.puredata.core.utils.IoUtils.extractZipResource

### ISSUE THREAD

**Issue by morenhaole** [libpd/libpd#266]
I received this from google:

> Zip files can contain an entry (file or directory) having path traversal characters (“../”) in its name. If developers unzip such zip file entries without validating their name, it can potentially cause a path traversal attack, leading to writes in arbitrary directories or even overwriting the files in the app's private folders.
> 
> We recommend fixing this issue in your app by checking if canonical paths to unzipped files are underneath an expected directory. Specifically, before using a File object created using the return value of ZipEntry's getName() method, always check if the return value of File.GetCanonicalPath() belongs to the intended directory path. For example:
> 
> ~~~
> InputStream is = new InputStream(untrustedFileName);
> ZipInputStream zis = new ZipInputStream(new BufferedInputStream(is));
> while((ZipEntry ze = zis.getNextEntry()) != null) {
>   File f = new File(DIR, ze.getName());
>   String canonicalPath = f.getCanonicalPath();
>   if (!canonicalPath.startsWith(DIR)) {
>     // SecurityException
>   }
>   // Finish unzipping…
> }
> ~~~

Can you solve this problem?

**Comment by danomatika** [comment]
This seems pretty clear: the suggested fix needs to be applied to the named file: https://github.com/libpd/libpd/blob/master/java/org/puredata/core/utils/IoUtils.java

What do you think @chr15m?

**Comment by chr15m** [comment]
@danomatika the fix from @rpattabi looks like a good start. I think an unhandled SecurityException would make the app crash, which is probably better than a user getting owned because of libpd.
