### ISSUE TITLE
clone: can't create subpatch

### ISSUE THREAD

**Issue by MaurinElectroTextile** [libpd/libpd#269]
"clone: can't create subpatch"
Is there any example that use clone object ?
Do I need to add subpatch used by clone object in the main.cpp ?

Merci ;-)

**Comment by danomatika** [comment]
Is the abstraction .pd file landed by clone in the same directory as the main pd file? libpd may not be able to find it.

**Comment by virusys** [comment]
The way clone works is that you can load other patches multiple times, so for example if you had a patch “filternode.pd” outside of the main patch you’re working on, you could clone it this way:

[clone filternode.pd 100] 

Let me know if this is not clear!

-c

**Comment by danomatika** [comment]
>Is there any example that use clone object ?

If you not sure how to use [clone], right click on the object and choose "Help" in desktop Pd.

**Comment by MaurinElectroTextile** [comment]
I use to work with Puredata & clone. The patch I made using clone is working with pd Vanilla but not with libpd...

**Comment by danomatika** [comment]
We need *lots* more detail:

* Which version of libpd are you using?
* What operating system / platform are you using?
* How are you using libpd? In C, C++, C#, etc
* What does the main patch and abstraction patch look like?
* How are your patches arranged in a folder?
* How are you adding to libpd's search path (if at all)?

**Comment by MaurinElectroTextile** [comment]
libpd 0.11.0-14-ga287064 (master) 
Debian GNU/Linux 9
Using libpd in C++ 
https://github.com/eTextile/Matrix/tree/master/Software/libPd/pdtest_rtaudio

**Comment by danomatika** [comment]
I tested both [clone] and the set of patches in the project you linked with both the C and C++ `pdtest` libpd samples. Loading MAIN.pd in both samples seems to open the [clone] without issue.

**Comment by danomatika** [comment]
There is also a simple test-clone to confirm: https://github.com/libpd/libpd/commit/ba51dbc52ae247ec2878164e2aa427e9d02e0211

**Comment by MaurinElectroTextile** [comment]
OK, I got it working, I want to thank you very much for your reactivity.
Maurin

**Comment by danomatika** [comment]
How did you solve the problem?

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by MaurinElectroTextile** [comment]
I did a symbolic link in the cloned libpd repository instead of changing the libpd path in my projet. This symbolic link whas pointing the MAIN.pd file of my project located outside of the libpd framework.
