### ISSUE TITLE
PInvoke.unbind does not work with macos

### ISSUE THREAD

**Issue by fdch** [libpd/libpd#270]
Hi, is there any solution to this? I could work around this by commenting [this line ](https://github.com/libpd/libpd/blob/ba51dbc52ae247ec2878164e2aa427e9d02e0211/csharp/Managed/Binding.cs#L27)out, but I am not sure if this might generate other problems. ATM, the Unity project I made seems to work fine. 

Btw, thanks for libpd and the csharp bindings! This really turns pd patching into a whole other level of noise making!

**Comment by residuum** [comment]
This is a call to `libpd_unbind`, which is necessary to clean up the instance of libpd:

https://github.com/libpd/libpd/blob/master/csharp/Native/Messaging.cs#L45

See the section in the documentation of the C API: https://github.com/libpd/libpd/wiki/libpd#receiving-messages-from-pd

**Comment by danomatika** [comment]
Maybe add a null check before calling unbind?

**Comment by danomatika** [comment]
Any updates on this? Otherwise I could close the issue.

**Comment by fdch** [comment]
No updates on my end.

**Comment by danomatika** [comment]
Closing for now, reopen if this specific issue comes up again.
