### ISSUE TITLE
Possible to start libpd on Android without audio?

### ISSUE THREAD

**Issue by funkyfourier** [libpd/libpd#275]
Is it possible to start/use libpd on Android without initializing audio drivers? In other words, using it without OpenSL ES nor AudioTrack?

Use cases could be an app which generates audio files while not playing back anything on the speakers, or if some post processing is needed on the result of the `process` method before sending it to the speakers.

As it stands PdBase executes `PdBaseLoader.loaderHandler.load()` at creation time, which in turn initializes pdnativeopensl or pdnative. What if I want neither? Is that possible?

**Comment by simonnorberg** [comment]
You can set a custom `PdBaseLoader` before calling `PdBase`.
```java
PdBaseLoader.loaderHandler = new PdBaseLoader() {
    @Override
    public void load() {
        System.loadLibrary("pd");
    }
};
```

**Comment by funkyfourier** [comment]
Thanks, I wasn't aware of that. Will try as soon as I have a chance in a couple of days.

**Comment by danomatika** [comment]
I also added this info to the [pd-for-android wiki](https://github.com/libpd/pd-for-android/wiki/Custom-PdBaseLoader). Feel free to update/expand that wiki page.
