### ISSUE TITLE
double-precision support

### ISSUE THREAD

**Issue by umlaeute** [libpd/libpd#276]
as raised by @danomatika in https://github.com/pure-data/pure-data/pull/807, it might be a good idea to have libpd support double-precision builds of Pd properly.

**Comment by umlaeute** [comment]
afaict, libpd (the "low-level C API") will not have any problems with double-precision as is.
the `libpd_process_double` will already allow you to have full benefits of a double-precision build.
so no changes required for sample-processing!

however, the message-subsystem as exposed via libpd only offers a single-precision interface.
so you might want to add double-precision variants of the following functions, so that libpd can make *full* use of a double-precision Pd:

- `libpd_read_array`, `libpd_write_array`
- `libpd_float`
- `libpd_set_float`, `libpd_get_float`

you also might want to implement a `doublehook` (that probably should precedence over the `floathook`).

**Comment by umlaeute** [comment]
the alternative is to use `t_float` instead of explicit `float` and `double` variants.

i'm leaning towards explicit variants of the various float-functions, as i guess this would allow an application to (dynamically) link against a `libpd.so` and not having to worry whether this library was compiled with double or single precision internally.

this only works as long as the application doesn't know about `t_float`.
Currently the *libpd* API doesn't mention `t_float` at all, so (it seems that) an application can chose to be oblivious of the internal sampletype of Pd.

**Comment by danomatika** [comment]
Using t_float would probably also introduce all sorts of headaches in the language wrappers.

**Comment by danomatika** [comment]
So I've merged #310 but I'm not able to get it working so far...

A modification of the pdtest c sample which uses `libpd_process_double()` and a test patch with `[osc~ 0.1]` and prints 1/3 is not giving me output with more decimal places. Both libpd and the program are compiled with `-DPD_FLOATSIZE=64`.

**Comment by umlaeute** [comment]
i cannot reproduce.
i also modified samples/c/pdtest/pdtest.c, like this:

```C
#include <stdio.h>
#include "z_libpd.h"

void pdprint(const char *s) { ; }
void pdnoteon(int ch, int pitch, int vel) { ; }

#ifdef USE_DOUBLE
# define TYPE double
# define PROCESS libpd_process_double
#else
# define TYPE float
# define PROCESS libpd_process_float
#endif

#define print_samples(num, samples) \
        for(unsigned int i=0; i<num; i++) printf("%+f%c", samples[i], (!((i+1)%8))?'\n':'\t'); printf("\n");

int main(int argc, char **argv) {
  if (argc < 3) {
    fprintf(stderr, "usage: %s file folder\n", argv[0]);
    return -1;
  }

  int srate = 44100;
  libpd_set_printhook(pdprint);
  libpd_set_noteonhook(pdnoteon);
  libpd_init();
  libpd_init_audio(1, 2, srate);
  TYPE inbuf[64], outbuf[128];

  libpd_start_message(1);
  libpd_add_float(1.0f);
  libpd_finish_message("pd", "dsp");

  if(!libpd_openfile(argv[1], argv[2])) return -1;

  for (int i = 0; i < 10 * srate / 64; i++) {
    PROCESS(1, inbuf, outbuf);
    print_samples(sizeof(outbuf)/sizeof(*outbuf), outbuf);
  }
}
```

i ran 4 different tests:

| libpd | pdtest | 
|-------|-----------|
|`-DPD_FLOATSIZE=32` | - |
|`-DPD_FLOATSIZE=32` | `-DUSE_DOUBLE` |
|`-DPD_FLOATSIZE=32` | - |
|`-DPD_FLOATSIZE=64` | `-DUSE_DOUBLE` |

basically using this script:
```sh
#!/bin/sh
for hostflags in -DUSE_DOUBLE ""; do
  for floatsize in 32 64; do 
     hostfloat=64
     if [ "x${hostflags}" = "x" ]; then hostfloat=32; fi

     make clean
     make -C samples/c/pdtest clean
     rm libs/libpd.so samples/c/pdtest/pdtest.o samples/c/pdtest
     make -j8 CPPFLAGS="-DPD_FLOATSIZE=${floatsize}"
     make -j8 -C samples/c/pdtest CPPFLAGS="${hostflags}"

     (cd samples/c/pdtest/; ./pdtest test.pd .) > "lib${floatsize}_host${hostfloat}.txt"
  done
done
```

and then compared the numbers i got (using a python script)
the output is practically identical (of course it's not due to rounding errors).


### random thoughts
- `PD_FLOATSIZE` shouldn't do anything when compiling the host code (as it doesn't use `t_float`)
- you have to pass an array of `double` to `libpd_process_double()`
- you have to print the samples with their proper type. (i used a macro in my code so i don't have to care; but passing a `double*` to some `print_samples(float*, size_t)` function is obviously not going to work)

i know that the last two points are obvious (but i also know that *i* frequently stumble upon such things)

**Comment by danomatika** [comment]
Ok thanks for double-checking this. My first attempt failed because of wrong assumptions:
* I assumed `printf("%g", double_val);` would print with more precision but instead defaults to 6 digits, at least on my system. Using `printf("%.12f", double_val);` now shows me whether the number is being rounded or not.
* I assumed pd also applied something similar when converting numbers to string for printing (via `post()` etc) but I remember now it probably uses `sprintf("%g"...)` internally so the same default representation applies.

**Comment by danomatika** [comment]
I'm satisfied that it's working now. I added a minimal pdtest_double and clarified in the readme `PD_FLOATSIZE` is only needed when building libpd.

**Comment by joebowbeer** [comment]
[Updating](https://github.com/libpd/pd-for-android/pull/122) pd-for-android to the latest commit is failing to build:
```
In file included from /home/runner/work/pd-for-android/pd-for-android/PdCore/src/main/jni/libpd/libpd_wrapper/util/z_queued.c:11:
/home/runner/work/pd-for-android/pd-for-android/PdCore/src/main/jni/libpd/libpd_wrapper/util/z_queued.h:43:47: error: unknown type name 't_libpd_doublehook'
EXTERN void libpd_set_queued_doublehook(const t_libpd_doublehook hook);
```

Any clues @danomatika ?

**Comment by danomatika** [comment]
Cleaned after pull?

This is probably better as a separate issue.
