### ISSUE TITLE
submodule from github

### ISSUE THREAD

**Issue by umlaeute** [libpd/libpd#278]
minor nitpick, but why is the "pure-data" submodule imported from sourceforge and not from github?

i find sf to be unreliable, and it seems that the pd repo there isn't updated as regularily as the one on github...

**Comment by danomatika** [comment]
It's the canonical source and we weren't sure about how the source forge <-> GitHub mirror integration was going to work with upstream the last time I updated it.

**Comment by umlaeute** [comment]
yes, i thought so.

in the meantime i *think* it has become clearer, that SourceForge is no longer the "canonical source", and github is the primary public repository of Pure Data.

so i opened this ticket to trigger a re-evaluation of the canonical source :-)
