### ISSUE TITLE
More than 2 channel audio on Unity and libpd

### ISSUE THREAD

**Issue by fdch** [libpd/libpd#286]
Hi, we are trying libpd with Unity [as suggested here](https://github.com/playdots/UnityPd). We are on Macos Catalina. The problem sounds like sampling rate mismatch, or block size distortion, and only occurs when more than 2 channels (i.e., quad, surround 5.1, 7.1, etc) are set on both Unity and the Audio MIDI Setup. We are using a Motu interface, and everything is set to 44.1 (Pd, Unity, and macos preferences)

We tested using pd synthesis as well as a 4-channel audio playback (i.e., using [readsf~ 4]) and we have the same issue on both.

Any pointers will be highly appreciated!

Best,

**Comment by danomatika** [comment]
>only occurs when more than 2 channels (i.e., quad, surround 5.1, 7.1, etc) are set on both Unity and the Audio MIDI Setup

Sounds like a buffer size issue where pd expects 2 channels only but is getting more. This is most likely a problem with the LibPD Unity wrapper you are using which may be hard coded to stereo I/O.

**Comment by danomatika** [comment]
Any updates on this?

**Comment by fdch** [comment]
I have not worked on this for a while, so I'm closing this for now.
