### ISSUE TITLE
Can't add libpdcsharp.dll and libwinpthread-1.dll to project c# VisualStudio

### ISSUE THREAD

**Issue by BenReg** [libpd/libpd#289]
Hello,

I have some trouble with libpdbinding on Visual Studio.
I've downloaded the Nuget Package and I can find the libpdcsharp.dll and the libwinpthread.dll files.
But I can't add them to my project.
When I try to add them with "add a reference" I get this error : "a reference to [...] could not be added. Please make sure that the file is accesible and that it is a valid assembly or COM component.".
I tried other stuff like "DLLImport" but nothing worked.
I just can add the files to my project with "add an existing file" and set their properties to "Copy if newer" but that's all. I don't have access to any of the methods or objects of the library.

Thanks,

**Comment by danomatika** [comment]
You shouldn't need to add them to the VS project itself, only place them in the same folder as your executable so it can find and load them.

Closing for now.
