### ISSUE TITLE
Handling sample rate changes

### ISSUE THREAD

**Issue by amethystdeceiver** [libpd/libpd#290]
I'm using the low-level C API in my app. What would be the right way to forward an external sample rate change to libpd? Is calling `libpd_init_audio()` with the new rate enough? Or do I have to restart anything?

Thanks!

**Comment by danomatika** [comment]
>Is calling libpd_init_audio() with the new rate enough?

Yes.

**Comment by amethystdeceiver** [comment]
Great, thanks! 👍
