### ISSUE TITLE
Does the PdDispatcher work in macOS?

### ISSUE THREAD

**Issue by gorborukov** [libpd/libpd#294]
I set up PdDispatcher, opened patch file with PdBase, send the float to start metro, but after turning on in the console I see only a single new bang instead of a series of bangs that should be received from the patch. Maybe I do not understand the purpose of the dispatcher correctly? I would be grateful for any help or clarification.

```
class ViewController: NSViewController, PdListener {
    @IBOutlet weak var onOffSwitch: NSSwitch!
    let dispatcher = PdDispatcher()

    override func viewDidLoad() {
        super.viewDidLoad()
        dispatcher.add(self, forSource: "track1")
        PdBase.setDelegate(dispatcher)
        PdBase.openFile("patch.pd", path: Bundle.main.resourcePath!)
        
    }

    @IBAction func onOffSwitchToggled(_ sender: NSSwitch) {
        PdBase.send(sender.floatValue, toReceiver: "toggle")
    }

    func receiveBang(fromSource source: String!) {
        if source == "track1" {
            print("bang")
        }
    }
}
```

**XCode 11.4, macOS 10.15.4**

![patch](https://user-images.githubusercontent.com/2666067/80897644-a1f7a080-8d03-11ea-9b66-83155a93c6d6.png)

**Comment by danomatika** [comment]
Did you turn on Pd's DSP? If not, the metro won't run, hence no bangs.

**Comment by danomatika** [comment]
Also, does it work with PdListener instead of PdDispatcher. PdDispatcher is a convenience class for using PdListener. In using PdListener, you would just need to manually subscribe to the "track1" source with PdBase.

**Comment by gorborukov** [comment]
Same result with PdListener subscription. Also I added ; pd dsp $ message to patch, but this didn't produce the expected result. Perhaps the fact is that I do not use any audio handling (portaudio or something that works in macOS) because I planned to work only with messages without sound and the metro doesn't work for this reason?

**Comment by danomatika** [comment]
You have to run one of the process functions for messages to be handled. You can make a dummy buffer and simply run it in your main loop periodically or in a timer or display sync thread, etc.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by danomatika** [comment]
Note: Many of the code samples do this, ie. the basic C pdtest runs Pd in a loop with a dummy buffer: https://github.com/libpd/libpd/blob/master/samples/c/pdtest/pdtest.c#L35

**Comment by gorborukov** [comment]
Thank you @danomatika ! I implemented this with display link and by calling libpd_wrapper functions directly: 

```
override func viewDidLoad() {
        ...
        PdBase.initialize()
        libpd_init_audio(1, 2, 44100)
        ...
        displayLink = NSUIDisplayLink(target: self, selector: #selector(processBuffer))
        displayLink!.add(to: .current, forMode: .common)
    }

func processBuffer() {
	libpd_process_float(1, UnsafeMutablePointer<Float>.allocate(capacity: 64), UnsafeMutablePointer<Float>.allocate(capacity: 128))
}
```

but it seems that metro moving in slower tempo than it should. Perhaps i should increase the values of ticks/input buffer/output buffer.

**Comment by danomatika** [comment]
I would avoid allocating on every call as it is slow. I would allocate once during setup and save the buffers as instance variables.

**Comment by gorborukov** [comment]
Yes, this is good advice, I will do so. Thanks.
