### ISSUE TITLE
msys compilation fails

### ISSUE THREAD

**Issue by mxa** [libpd/libpd#295]
I've followed the instructions to the letter and even found out how to [navigate the directory](https://stackoverflow.com/questions/11376899/browsing-folders-in-msys) in msys2 but I'm getting the following error when trying to compile:

```
make ADDITIONAL_CFLAGS='-DPD_LONGINTTYPE="long long"'
/bin/sh: cc: command not found
/bin/sh: cc: command not found
cc -DPD -DHAVE_UNISTD_H -DUSEAPI_DUMMY -I./libpd_wrapper -I./libpd_wrapper/util -I./pure-data/src -DWINVER=0x502 -DWIN32 -D_WIN32 -DPD_INTERNAL -I"/include" -I"/include/win32" -ffast-math -funroll-loops -fomit-frame-pointer -O3 -DLIBPD_EXTRA   -DPD_LONGINTTYPE="long long"   -c -o libpd_wrapper/util/z_print_util.o libpd_wrapper/util/z_print_util.c
/bin/sh: cc: command not found
make: *** [<builtin>: libpd_wrapper/util/z_print_util.o] Error 127

```

**Comment by danomatika** [comment]
You need to run the Msys MinGW console, not regular cmd.exe.

See this long thread: https://github.com/danomatika/ofxPd/issues/77#issuecomment-607166438

**Comment by mxa** [comment]
I think that's where I am.

![image](https://user-images.githubusercontent.com/1220707/82094825-1bc55c00-96fe-11ea-8ea4-26a0f0ed8037.png)

**Comment by danomatika** [comment]
Actually, look here: https://github.com/danomatika/ofxPd/issues/77#issuecomment-609635112

**Comment by mxa** [comment]
Are you referring to the incomplete MSYS installation? That's not the case.

```
gmu@DESKTOP-GOD8M5S MSYS /c/Users/gmu/My Documents/libpd
$ pacman -Syu
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
 there is nothing to do

gmu@DESKTOP-GOD8M5S MSYS /c/Users/gmu/My Documents/libpd
$ pacman -Su
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
 there is nothing to do
```

**Comment by danomatika** [comment]
I'm reporting what someone who seemingly had the same issue did to make it work. I can;t really debug it beyond there. Ask @Spacechild1.

**Comment by mxa** [comment]
Thanks anyway

**Comment by danomatika** [comment]
Also, note that it's important which shell you use, 32 or 64 bit as it needs to align with the compiler chain you installed, also 32 or 64 bit.

**Comment by mxa** [comment]
actually closing and re-opening MSYS2 seems to have fixed that. doh.

**Comment by danomatika** [comment]
That makes sense. Packages may have been installed that added themselves to the bin path, but you don't actually hav that in your environment until you reload it. It's similar to editing your `.bash_profile` and needing to reload it with `source ~/.bash_profle`.

I will add another note about doing this.

**Comment by danomatika** [comment]
Ok, hopefully this will help: f0a550795d2ac52fe4f47b397c036711af096c5f
