### ISSUE TITLE
[paid] Developer wanted: libpd backend for VCV Prototype

### ISSUE THREAD

**Issue by AndrewBelt** [libpd/libpd#298]
See https://community.vcvrack.com/t/developer-wanted-for-next-fundraiser-libpd-backend-for-vcv-prototype/10175 for a full description. Email contact@vcvrack.com to adopt this project and discuss funding.

**Comment by mxa** [comment]
Almost done. I think this issue may be closed.

**Comment by AndrewBelt** [comment]
Oh yes, I forgot to close this issue. Thanks to everyone who responded and congratulations Max and Clemens for successful funding!
