### ISSUE TITLE
python + libpd problem

### ISSUE THREAD

**Issue by iohanna** [libpd/libpd#30]
Hi everybody,

I tried to get libpd working in python. After some initial problems, the test.py works with python 2.7 (3.3 gives me syntax errors).  Also pygame_fun_test.py works fine.... However, when I try to run the echo.py example I get an error message. The message looks like this:

Python 2.7.3 (v2.7.3:70274d53c1dd, Apr  9 2012, 20:52:43) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "copyright", "credits" or "license()" for more information.
>>> ================================ RESTART ================================
>>> 

Traceback (most recent call last):
  File "/libpd-master/python/echo.py", line 24, in <module>
    data = stream.read(bs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyaudio.py", line 605, in read
    return pa.read_stream(self._stream, num_frames)
IOError: [Errno Input overflowed] -9981
>>> ================================ RESTART ================================
>>> 

Does anybody have an idea where this error comes from? I would be also interesting to hear more about setups which have been used successfully. I am on a Mac (OS X 10.8), using python 2.7 from python.org.

Thank you so much!
Best regards,
iohanna

**Comment by ktatar** [comment]
Deleting pulseaudio solved my problem. I still get errors but dropouts are fixed.
sudo apt-get --purge remove pulseaudio

**Comment by danomatika** [comment]
That's a little extreme? Did you try pasuspender first?

**Comment by ktatar** [comment]
Yes, it didn't work.
