### ISSUE TITLE
libpd website is no more?

### ISSUE THREAD

**Issue by mxa** [libpd/libpd#301]
Here: https://github.com/libpd/libpd and here: https://github.com/libpd
the website libpd.cc is prominently featured, but looking at it it seems it is no longer related to libpd.

**Comment by danomatika** [comment]
@nettoyeurny Is the domain dead?

**Comment by nettoyeurny** [comment]
I think Peter Kirn set up the website.

Peter, any idea what happened to libpd.cc?

**Comment by mxa** [comment]
@peterkirn

**Comment by danomatika** [comment]
One option is to use GitHub pages and host here with a possible redirect from libpd.cc if someone buys it. Is the original page source available somewhere? If no one has int or wants to make a new page, I'm fine with just changing all the documentation to point here.

**Comment by mxa** [comment]
This is the last working crawl from archive.org's waybackmachine https://web.archive.org/web/20190702143211/http://libpd.cc/

**Comment by peterkirn** [comment]
Hi everyone - I think I failed to hit reply all somewhere in this thread.

So the usual problem, couldn't pay a domain bill, missed a registration on
a weird registrar, now someone has parked it.

Oddly though libpd.org has become available which may make more sense,
apart from some 'legacy' references to the old domain. But as far as
restoring the site itself; that's easier.

Peter

**Comment by danomatika** [comment]
libpd.xyz and libpd.me are cheaper :)

**Comment by danomatika** [comment]
I've removed the references to libpd.cc for now, both in the readme and in the organization and repo info.

**Comment by danomatika** [comment]
I would be open to registering a new domain to reupload the original site, however I don't see myself updating it. Who was updating it before? If no one wants to maintain it, then it's perhaps better to convert it to a static page for hosting the book with some of the original content and links back to here.

**Comment by danomatika** [comment]
Ping @umlaeute.

**Comment by mxa** [comment]
A GitHub.io page might be the cheapest and easiest to keep up to date.

**Comment by danomatika** [comment]
> A GitHub.io page might be the cheapest and easiest to keep up to date.

...but also further dependent on GitHub.

**Comment by mxa** [comment]
Right, but if libpd.cc has tought us anything, then that it is at least as risky to put a community member in charge of registering and remering to renew a domain and hosting, compared to trusting Microsoft to provide GitHub.io for the foreseeable future.

**Comment by danomatika** [comment]
> compared to trusting Microsoft to provide GitHub.io for the foreseeable future.

... or asking IEM to co-host along with puredata.info or integrate into puredata.info?

Also, we are all members of the community.

**Comment by umlaeute** [comment]
I can certainly setup https://libpd.puredata.info/ (and point it to wherever, if that is required; we could probably even use GitHub.io for the actual hosting for now - as long as "the community" is in control of the domain)

**Comment by danomatika** [comment]
In case y'all were wondering: I am too lazy/busy to do this. Github is fine for me. Reopen if you want to take it on.

**Comment by mxa** [comment]
I guess the issue has been fixed by removing the reference. What was on that page anyways? Is it backed up anywhere? Is it worth preserving? Possibly using g github pages?

**Comment by peterkirn** [comment]
Hi - the answer is: not much was there. I have a backup but it's outdated
anyway; too much changed with libpd and it had a showcase of examples that
would have needed updating. Basically I screwed up a domain renewal because
it came up at some exorbitant price and I lost the domain when I couldn't
afford it. If someone wanted this to happen again with a redesign, I'd be
up for it. But it seems GitHub is the place for now!

**Comment by danomatika** [comment]
> But it seems GitHub is the place for now!

Well, this could be something to fold back into predate.info but I won't be doing it. My bandwidth is only wide enough to try to keep tracked releases with pure-data upstream and those maintenance changes needed for my own projects which use libpd. Maintaining community, keeping info and a collection of various projects up to date is not something I can do, realistically.
