### ISSUE TITLE
libpd compile fails with Pd 0.51

### ISSUE THREAD

**Issue by mxa** [libpd/libpd#303]
It works with 0.50-2, but 0.51 will just quit, no error message shown.

**Comment by Spacechild1** [comment]
sorry, but where did you get Pd 0.52? ;-)

**Comment by mxa** [comment]
oops, subtract 1 each

**Comment by mxa** [comment]
Writing from the future! :)

**Comment by Spacechild1** [comment]
https://github.com/libpd/libpd/pull/299

**Comment by danomatika** [comment]
Closed via 2a998693de11c2060cf6d184223eaceab2ad05fe
