### ISSUE TITLE
Recursive variable CFLAGS installing pylibpd in OSX 10.13

### ISSUE THREAD

**Issue by xaviliz** [libpd/libpd#313]
Hi everyone, 

I was trying to install pylibpd in my python system but I got always the same error:

`Makefile:9: *** Recursive variable `CFLAGS' references itself (eventually).  Stop.`

My OSX is a little bit old (10.13.6) and I am have not experience with Makefiles. 
However I have modified `=` to `:=` and it was solved.

Thanks for your dedication,
XL

**Comment by danomatika** [comment]
Good catch, indeed a bug. The current `master` branch has this fix and I also updated the python bindings a bit.

**Comment by xaviliz** [comment]
Thanks @danomatika 

I got a new issue building in python3,

`make PYTHON=python3
python3 setup.py build
running build
running build_py
file pylibpd.py (for module pylibpd) not found
file pylibpd.py (for module pylibpd) not found
running build_ext
building '_pylibpd' extension
swigging pylibpd.i to pylibpd_wrap.c
swig -python -o pylibpd_wrap.c pylibpd.i
unable to execute 'swig': No such file or directory
error: command 'swig' failed with exit status 1
make: *** [build] Error 1`

I was trying to install swig but not sure how to do it yet. 
Is there any workaround?

**Comment by danomatika** [comment]
You can install swig via homebrew. It is currently required.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by xaviliz** [comment]
Thanks! I got a new issue including m_pd.h:

> swig -python -o pylibpd_wrap.c pylibpd.i
> creating build/temp.macosx-10.13-intel-2.7
> cc -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -fcommon -Wno-unused-variable -Wno-unused-function -Wno-unused-label -arch i386 -arch x86_64 -pipe -DPD=1 -DHAVE_UNISTD_H=1 -DHAVE_LIBDL=1 -DUSEAPI_DUMMY=1 -DLIBPD_EXTRA=1 -I../libpd_wrapper -I../pure-data/src -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c pylibpd_wrap.c -o build/temp.macosx-10.13-intel-2.7/pylibpd_wrap.o
> In file included from pylibpd_wrap.c:3048:
> ../libpd_wrapper/z_libpd.h:20:10: fatal error: 'm_pd.h' file not found
> #include "m_pd.h"
>          ^~~~~~~~
> 1 error generated.
> error: command 'cc' failed with exit status 1
> make: *** [build] Error 1

**Comment by danomatika** [comment]
Did you checkout the pure-data submodule as outlined [in the README](https://github.com/libpd/libpd#getting-libpd)? If you `libpd/pure-data` directory is empty, you need to do this step.

**Comment by xaviliz** [comment]
Nope, thanks to pointing it out :)

It solved it, however I only can build the python module wrapper at the master branch. In 0.8.3 branch I got the following error:

>       (aka 'float *(void)') [-Wincompatible-pointer-types]
>   for (p = sys_soundout, i = 0; i < n_out; i++) {
>          ^ ~~~~~~~~~~~~
> ../libpd_wrapper/z_libpd.c:181:3: error: use of undeclared identifier
>       'sys_soundin'
>   PROCESS(* short_to_sample, * sample_to_short)
>   ^
> ../libpd_wrapper/z_libpd.c:165:22: note: expanded from macro 'PROCESS'
>     for (j = 0, p0 = sys_soundin; j < DEFDACBLKSIZE; j++, p0++) { \
>                      ^
> ../libpd_wrapper/z_libpd.c:181:3: error: use of undeclared identifier
>       'sys_inchannels'; did you mean 'sys_get_inchannels'?
> ../libpd_wrapper/z_libpd.c:166:32: note: expanded from macro 'PROCESS'
>       for (k = 0, p1 = p0; k < sys_inchannels; k++, p1 += DEFDACBLKSIZE) { \
>                                ^
> ../pure-data/src/m_pd.h:607:12: note: 'sys_get_inchannels' declared here
> EXTERN int sys_get_inchannels(void);
>            ^
> ../libpd_wrapper/z_libpd.c:181:3: warning: ordered comparison between pointer
>       and integer ('int' and 'int (*)(void)')
>   PROCESS(* short_to_sample, * sample_to_short)
>   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../libpd_wrapper/z_libpd.c:166:30: note: expanded from macro 'PROCESS'
>       for (k = 0, p1 = p0; k < sys_inchannels; k++, p1 += DEFDACBLKSIZE) { \
>                            ~ ^ ~~~~~~~~~~~~~~
> fatal error: too many errors emitted, stopping now [-ferror-limit=]
> 12 warnings and 20 errors generated.
> error: command 'cc' failed with exit status 1
> make: *** [build] Error 1

Unfortunately, I only can recover a part of the log error. I should increase my history buffer.

**Comment by danomatika** [comment]
Why do you need the 0.8.3 branch? The errors look like a mismatch between the pure-data version which is checked out and the libpd version. When you checkout a libpd branch, it usually also changes the pure-data submodule to a different commit as well. It looks like you may have switched before init pure-data and it's in the wrong state.

Anyway, if it works in master, fine. The master bring will soon be the new libpd 0.12 release.

**Comment by xaviliz** [comment]
init pure-data? Do you mean `git submodule update --init --recursive`?

**Comment by xaviliz** [comment]
ok, it is working. Thanks again. 
After checking out I have updated the submodules manually and it was solved.

After adapting printing commands, I have found some errors in `samples/python/test.py` reading a float array:

> python3 test.py
> received: ('print: bang\n',)
> received: (6, 63, 0)
> $0:  1003
> received: ('print: 42\n',)
> received: ('eggs', 42.0)
> received: ('print: symbol',)
> received: (' ',)
> received: ("don't\\ panic",)
> received: ('\n',)
> received: ('eggs', "don't panic")
> received: ('print: list',)
> received: (' ',)
> received: ('test',)
> received: (' ',)
> received: ('1',)
> received: (' ',)
> received: ('foo',)
> received: (' ',)
> received: ('2',)
> received: ('\n',)
> received: ('eggs', 'test', 1.0, 'foo', 2.0)
> array size: 64
> array size: -1
> Traceback (most recent call last):
>   File "test.py", line 27, in <module>
>     print(libpd_read_array(buf, "array1", 0, 64))
>   File "/usr/local/lib/python3.7/site-packages/pylibpd.py", line 111, in libpd_read_array
>     return _pylibpd.libpd_read_array(dest, name, offset, n)
> TypeError: in method 'libpd_read_array', argument 1 of type 'float *'

**Comment by danomatika** [comment]
If you are changing libpd and pure-data commits, you also have to clean and rebuild the python wrapper:

~~~
cd python
make clean clobber
make
~~~

**Comment by xaviliz** [comment]
yes, that's it. Now is building properly. 

I have modified a little bit pylibpd.py,  to be run in python3.7

> File "/usr/local/lib/python3.7/site-packages/pylibpd.py", line 243, in libpd_subscribe
>     if not __libpd_subscriptions.has_key(sym):
> AttributeError: 'dict' object has no attribute 'has_key'

Python2.7:
`if not __libpd_subscriptions.haskey(sym):`

Python3:
`if sym not in __libpd_subscriptions:`

> File "/usr/local/lib/python3.7/site-packages/pylibpd.py", line 264, in __init__
>     self.__outbuf = array.array('h', '\x00\x00' * outch * libpd_blocksize())
> TypeError: cannot use a str to initialize an array with typecode 'h'

Python2.7:
`self.__outbuf = array.array(‘h’, '\x00\x00' * outch * libpd_    blocksize())`

Python3:
`self.__outbuf = array.array('b', '\x00\x00'.encode() * outch * libpd_    blocksize())`

> python3 test.py
> received: ('print: bang\n',)
> received: (6, 63, 0)
> $0:  1003
> received: ('print: 42\n',)
> received: ('eggs', 42.0)
> received: ('print: symbol',)
> received: (' ',)
> received: ("don't panic",)
> received: ('\n',)
> received: ('eggs', "don't panic")
> received: ('print: list',)
> received: (' ',)
> received: ('test',)
> received: (' ',)
> received: ('1',)
> received: (' ',)
> received: ('foo',)
> received: (' ',)
> received: ('2',)
> received: ('\n',)
> received: ('eggs', 'test', 1.0, 'foo', 2.0)
> array size: 64
> array size: -1
> 0
> array('f', [0.0428570993244648, 0.0857141986489296, 0.21428599953651428, 0.2571429908275604, 0.2857140004634857, 0.32857099175453186, 0.3714280128479004, 0.4428569972515106, 0.48571398854255676, 0.6285709738731384, 0.6999989748001099, 0.7571420073509216, 0.7857130169868469, 0.8142849802970886, 0.8571419715881348, 0.8857129812240601, 0.8857129812240601, 0.8857129812240601, 0.8714280128479004, 0.8571419715881348, 0.7999989986419678, 0.7714279890060425, 0.7285709977149963, 0.6571419835090637, 0.5999990105628967, 0.5285710096359253, 0.2857140004634857, -0.0714287981390953, -0.32857099175453186, -0.4428569972515106, -0.5285710096359253, -0.6000000238418579, -0.6571419835090637, -0.7142850160598755, -0.7142850160598755, -0.7142850160598755, -0.7142850160598755, -0.6857140064239502, -0.042857199907302856, 0.08571410179138184, 0.22857099771499634, 0.25714200735092163, 0.2857140004634857, 0.41428500413894653, 0.4571419954299927, 0.5428569912910461, 0.5857139825820923, 0.5999990105628967, 0.6142849922180176, 0.6285709738731384, 0.6428560018539429, 0.6571419835090637, 0.6571419835090637, 0.6571419835090637, 0.6428560018539429, 0.5999990105628967, 0.5571420192718506, 0.5142850279808044, 0.2857140004634857, 0.11428599804639816, 0.028571300208568573, -0.02857149951159954, -0.08571430295705795, -0.2714279890060425])
> array('b', [0, 0, 124, 5, 3, 0, -8, 10, 6, 0, 109, 27, 9, 0, -23, 32, 12, 0, -111, 36, 15, 0, 14, 42, 18, 0, -118, 47, 21, 0, -81, 56, 24, 0, 43, 62, 27, 0, 116, 80, 30, 0, -104, 89, 33, 0, -23, 96, 36, 0, -111, 100, 39, 0, 57, 104, 42, 0, -75, 109, 45, 0, 94, 113, 48, 0, 94, 113, 51, 0, 94, 113, 54, 0, -118, 111, 57, 0, -75, 109, 60, 0, 101, 102, 63, 0, -67, 98, 66, 0, 65, 93, 69, 0, 28, 84, 72, 0, -52, 76, 75, 0, -89, 67, 78, 0, -111, 36, 81, 0, -36, -10, 84, 0, -14, -43, 87, 0, 81, -57, 90, 0, 89, -68, 93, 0, 52, -77, 96, 0, -28, -85, 99, 0, -108, -92, 102, 0, -108, -92, 105, 0, -108, -92, 108, 0, -108, -92, 111, 0, 60, -88, 114, 0, -124, -6, 117, 0, -8, 10, 120, 0, 65, 29, 123, 0, -23, 32, 126, 0, -111, 36, -127, 0, 6, 53, -124, 0, -125, 58, -121, 0, 123, 69, -118, 0, -8, 74, -115, 0, -52, 76, -112, 0, -96, 78, -109, 0, 116, 80, -106, 0, 72, 82, -103, 0, 28, 84, -100, 0, 28, 84, -97, 0, 28, 84, -94, 0, 72, 82, -91, 0, -52, 76, -88, 0, 79, 71, -85, 0, -45, 65, -82, 0, -111, 36, -79, 0, -96, 14, -76, 0, -88, 3, -73, 0, 88, -4, -70, 0, 8, -11, -67, 0, 67, -35])
> 0
> array('b', [0, 0, 0, 0, 3, 0, -1, 1, 6, 0, -1, 3, 9, 0, -1, 5, 12, 0, -1, 7, 15, 0, -1, 9, 18, 0, -1, 11, 21, 0, -1, 13, 24, 0, -1, 15, 27, 0, -1, 17, 30, 0, -1, 19, 33, 0, -1, 21, 36, 0, -1, 23, 39, 0, -1, 25, 42, 0, -1, 27, 45, 0, -1, 29, 48, 0, -1, 31, 51, 0, -1, 33, 54, 0, -1, 35, 57, 0, -1, 37, 60, 0, -1, 39, 63, 0, -1, 41, 66, 0, -1, 43, 69, 0, -1, 45, 72, 0, -1, 47, 75, 0, -1, 49, 78, 0, -1, 51, 81, 0, -1, 53, 84, 0, -1, 55, 87, 0, -1, 57, 90, 0, -1, 59, 93, 0, -1, 61, 96, 0, -1, 63, 99, 0, -1, 65, 102, 0, -1, 67, 105, 0, -1, 69, 108, 0, -1, 71, 111, 0, -1, 73, 114, 0, -1, 75, 117, 0, -1, 77, 120, 0, -1, 79, 123, 0, -1, 81, 126, 0, -1, 83, -127, 0, -1, 85, -124, 0, -1, 87, -121, 0, -1, 89, -118, 0, -1, 91, -115, 0, -1, 93, -112, 0, -1, 95, -109, 0, -1, 97, -106, 0, -1, 99, -103, 0, -1, 101, -100, 0, -1, 103, -97, 0, -1, 105, -94, 0, -1, 107, -91, 0, -1, 109, -88, 0, -1, 111, -85, 0, -1, 113, -82, 0, -1, 115, -79, 0, -1, 117, -76, 0, -1, 119, -73, 0, -1, 121, -70, 0, -1, 123, -67, 0, -1, 125])

**Comment by danomatika** [comment]
Thanks. I am updating the python wrapper for python3 and your changes are working, but I am seeing the following with python 3.9:

~~~
Traceback (most recent call last):
  File "/Users/dano/src/pd/libpd/samples/python/test.py", line 26, in <module>
    print(libpd_read_array(buf, "array1", 0, 64))
  File "/Users/dano/src/pd/libpd/samples/python/venv/lib/python3.9/site-packages/pylibpd.py", line 111, in libpd_read_array
    return _pylibpd.libpd_read_array(dest, name, offset, n)
TypeError: in method 'libpd_read_array', argument 1 of type 'float *'
~~~

Any thoughts?

**Comment by danomatika** [comment]
(reopen for now until Python 3 support is working.)

**Comment by danomatika** [comment]
Ok, the wrapper and examples now all support Python 3. There is also a Makefile "uninstall" target to remove those files install via `make install`.

The pygame examples both run but something is wrong with the sound. All other examples work for me.

**Comment by xaviliz** [comment]
@danomatika sorry, I was out for some days. I got that error but with your last suggestions it was solved. Good if you fixed I don't know exactly why the error disappeared. I will test the pygame examples later, but for me was working too ;)

**Comment by danomatika** [comment]
I'm going to close this for now as the build and examples are, more or less, working.
