### ISSUE TITLE
Python 3 pygame sample updates 

### ISSUE THREAD

**Issue by danomatika** [libpd/libpd#314]
@chr15m If you have time, can you check the pygame_test and pygame_fun_test samples?

I've updated the wrapper and other samples to Python 3 and they are working again. The pygame examples are ok syntax-wise but sound is bad and I wonder if the loops or sample buffer array handling is slightly off and sound is garbled.

**Comment by chr15m** [comment]
@danomatika just a quick update to let you know I tried to get this installed on my local and ran into issues which I have not yet had time to go back and look at. If somebody else who is more up to date with this stuff wants to jump in and fix this it will get done faster.

**Comment by danomatika** [comment]
Unless anyone else gets to this, I'm going to assume it's working and leave it as is.

**Comment by nuromantix** [comment]
This still seems to be a problem. Very quiet & garbled audio.

**Comment by danomatika** [comment]
Ok, reopening. It would be nice if someone can look into this, otherwise we can remove the example if it's _permabroken_.

**Comment by nuromantix** [comment]
My friend has made a working example using callbacks and pyaudio.
Apparently the pyaudio API has changed quite a bit.
Here it is:
https://github.com/jkammerl/pylibpd_pyaudio/blob/main/pd_callback_example.py

**Comment by danomatika** [comment]
Cool. If he has time, maybe he can make a PR to this repo with fixes for the `samples/python/pygame_test.py` and `samples/python/pygame_fun_test.py`. That would be helpful.

**Comment by danomatika** [comment]
I *think* this is working better now (there have been some python updates). If not, please reopen.
