### ISSUE TITLE
libpd in cocoapods from github xcode errors

### ISSUE THREAD

**Issue by davidplans** [libpd/libpd#318]
On building with 0.11 libpd github version from cocoapods in code 12.2 (and 11.3.1), errors for the following externals occur on build:

`Undefined symbols for architecture arm64:
  "_bonk_tilde_setup", referenced from:
      _libpd_init in z_libpd.o
  "_fiddle_tilde_setup", referenced from:
      _libpd_init in z_libpd.o
  "_loop_tilde_setup", referenced from:
      _libpd_init in z_libpd.o
  "_lrshift_tilde_setup", referenced from:
      _libpd_init in z_libpd.o
  "_bob_tilde_setup", referenced from:
      _libpd_init in z_libpd.o
  "_sigmund_tilde_setup", referenced from:
      _libpd_init in z_libpd.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

...if one updates to 0.12 by installing latest using `pod 'libpd', :git => 'https://github.com/libpd/libpd', :submodules => true`, the following errors happen instead regarding binarymsg.c on trying to build the libpd pod. Beginning with 'Unknown type name 'FILE' in line 11, etc.

Any ideas?

**Comment by danomatika** [comment]
`binarymsg.c` should be excluded from the build as it is included directly in the pd~ source files.

**Comment by danomatika** [comment]
Try 28ed5a6886aca2699692e5ef5731be5200896f46.

**Comment by davidplans** [comment]
Hi! Sorry to be daft but `28ed5a6` looks a little like you added, not removed, binarymsg.c? On building with that commit, I still get:

`/Users/david/Development/EPDPMasterTemplate/epdpMasterTemplate/Pods/libpd/pure-data/extra/pd~/pdsched.c:22:10: 'binarymsg.c' file not found
/Users/david/Development/EPDPMasterTemplate/epdpMasterTemplate/Pods/libpd/pure-data/extra/pd~/pd~.c:127:10: 'binarymsg.c' file not found`

**Comment by danomatika** [comment]
I added the file to the `spec.exclude_files` list, so I assume that "removes" it as far as CocoaPods is concerned.

I don't use CocoaPods very often, but I imagine you probably have to regenerate the project files, clean, & rebuild for the change to take effect. If you want to do it manually, find whichever generated Xcode project has `binarymsg.c` and remove the file form the project, usually by selecting it in the left-side project tree and pressing delete.

**Comment by davidplans** [comment]
You're right of course in that clean&rebuild at least got binarymsg.c out of the works...however, xcode still seems to think it's needed by these guys:

`/Users/david/Development/EPDPMasterTemplate/epdpMasterTemplate/Pods/libpd/pure-data/extra/pd~/pd~.c:127:10: 'binarymsg.c' file not found
/Users/david/Development/EPDPMasterTemplate/epdpMasterTemplate/Pods/libpd/pure-data/extra/pd~/pdsched.c:22:10: 'binarymsg.c' file not found`

**Comment by danomatika** [comment]
Yes, it’s still needed to build libpd, it just doesn’t need to be built directly by the compiler.

Check the CocoaPods documentation. Perhaps there is something else other than the exclude list to put the file in the pod file:

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by danomatika** [comment]
This should be fixed with libpd 0.12.1. The answer is to *not* include binarymsg.c in the podspec `sources_list` but make sure it's downloaded with `preserve_paths`.

Please test and reopen if the issue persists.

**Comment by davidplans** [comment]
Confirmed! 12.1 fixes the issue. Thank you @danomatika !
