### ISSUE TITLE
undefined symbols for arm64 Xcode 12

### ISSUE THREAD

**Issue by d01101010m** [libpd/libpd#328]
I get this error in Xcode 12 whether I start a new project and add libpd or if I try to compile one of the pd-for-ios projects: 

Undefined symbols for architecture arm64:
  "_pd_tilde_setup", referenced from:
      _libpd_init in libpd-ios.a(z_libpd.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by d01101010m** [comment]
I've tried every combination of linker settings in Xcode for libpd and my project. Sometimes it says x86_64 and sometimes it says arm64. I have the correct architectures selected for libpd and my project and I've linked my binary to libpd under the "build phases" tab. Still get the same error.

**Comment by michaelpace** [comment]
@d01101010m, have you had any luck with this? I'm running into the same issue on Xcode 11.2.

**Comment by danomatika** [comment]
Note: The pd-for-ios projects are not always updated, so no real guarantee that they will "just build." (It would be nice if more people would maintain them.)

What steps are being used to set up a project to build with libpd? The libpd.xcodeproj should build for both arm64 and x86_64 on macOS. I can at least say that I am using it successfully for universal builds of an application.

**Comment by danomatika** [comment]
Ok, nothing big here. The libpd.xcodeproj is missing the pd~ folder in extra.

**Comment by danomatika** [comment]
This should be fixed in latest commits. New bugfix version now: 0.12.2.

**Comment by danomatika** [comment]
Tested build with samples/objc/ios/pdtest project on macOS 11 with Xcode 12.5. Reopen if needed.
