### ISSUE TITLE
Accessing errors

### ISSUE THREAD

**Issue by tgujar** [libpd/libpd#330]
Is there a way in libpd to access errors generated while running a patch.

For example if I connect a message say "hello" to a float object. [Patch image](https://imgur.com/j9CDSIL)
When I actually send "hello" to the send object while running, I would get an error in the pd console saying:
**error: float: no method for 'hello'**

Is it possible to access these kind of messages using the interface provided by libpd.

I am using CPP and running pd on Debian.

**Comment by danomatika** [comment]
No. Errors are simply messages sent to the console with a different level but libpd makes no distinction between lines.

**Comment by tgujar** [comment]
Thank you for the quick response!

**Comment by danomatika** [comment]
I would also add that it may be useful in the future to be able to handle the log levels more directly, possibly by alternate hooks, but we are not there yet.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by tgujar** [comment]
Yup that would be great! I'll use a workaround for now :p
