### ISSUE TITLE
Trouble with pd Internal messages

### ISSUE THREAD

**Issue by tgujar** [libpd/libpd#331]
I am trying to use [pd Internal messages](https://puredata.info/community/pdwiki/PdInternalMessages) to make changes to the file dynamically using libpd.

Currently the contents of the file are as shown [in this image](https://imgur.com/Hlf4bcA).

I am sending the messages using the `sendMessage` method defined in `PdBase`. I am able to view that the messages are indeed reaching the patch by using an overriden version of `receiveMessages` such that it prints directly to stdout.
Like so:
```
vector<string> s = {"msg 10 10 bang", "floatatom 100 10 7 50 5000", "menusave"}; 

	for (vector<string>::iterator i = s.begin(); i != s.end(); i++) {
		pd.sendMessage("maker", *i);
		pd.receiveMessages();
	}
```
The expected behaviour should be the same as when I click on the `msg 10 10 bang` msg object as shown in the image, which leads to creation of a msg object containing the text "bang" at position (10, 10) in the file `test.pd`(which is also the current active file). I have tested this in the GUI.

However, using libpd to directly send messages(as mentioned above) to the `maker` receiver leads to errors as shown in the attached output.
```
Patch: "test.pd" $0: 1003 valid: 1
pd 0.51.4
bonk version 1.5
fiddle version 1.1 TEST4
pd~ version 0.54
pique 0.1 for PD version 23
sigmund~ version 0.07
print: msg 10 10 bang
error: canvas: no method for 'msg 10 10 bang'
verbose(4): ... you might be able to track this down from the Find menu.
print: floatatom 100 10 7 50 5000
error: canvas: no method for 'floatatom 100 10 7 50 5000'
print: menusave
saved to: /home/tanmay/Desktop/pd-REPL/REPL/src/test.pd
FINISH Patch Test
```
Here `menusave` seems to be working correctly. Are the other messages not supported by libpd?

**Comment by tgujar** [comment]
This issue gets resolved by sending the message as:
```
pd::List l;
l.addFloat(10);
l.addFloat(10);
l.addSymbol("bang");
pd.sendMessage("maker", "msg", l);
```
I am guessing this was due to the entire message being treated as one string. I am fairly new to using pd can someone confirm?

**Comment by danomatika** [comment]
Yes, sending `"msg 10 10 bang"` as a string results in `"msg 10 10 bang"` as a symbol and *not* a list. You need to break it up and send it typed. Look into using pd::List...
