### ISSUE TITLE
libpd_start_gui / libpd_stop_gui: closing Pd closes the host software

### ISSUE THREAD

**Issue by jcelerier** [libpd/libpd#337]
Hi,
it's very simple: 
if one opens the Pd GUI with libpd_start_gui, and then closes the Pd window, the whole software goes away because this calls glob_exit() in s_inter.c which in turn calls exit().

I tried to experiment by replacing that function with a call to `sys_stopgui();` ; that seems to work but I am getting double frees if I open, close, open, close, the gui on a single instance, and then call libpd_closefile when I'm done.

**Comment by danomatika** [comment]
As this is a problem within the `pure-data` folder, please open an issue upstream: https://github.com/pure-data/pure-data/issues.

**Comment by Spacechild1** [comment]
Actually, `glob_exit` needs to be fixed. It shouldn't just call `_exit`, but rather break from the scheduler. I've been working on some scheduler fixes/improvements, and this will be part of it.

**Comment by jcelerier** [comment]
Okay, I'll make an issue there and link to this one
