### ISSUE TITLE
Few issues building javalib on Linux 

### ISSUE THREAD

**Issue by funkyfourier** [libpd/libpd#340]
**Finding jni.h and jni_md.h:**

The Makefile seems to expect both of these to be in `$(JAVA_HOME)/include/linux`. However, at least in Raspbian, when using openjdk-11-jdk and openjdk-8-jdk, `jni.h` is placed in `$(JAVA_HOME)/include` and `jni_md.h` in `$(JAVA_HOME)/include/linux`. This leads to an error while building since jni.h will not be found. I am not sure how this should be solved.

**Typo in Makefile**

As it stands, in line 118 it says `java/org/puredata/core/PdBaseloader.java \`. It should of course be `PdBaseLoader.java` with a capital 'L'.

**Comment by danomatika** [comment]
The Java build may be out of date. Please make a PR for this.

**Comment by funkyfourier** [comment]
Done #342
