### ISSUE TITLE
iOS app with libpd build errors: "Undefined symbols"

### ISSUE THREAD

**Issue by marineturtle** [libpd/libpd#347]
I have an iOS app with libpd working for some years. I just updated libpd to the latest master (after some blank), and then started to see the following errors when I tried to build the app:

> Undefined symbols for architecture x86_64:
>   "_soundfile_wave_setup", referenced from:
>       _soundfile_type_setup in libpd-ios.a(d_soundfile.o)
>   "_soundfile_aiff_setup", referenced from:
>       _soundfile_type_setup in libpd-ios.a(d_soundfile.o)
>   "_soundfile_caf_setup", referenced from:
>       _soundfile_type_setup in libpd-ios.a(d_soundfile.o)
>   "_soundfile_next_setup", referenced from:
>       _soundfile_type_setup in libpd-ios.a(d_soundfile.o)
>   "_x_file_setup", referenced from:
>       _conf_init in libpd-ios.a(m_conf.o)
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

It seems that these errors occur when the function is not actually defined within pure-data. For example, m_conf.o calls the two functions below:

> x_net_setup();
> x_file_setup();

The first one is defined in x_net.o and no error occurs. On the other hand, the second one is not defined like that and the error occurs.

How can I resolve these errors? Thank you very much for your time for this. Any help would be appreciated.

**Comment by marineturtle** [comment]
I found some more info on the issue. For example, soundfile_wave_setup() is defined in the file of d_soundfile_wave.c. Although I see that file in my app's directory, Xcode somehow doesn't seem to include it in the /pure-data/src folder and it won't appear under the Project navigator.

**Comment by marineturtle** [comment]
And, it turned out that, if I manually added missing files into Xcode, the issue is resolved. It may not be a libpd issue, but more likely Xcode's strange behavior.

**Comment by danomatika** [comment]
Often if you add new files but don't clean the project, the build objects will be missing symbols. Clean & rebuild usually solves it.
