### ISSUE TITLE
Different behaviour when sending float or symbol to receiver.

### ISSUE THREAD

**Issue by residuum** [libpd/libpd#353]
The Pd patch contains a receiver `foo` which is connected to a `print`.

    [r foo]
    |
    [print]

The print_hook is set and raises an event in C#.
Now for the different behaviour in unit tests:
- When a symbol `bar` is sent to `foo`, it will result in one event with the value `print: symbol bar\n`
- When a float `42` is sent to `foo`, it will result in two events with the values `print: 42` and `\n`

**Comment by residuum** [comment]
Ah, never mind, my mistake. It will always result in two events, with the latter containing `\n`.

**Comment by danomatika** [comment]
Use the print concatenation in print_util.h which stitches lines together. The underlying `post()` mechanism may sometimes (but not always) split lines into chunks by default.
