### ISSUE TITLE
Externals don't work unless compiled in

### ISSUE THREAD

**Issue by magogware** [libpd/libpd#355]
Similar to #341, but this is happening on libpd's C API.

Simply put, externals aren't working unless compiled in (i.e.: using `EXTRA=true`, adding the external's source files to the libpd Makefile's `EXTRA_FILES` variable, and adding the external's `setup()` function to `z_libpd.c`). I've tested this with a known-working extra ([bob~]) by setting EXTRA=false, compiling bob~ into an external separately, and using both libpd's `libpd_add_to_search_path()` function _and_ using a [declare] block in a patch to load bob~ in; neither approach worked.

This happens on both 0.12.3 and the current master branch (02c94a2).

This is happening on an M1 Mac. I have access to a Windows machine I can test on in the next few days. I'll post the results here.

**Comment by danomatika** [comment]
What is the output of `file` for the following?
1. libpd binary (.dylib or .a, whichever you are linking)
2. your program binary
3. the external(s) you are trying to load

**Comment by magogware** [comment]
```
libs/libpd.dylib: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64Mach-O 64-bit dynamically linked shared library x86_64] [arm64]
libs/libpd.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
libs/libpd.dylib (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
```

`program: Mach-O 64-bit executable arm64`

`bob~.d_fat: Mach-O 64-bit bundle x86_64`

There is a discrepancy between the external (bob~)'s architecture and the rest of the software here, but I've used this external (built for the x86_64 architecture) with vanilla Pure Data 0.52.1 built for arm64, so there Apple's Rosetta magic should mean that the differences in architecture aren't causing the issue here. Nevertheless, I will try building the external specifically for the arm64 architecture and testing with that.

**Comment by magogware** [comment]
Just tried compiling bob~ myself into a .pd_darwin file. Result of `file` is as follows:

```
bob~.pd_darwin: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64Mach-O 64-bit dynamically linked shared library x86_64] [arm64:Mach-O 64-bit dynamically linked shared library arm64Mach-O 64-bit dynamically linked shared library arm64]
bob~.pd_darwin (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
bob~.pd_darwin (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
```

Testing the external using a [declare] block in the patch still yielded nothing.

**Comment by magogware** [comment]
No dice. Forced a match between libpd, the external, and my software, and got nothing. I tested using a [declare] block and `libpd_add_to_search_path`, and libpd just couldn't create the [bob~] object. To verify, here's the output from `file` for all three files:

```
bob.pd_darwin: Mach-O 64-bit bundle x86_64
libs/libpd.dylib: Mach-O 64-bit dynamically linked shared library x86_64
program: Mach-O 64-bit executable x86_64
```
Even tried renaming `bob.pd_darwin` to `bob.d_amd64`, in accordance with the [official external writing documentation](https://github.com/pure-data/externals-howto#my-first-external-helloworld), and still got nothing.

**Comment by danomatika** [comment]
I just did a quick test with the pdtest C sample and the vbap external for arm64:

1. clean & build pdtest:
~~~
cd samples/c/pdtest
make clobber && make
~~~
2. clone & build vbap
~~~
git clone https://github.com/pd-externals/vbap
cd vbap
make
cd ../
~~~
3. run the vbap help patch in pdtest
~~~
./pdtest vbap/vbap-help.pd .
~~~

The output of `file` confirms all are using the same architecture:
~~~
danomatika@danomatika pdtest % file pdtest
pdtest: Mach-O 64-bit executable arm64
danomatika@danomatika pdtest % file vbap.pd_darwin
vbap.pd_darwin: Mach-O 64-bit bundle arm64
danomatika@danomatika pdtest % file ./libs/libpd.dylib
./libs/libpd.dylib: Mach-O 64-bit dynamically linked shared library arm64
~~~

I'm not quite sure I understand the reason for using `bob~` when you can easily build it into libpd. I suppose you choose it as a test external however building it is not as straightforward as using third-party externals which use `pd-lib-builder`. I honestly don't know or understand all of the build flags used to make dynamically-loadable external binaries for Pd but I have a suspicion the build flags you are using for your test with `bob~` may be insufficient, which is why I tested with a different external.

**Comment by danomatika** [comment]
As a followup test, renaming the `vbap` dir so Pd can't find it triggers the usual "couldn't create" error:
~~~
mv vbap vbap-bak
cp vbap-bak/vbap-help.pd .
danomatika@danomatika pdtest % ./pdtest vbap-help.pd .
pd 0.52.2
bonk version 1.5
fiddle version 1.1 TEST4
pd~ version 0.54
pique 0.1 for PD version 23
sigmund~ version 0.07
 vbap 90 0 30
error: ... couldn't create
 vbap 0 0 30
error: ... couldn't create
0
0
0
0
0
0
0
0
0
0
~~~

**Comment by magogware** [comment]
Okay, I've recreated your steps and it seems you're spot on. Externals, libpd, and the software linking to libpd need to match their architectures completely. I used a poor example, clearly; the actual external I'm trying to use is the [Sound Design Toolkit](https://github.com/SkAT-VG/SDT/). I suppose I'll just have to try and compile that external for the arm64 architecture, as it's only been released for i386 and x86_64. I've tried compiling libpd and pdtest for x86_64 and using the x86_64 SDT external, but I get this error when I run pdtest:

error: ./SDT.pd_darwin: dlopen(./SDT.pd_darwin, 0x000A): symbol not found in flat namespace '_error'

I suspect this is just now an issue of compiling this external correctly somehow. It does work in vanilla Pd (using x86_64), so I'm a bit lost.

Thank you so much for your help, @danomatika

**Comment by danomatika** [comment]
> Okay, I've recreated your steps and it seems you're spot on. Externals, libpd, and the software linking to libpd need to match their architectures completely.

The external needs to be, at a minimum, compiled for the architecture in question. "Fat libs" which contain nu,tiple arch should work as long as the required arch is there. The reason it works with with the Pd .app is that the `pd` core inside the app bundle is also compiled for multi-arch. 

>I used a poor example, clearly; the actual external I'm trying to use is the [Sound Design Toolkit](https://github.com/SkAT-VG/SDT/). I suppose I'll just have to try and compile that external for the arm64 architecture, as it's only been released for i386 and x86_64. I've tried compiling libpd and pdtest for x86_64 and using the x86_64 SDT external, but I get this error when I run pdtest:
> 
> `error: ./SDT.pd_darwin: dlopen(./SDT.pd_darwin, 0x000A): symbol not found in flat namespace '_error'`
> 
> I suspect this is just now an issue of compiling this external correctly somehow.

This is a different issue where Pd's `error()` function conflicted with the libc version. The external needs to be updated to use `pd_error()` instead. See the issue [here](https://github.com/libpd/libpd/issues/336).

**Comment by danomatika** [comment]
I would also open an issue on the SDT repo for both updating to `pd_error()` and using [pd-lib-builder](https://github.com/pure-data/pd-lib-builder). pd-lib-builder provides the auto detection and various flags needed and is updated as Pure Data progresses.

**Comment by magogware** [comment]
Thank you so much for that extra help!

I did see the Pd .app's executable is compiled for x86_64 as well (and seems to execute in x86_64 as well). The main things that confuse me are that the SDT external runs on a current version of Pd despite the `error()` issue, and that the program linking libpd can't run an external compiled for a different arch (e.g.: an arm64 program using a fat lib libpd can't load an x86_64 external). Getting the match-up right was a bit strange because I figured Rosetta would handle calling x86_64 code from arm64 code.

In any case, you're a lifesaver! Thanks again

**Comment by danomatika** [comment]
> Getting the match-up right was a bit strange because I figured Rosetta would handle calling x86_64 code from arm64 code.

Mmmm I think that's too much of an assumption. I bet it works for the main program itself where the byte code is somehow inspected by Rosetta but it may not be handled in the same way for objects loaded later on at run time. Dunno.
