### ISSUE TITLE
Android.mk missing update for double precision?

### ISSUE THREAD

**Issue by joebowbeer** [libpd/libpd#356]
[Updating](https://github.com/libpd/pd-for-android/pull/122) pd-for-android to the latest commit is failing to build:
```
In file included from /home/runner/work/pd-for-android/pd-for-android/PdCore/src/main/jni/libpd/libpd_wrapper/util/z_queued.c:11:
/home/runner/work/pd-for-android/pd-for-android/PdCore/src/main/jni/libpd/libpd_wrapper/util/z_queued.h:43:47: error: unknown type name 't_libpd_doublehook'
EXTERN void libpd_set_queued_doublehook(const t_libpd_doublehook hook);
```

Any clues @danomatika ?

**Comment by danomatika** [comment]
I don’t use Android, so no idea. The android makefile may need to be updated?

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by joebowbeer** [comment]
@danomatika the entire build is automated and can be perused online:

https://github.com/libpd/pd-for-android/runs/6483411925?check_suite_focus=true

The failure happens in the libpd_wrapper sources at the end of the Android.mk src list.

Is there anything familiar about this failure?

**Comment by tkirshboim** [comment]
@residuum Do you maybe have an idea how we could fix this issue?

**Comment by Ant1r** [comment]
I think the solution is #357:
when compiling `z_queued.c`, the compiler needs to include `z_queued.h`, but it first finds the one in pure_data/src, which is outdated (and where `t_libpd_doublehook` is not declared).

**Comment by residuum** [comment]
> @residuum Do you maybe have an idea how we could fix this issue?

My knowledge of Android and Java programming is more or less limited to my sensor apps, so I have no idea.
