### ISSUE TITLE
how to compare my (emscripten) changes with the files of the currently used pure data branch?

### ISSUE THREAD

**Issue by Jonathhhan** [libpd/libpd#363]
this is the pure data branch currently used by libpd: https://github.com/pure-data/pure-data/tree/18c9695ba4de543c51c2c013b45b99b8f1c35a19
and here are my libpd changes (i only changed some of the pure data source files): https://github.com/Jonathhhan/ofxOfelia/tree/update/libs/ofxPd/libs/libpd
it would help to have a better overview and to remove unnecessary changes, if i can compare both versions (like it is possible with "normal" branches in github).
it actually seems to work well with emscripten.

**Comment by Ant1r** [comment]
if you made some changes, then you're surely in the best position to know what and where these changes are...
you also could learn to use `diff` and `git diff`.

That said, here is the **libpd** issue tracker: it's the place you can report bugs and request features for **libpd**. To quote someone else:

> if you seek general help, please use the pd-list, the Pd-forum, the facebook group, your local Pd user group, or.... - but do not abuse the issue tracker for support.

**Comment by Jonathhhan** [comment]
@Ant1r 
> if you made some changes, then you're surely in the best position to know what and where these changes are...
haha, that makes sense. now i have an idea how to compare. thank you for the hints and clarifications...

**Comment by Jonathhhan** [comment]
Here is what I actually changed: https://github.com/Jonathhhan/ofxOfelia/compare/update_compare...Jonathhhan:ofxOfelia:update

**Comment by danomatika** [comment]
If y’all want traction on this, I would suggest chiming in further on the main pure-data repo pull request by Claude for emscripten support. If you can get Millers attention, there is a better chance for feedback and the possibility of a merge.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by danomatika** [comment]
Ah, I see you already did that. Sorry, I am reading the emails in reverse order.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com
