### ISSUE TITLE
couldn't create clone abstraction

### ISSUE THREAD

**Issue by apiel** [libpd/libpd#367]
I am trying to use `clone` with libpd but doesn't work, I am getting: `error: ... couldn't create`

I have a main pd file:
```pd
#N canvas 573 435 352 157 10;
#X obj 85 87 clone abstraction 4;
```
And then an abdstraction.pd file:
```pd
#N canvas 691 151 352 157 10;
#X obj 69 63 loadbang;
#X obj 69 107 print hello \$1;
#X connect 0 0 1 0;
```

With pure data UI, it does print out:
```
hello 0: bang
hello 1: bang
hello 2: bang
hello 3: bang
```

With using pdtest from sample c folder, I am getting:
```
 clone abstraction 4
error: ... couldn't create
```

I am using Ubuntu and the last version recommended of libpd (0.8.3).
Any idea on how to fix this?

**Comment by apiel** [comment]
Clone is not available on the recommended version but on more recent version...

**Comment by danomatika** [comment]
Yup. The version of pd used by libpd 0.8.3 is too old and doesn’t have the clone object yet.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com
