### ISSUE TITLE
How does multiple instance work?

### ISSUE THREAD

**Issue by tapir** [libpd/libpd#378]
I'm working on a project where I eventually want to process multiple *.pd modules at the same time. In order to do that I would like to manage my own threads however the impression I got from the documentation is that a multi-instance would cause libpd to do some internal threading magic. Is there a way around it?

**Comment by danomatika** [comment]
> I'm working on a project where I eventually want to process multiple *.pd modules at the same time.

Do you mean run mutliepl patches simultaneously? You can do that in a single libpd instance just like desktop Pd.

> In order to do that I would like to manage my own threads however the impression I got from the documentation is that a multi-instance would cause libpd to do some internal threading magic. Is there a way around it?

In what language are you working? The core C libpd does not do any "internal threading magic" it only provides methods to create and set individual instances. You then process samples in and out. Multiple instances are useful mainly in the context of plugins, etc.

**Comment by danomatika** [comment]
Yeah I think so too. Basically, if you create and run the patches on desktop Pd, stick with single instance. If you need completely separate patch environments that cane loaded at will, like plugins, then multiple instances as a special case make sense.

**Comment by danomatika** [comment]
> I'm using it from Go and my idea was to use a goroutine per patch and pass the samples in-between them.

In this case, consider using abstractions or sub patches and changing them in the Pd patch itself. I wouldn't overthink it at the libpd level, do what you can all within patches first.

**Comment by danomatika** [comment]
Closing for now. Reopen if necessary.
