### ISSUE TITLE
libpd_start_gui silently fails

### ISSUE THREAD

**Issue by samsface** [libpd/libpd#380]
Hi. When calling `libpd_start_gui`, no gui is launched but I get a success return code of `0.`

I'm calling the function like this `libpd_start_gui("/lib/puredata/")`
I'm on the master branch.
Using Ubuntu.

Is there anything else one needs to do in order for this function to work?

*Love this project btw*.

Thanks

**Comment by danomatika** [comment]
Did you install the GUI, ie. the Pure Data desktop application? The debian package name is `puredata` I believe. If the GUI is installed, the function should then work.
