### ISSUE TITLE
alloca.h no such file minGW-w64

### ISSUE THREAD

**Issue by ddgg-el** [libpd/libpd#381]
Hello!
I'd like to compile the provided python wrapper, but I am having problems compiling the libpd in Windows.
I am using msys2/mingw64 as suggested in the README.md.
Unfortunately I almost immediately get an error:
```
In file included from pure-data/src/d_fft_fftsg.c:25:
pure-data/src/m_private_utils.h:57:12: fatal error: alloca.h: No such file or directory
   57 | #  include <alloca.h> /* linux, mac, mingw, cygwin,... */
      |            ^~~~~~~~~~
compilation terminated.
```
I did install: `mingw-w64-x86_64-toolchain mingw-w64-x86_64-clang make` and mysys2 is properly updated.
I could compile libpd with @Spacechild1's [pure-data fork](https://github.com/Spacechild1/pure-data)  though, but when compiling the python wrapper the linker fails.
I had no problem compiling the wrapper for MacOS and Debian. I have to acknowledge that I am not very skilled with the Mingw64 compilation toolchain.
Is there something else I could try?

Thank you!

**Comment by danomatika** [comment]
Try the following: comment or remove the HAVE_ALLOCA_H line in setup.py, then clean & rebuild: https://github.com/libpd/libpd/blob/master/python/setup.py#L11

**Comment by ddgg-el** [comment]
which means that there is no need to compile the libpd first...? 
Thank you. I'll give it a try

**Comment by danomatika** [comment]
setup.py compiles libpd separately

**Comment by danomatika** [comment]
Ok, so the issue is with the makefile and not the setup.py. In this case, try building python without any changes first.

**Comment by danomatika** [comment]
@umlaeute We are setting `HAVE_ALLOCA_H` as before but I wonder if mingw sets `WIN32` as needed in the private)utils,.h header...

**Comment by ddgg-el** [comment]
ok without `HAVE_ALLOCA_H`  it goes on, but then it does not find `endian.h` .
I could comment `pd_defines.append((HAVE_ENDIAN_H,1))` on line 20...

**Comment by Spacechild1** [comment]
>  We are setting HAVE_ALLOCA_H as before but I wonder if mingw sets WIN32 as needed in the private)utils,.h header...

The define is `_WIN32` and it must be set by MinGW. `HAVE_ALLOCA_H` should not be defined.

`m_private_utils.h` is not the problem, as Pd compiles successfully on Windows (both with autotools and Miller's makefiles), so this must be rather a problem with libpd's build system.

I am AFK now, but I will try to compile libpd and the python wrapper on my MSYS2 system.

**Comment by danomatika** [comment]
Yeah, it could be wrong. I set the new defined since they were now required by the changes brought by the header, however I couldn't test every platform.enohp ym morf tnes-----------Dan Wilcoxdanomatika.comrobotcowboy.comOn Dec 23, 2023, at 6:50 PM, Christof Ressi ***@***.***> wrote:﻿

We are setting HAVE_ALLOCA_H as before but I wonder if mingw sets WIN32 as needed in the private)utils,.h header...

The define is _WIN32 and it must be set by MinGW. HAVE_ALLOCA_H should not be defined.
m_private_utils.h is not the problem, as Pd compiles successfully on Windows (both with autotools and Miller's makefiles), so this must be rather a problem with libpd's build system.
I am AFK now, but I will try to compile libpd and the python wrapper on my MSYS2 system.

**Comment by Spacechild1** [comment]
> We are setting HAVE_ALLOCA_H as before

`HAVE_ALLOCA_H` should not be defined because Windows/MinGW does not have `alloca.h` (instead, `alloca` is defined in `malloc.h`).

That being said, `m_private_utils.h` did not change anything regarding `alloca` and byte order, it contains the same code that has been previously repeated in several source files: https://github.com/pure-data/pure-data/commit/676eccde361a41b67fd435fb7cb225d229f3a283#diff-668cdf8f1bd0fddad31a95872f768289061f07778d7134e3ce618d72537c1267

**Comment by Spacechild1** [comment]
Ok, I removed `-DHAVE_ALLOCA_H` from the Makefile and now libpd compiles cleanly with MSYS2 (MinGW64).

**Comment by danomatika** [comment]
Ok, so it needs to eb set explicitly only for other platforms which support it. *sigh* I guess I understand the reasoning to push this out of the Pd sources into the build systems but it's annoying in our case...

**Comment by Spacechild1** [comment]
Similarly, for the python wrapper (`libpd/python`) I had to remove `-DHAVE_ALLOCA_H` and `-DHAVE_ENDIAN_H` from `setup.py`, as these should not be defined on Windows!

**Comment by danomatika** [comment]
What problems did `-DHAVE_ENDIAN_H` bring? As far as the header is concerned, it always pulsing the correct include by check if WIN32_ misdefined regardless of the define, at least when I check for the last version if libpd.

**Comment by Spacechild1** [comment]
Aha, before `m_private_utils.h`, @umlaeute changed the `#include` logic in the individual source files:
https://github.com/pure-data/pure-data/commit/26741fc573208df7dbcb08ae236caffc4e200336
https://github.com/pure-data/pure-data/commit/43fda671e5b76e1191d778dae905c43d773577c2

libpd always set the wrong defines on Windows, but it didn't have any effect until these two commits :)

**Comment by danomatika** [comment]
Ok, se we set these includes just for Linux and macOS and not for Windows?

**Comment by Spacechild1** [comment]
> What problems did -DHAVE_ENDIAN_H bring? 

Because the compiler would try to include `<endian.h>`:

```
#ifdef HAVE_MACHINE_ENDIAN_H
# include <machine/endian.h>
#elif defined HAVE_ENDIAN_H
# include <endian.h>
#endif

#ifdef __MINGW32__
#include <sys/param.h>
#endif
#ifdef _MSC_VER
/* _MSVC lacks BYTE_ORDER and LITTLE_ENDIAN */
#define LITTLE_ENDIAN 0x0001
#define BYTE_ORDER LITTLE_ENDIAN
#endif
```

As you can see, there is no explicit guard for Windows. However, the `_MINGW_32` and `_MSC_VER` sections should really be inside an `#else` clause after `#elif defined HAVE_ENDIAN_H`.

**Comment by Spacechild1** [comment]
> Ok, se we set these includes just for Linux and macOS and not for Windows?

Yes! (I assume you meant "defines" instead of "includes")

**Comment by danomatika** [comment]
> As you can see, there is no explicit guard for Windows. However, the `_MINGW32_` and `_MSC_VER` sections should really be inside an `#else` clause after `#elif defined HAVE_ENDIAN_H`.

Interesting... https://github.com/pure-data/pure-data/pull/2081

**Comment by danomatika** [comment]
Ok, please try latest commit [60852c2](https://github.com/libpd/libpd/commit/60852c2eeaba14f9ffcaddbb8307a2973a265171) in master branch.

**Comment by Spacechild1** [comment]
Thanks! libpd now compiles!

Unfortunately, I was too quick when testing the python wrapper and didn't notice the linker errors that @ddgg-el has mentioned. The problem is that we try to link against `libdl` (which does not exist on Windows) and forget to link against `ws2_32` (Winsock2). As a quick and dirty fix I replaced `dl` with `ws2_32` in the `libraries` array.

**Comment by danomatika** [comment]
Ah right, thanks for checking. The setup.py was originally written circa 2010 or so and we have only made occasional additional updates and maintenance, so it doesn't surprise me these were missed. In any case, I made linking `dl` per-platform and now include `ws2_32` as suggested.

Maybe we should really consider integrating CI builds to catch these things as suggested #210 but I am admittedly too lazy to do this.

**Comment by danomatika** [comment]
Both makefile and setup.py should be updated for Windows and BSD. Please check if you can. Once confirmed, I can make a bugfix release.

**Comment by Spacechild1** [comment]
Almost.

```
libraries = [
    'm',
    'pthread'
],
```
should rather be
```
libraries = pd_libraries,
```

**Comment by Spacechild1** [comment]
Side note: shouldn't `make clean` clean everything inside the `build` folder? Currently, it leaves `libpd_wrapper` and `pure-data`.

**Comment by danomatika** [comment]
Fixed.

> Side note: shouldn't make clean clean everything inside the build folder?

Use `make clobber`.

**Comment by Spacechild1** [comment]
Works now, thanks! Now I'm heading off to the next thing that badly needs some fixes: our Christmas tree :) Happy holidays!

**Comment by danomatika** [comment]
ja, thanks for double-checking. We did the tree yesterday, so I had time to do this today.

**Comment by ddgg-el** [comment]
amazing! thank you all very much!
It works flawless!
It does produces an `egg`  and it installs everything in site-packages.
If figured out that if you want to pack a `whl` package in `setup.py`  a quick solution would be to switch `distutils.core` with `setuptools`
```
# setup.py
from setuptools import set, Extension
``` 
and change the `install` rule in the Makefile as follow:
```
$(PYTHON) setup.py install bdist_wheel
```
this will create a `dist` folder in `libpd/python` with the `pylibpd` wheel package which can be distributed installed by `pip`
Of course this requires both `wheel` and `setuptools` to be installed.
Thank you very much again!
