### ISSUE TITLE
CmakeLists.txt needs to be updated to set HAVE_ALLOCA_H, HAVE_ENDIAN, etc

### ISSUE THREAD

**Issue by danomatika** [libpd/libpd#382]
Changes to the Pd sources moved certain platform checks out of the internal headers into the build systems. Also, we cannot link libdl on Windows or BSD and need to link winsock on Windows. The CMakeLists.txt needs to be updated to handle this.

The overview of changes is:
* macOS:
  - CFLAGS: `-DHAVE_ALLOCA_H -DHAVE_MACHINE_ENDIAN_H -D_DARWIN_C_SOURCE -DHAVE_LIBDL`
  - linker: `dl`
* Windows:
  - linker: `ws2_32`, do *not* link `dl`
* Linux: 
  - CFLAGS: `-DHAVE_ENDIAN_H -DHAVE_ALLOCA_H -DHAVE_LIBDL`
  - linker: `dl`
* BSD:
  - CFLAGS: `-DHAVE_ENDIAN_H`
  - linker: do *not* link `dl`

The `Makefile` and `python/setup.py` are updated and can be used as examples.

I don't use cmake regularly nor can I easily test on multiple platforms, so I call on those that do to update this: @eldruin @diegov @johnkeeping @mxa @clwe @jcelerier

**Comment by jcelerier** [comment]
... does any supported platform by pd today *not* have these headers?
From a quick check:
- endian.h is in glibc since at least 2.9 (2008) and in musl for at least 13 years. alloca.h has been on glibc for at least 26 years.
- I see on my macOS machin/endian.h a copyright header from 1995 and libdl has been here since forever too

in any case, I can whip up a quick PR for the remaining cases (linking libdl when necessary - CMake already has CMAKE_DL_LIBS which encodes the correct per-platform logic for it)

**Comment by danomatika** [comment]
> ... does any supported platform by pd today _not_ have these headers?

Some do, yes, and the desire in the Pd core is to move many older platform checks out of the headers. I don't fully agree but that's how it is for 0.54 so we need to change the CFLAGS on our end, ie. https://github.com/pure-data/pure-data/pull/2081.

> in any case, I can whip up a quick PR for the remaining cases (linking libdl when necessary - CMake already has CMAKE_DL_LIBS which encodes the correct per-platform logic for it)

Yeah, that would be helpful. The list above is just what has been added to the Makefile from feedback on other platforms, ie. Windows and BSD being broken with libod 0.14.0.

**Comment by danomatika** [comment]
I assume this was handled via merging #383. Closing for now.

**Comment by jcelerier** [comment]
yes:

```

target_compile_definitions(libpd_public_settings
  INTERFACE
    PD=1
    USEAPI_DUMMY=1
   "$<$<BOOL:${PD_DEFINE_EXTERN}>:EXTERN=${PD_DEFINE_EXTERN}>"
    $<$<BOOL:${APPLE}>:_DARWIN_C_SOURCE>
    $<$<BOOL:${HAVE_ALLOCA_H}>:HAVE_ALLOCA_H=1>
    $<$<BOOL:${HAVE_ENDIAN_H}>:HAVE_ENDIAN_H=1>
    $<$<BOOL:${HAVE_LIBDL}>:HAVE_LIBDL=1>
    $<$<BOOL:${HAVE_MACHINE_ENDIAN_H}>:HAVE_MACHINE_ENDIAN_H=1>
    $<$<BOOL:${HAVE_UNISTD_H}>:HAVE_UNISTD_H=1>
    $<$<BOOL:${PD_EXTRA}>:LIBPD_EXTRA=1>
    $<$<BOOL:${PD_MULTI}>:PDINSTANCE=1 PDTHREADS=1>
    $<$<NOT:$<BOOL:${PD_LOCALE}>>:LIBPD_NO_NUMERIC=1>
)
```
