### ISSUE TITLE
error when importing pylibpd

### ISSUE THREAD

**Issue by Jackovic** [libpd/libpd#390]
Hello,

I just got sources and do :
```
$ cd python
$ make PYTHON=python3
```

All seems fine.
But after :
```
$ python3
>>> from pylibpd import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jack/Documents/RYBN/pnode/test_libpd_python/libpd/python/pylibpd.py", line 15, in <module>
    import _pylibpd
ModuleNotFoundError: No module named '_pylibpd'
```
Is there something wrong in my setup ?
Ubuntu 22.04
Python 3.10.12
Thanx.
++

Jack

**Comment by danomatika** [comment]
Did you install after building?enohp ym morf tnes-----------Dan Wilcoxdanomatika.comrobotcowboy.comOn Mar 17, 2024, at 4:17 PM, Jackovic ***@***.***> wrote:﻿
Hello,
I just get sources and do :
$ cd python
$ make PYTHON=python3

All seems fine.
But after :
$ python3
>>> from pylibpd import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jack/Documents/RYBN/pnode/test_libpd_python/libpd/python/pylibpd.py", line 15, in <module>
    import _pylibpd
ModuleNotFoundError: No module named '_pylibpd'

Is there something wrong in my setup ?
Ubuntu 22.04
Python 3.10.12
Thanx.
++
Jack

**Comment by Jackovic** [comment]
Hi Dan,

I removed my libpd directory, then :
```
$ git clone --recurse-submodules https://github.com/libpd/libpd.git
$ cd libpd/python
$ make PYTHON=python3
$ make install
$ python3
>>> from pylibpd import *
>>>
```

And all is ok.
So "make install" was the missing element.
Thank you for your help.
++

Jack
