### ISSUE TITLE
EXC_BAD_ACCESS in Obj-C PdBase listHook

### ISSUE THREAD

**Issue by danomatika** [libpd/libpd#43]
In the Obj-C wrapper on iOS, I'm running a patch that is sending lots of continual list data to libpd. Over time, I keep seeing an EXC_BAD_ACCESS on 

    NSString *source = [[NSString alloc] initWithCString:src encoding:NSASCIIStringEncoding];

in https://github.com/libpd/libpd/blob/master/objc/PdBase.m#L120

The debugger shows the src cstring is not null so I'm not sure what's going on ... maybe it's not being null-terminated?

**Comment by nettoyeurny** [comment]
Should be fixed in Version 0.8.1 (now pushed to master branch).
