### ISSUE TITLE
autotools ?

### ISSUE THREAD

**Issue by umlaeute** [libpd/libpd#75]
as mentioned in #53, it might be good to use some complex build-system for building libraries, e.g. `autotools`.

since i do like `autotools`, i'm happy to help here

**Comment by danomatika** [comment]
This will happen, probably over the summer.

**Comment by eldruin** [comment]
I am definitely not trying to trigger a build system discussion but if Windows and Visual Studio support is something desired, cmake is probably a better choice.
With cmake you would not need msys to build on Windows as cmake can generate Visual Studio solutions natively.
As a matter of fact, we are interested in using this library on several platforms but we cannot use it on Windows as long as it is not possible to build the C (and python) library with Visual Studio (i.e. without msys and mingw).

**Comment by umlaeute** [comment]
you should be able to just use the library compiled with MinGW with your VisualStudio project (at least that's the idea)

**Comment by danomatika** [comment]
Also, I'm not sure if libpd currently builds in Visual Studio: https://github.com/libpd/libpd/issues/86

**Comment by eldruin** [comment]
Currently we do not want to integrate MinGW into our build system and we do not like the idea of compiling locally and checking in binaries into our repository. That is why native compilation with Visual Studio would be a requirement for us.

**Comment by umlaeute** [comment]
@eldruin if you want a VS project, you should raise a separate ticket.

i guess (but i'm not really in the knowe) that it would be welcome, if you could do a PR that adds that.

**Comment by eldruin** [comment]
@umlaeute A separate VS project file is not a great solution because these files contain local folder paths and are generally difficult to maintain as VS keeps changing over time and you need the actual IDE to change project properties.

Sadly I do not have time that I could invest in this project. I just wanted to let you guys know of additional goals you could consider when rewriting your build system, as this is a delicate long-term commitment.

**Comment by umlaeute** [comment]
please open a separate ticket to discuss the Visual Studio integration

**Comment by danomatika** [comment]
Closing this for now. I don't see a need for autotools so far.
