### ISSUE TITLE
gem support

### ISSUE THREAD

**Issue by jasperblues** [libpd/libpd#84]
Hello, 

Just wondering if liPid can be used with gem?

**Comment by umlaeute** [comment]
afaict, there shouldn't be any problem *in theory*.
however, things to keep in mind:

- Gem needs to be compiled separately and `dlopen()`ed in the calling application (or use Pd's loading mechanism). Gem uses some initialazation trickery, that *might* behave badly when being statically linked to the Pd-environment (e.g. libpd)

- some systems (e.g. *iOS*) do not have `dlopen()`, so you cannot dynamically load Gem (compare this with the above)

- Gem depends on *openGL*; it does **not** work with *openGL-ES* (as found on android)

- Gem's license is *GPLv2+* (unlike libpd's with has a BSD-like license): this is incompatible with some distribution platforms.

**Comment by jasperblues** [comment]
Thanks for the info. It sounds like a large project to get this happening on mobile platforms. Let's close for now.
