### ISSUE TITLE
Unable to build C# API - libpdcsharp.dll

### ISSUE THREAD

**Issue by milanjaros** [libpd/libpd#87]
Hi,
I'm unable to [build the libpd using mingw](https://github.com/libpd/libpd/wiki/Building-the-C%23-Api).

```make clean``` goes well, so it seems mingw is set-up properly, but

```make csharplib``` throws:
make: *** No rule to make target 'pure-data/src/d_arithmetic.o', needed by `libs/libpdcsharp.dll'. Stop.

@tebjan was so kind and prepared how-to but I'm not able to follow it.
Can you, please, suggest anything?

**Comment by danomatika** [comment]
Did you try mingw_build.bat?

**Comment by danomatika** [comment]
I think I know you're problem. You need to checkout the submodule which has the libs sources. See here: https://github.com/libpd/libpd#pure-data

**Comment by milanjaros** [comment]
Great, thanks! 
After cloning "pure-data" sources I've got also:
     `pure-data/src/d_soundfile.c:17:21: fatal error: pthread.h: No such file or directory`

So, I followed [your proposal from another thread](https://github.com/patricksebastien/libpd4unity/issues/4#issuecomment-44594141) and installed MinGW pthreads: 
`mingw-get install mingw32-pthreads-w32-dev`
and I've got:
```
c:\tools\mingw\include\pthread.h:320:8: error: redefinition of 'struct timespec'

 struct timespec {
        ^
In file included from c:\tools\mingw\include\unistd.h:95:0,
                 from pure-data/src/d_soundfile.c:15:
c:\tools\mingw\include\parts\time.h:65:8: note: originally defined here
 struct timespec
        ^
make: *** [pure-data/src/d_soundfile.o] Error 1
```
I'm stuck again.

**Comment by danomatika** [comment]
Dunno. Looks like a conflict between a defined type in both of those headers. In this case it's a MinGW environment problem and not with libpd. You might check the headers to see if there some define that needs to be set to ignore one of the definitions, etc.

**Comment by milanjaros** [comment]
Great, I build it. Sorry for bothering... I've found this is really some [MinGW issue with incompatible libraries](https://lists.gnu.org/archive/html/bug-gnulib/2015-01/msg00042.html).

So, I went to `MinGW\include\pthread.h` line 320 and commented out the scruct. 

Thank you very much for your patience. 

Milan ;)

**Comment by webfd** [comment]
wo yet has a same problem

**Comment by milanjaros** [comment]
Have you tried to modify the pthread.h?

**Comment by eigenbom** [comment]
Got through all this, modified pthread, and then hit this error. Looking further into it..

```
pure-data/src/g_canvas.c:64:1: error: initializer element is not constant
 static t_symbol *canvas_newfilename = &s_;
 ^
```

**Comment by eigenbom** [comment]
If you use msys2 and mingw64 you don't have to modify pthread. I still haven't got the c++ samples built, but the C sample works. Here's a [small blog post](http://bp.io/post/2017) on building libpd and the C sample with mingw.
