### ISSUE TITLE
libpd 64bit iOS compile error

### ISSUE THREAD

**Issue by tonysnail** [libpd/libpd#88]
Hi,

Trying to compile libPD in iOS with the latest puredata source, cloned from the PD git, and compiled in xcode as a 64-bit application renders the following errors:

in z_libpd.c - int libpd_process_raw():

 sched_tick(sys_time + sys_time_per_dsp_tick); - 'Too many arguments to function call, expected 0, have 1)

and the same error later in z_libpd.c -

int libpd_process_short(int ticks, short *inBuffer, short *outBuffer) {
  PROCESS(* short_to_sample, * sample_to_short)  - 'Too many arguments to function call...'
}

Can anyone suggest a fix for this? I cannot compile my app until this is addressed.

Thanks,

Carl

**Comment by danomatika** [comment]
Out of curiosity, why are you using the bleeding edge pd sources? The current stable pd we use in libpd works on arm64 as far as I can test. I recently updated libpd to pd 0.46-4 so I'd suggest using that.

Looks like the errors involve updates to the main pd sources which are not reflected in libpd, or at least the version you have.

**Comment by tonysnail** [comment]
could you point me to link with the stable PD source so that I can ensure I'm using the correct version? I'll try compiling and report back my findings..

Best,

Carl

**Comment by danomatika** [comment]
Uh, this repo. clone it and update the submodule with the pd sources: https://github.com/libpd/libpd#repository-layout

**Comment by tonysnail** [comment]
thanks Dan! My app is now compiled in 64 bit, you are a lifesaver sir. I used the repo link you gave :-)
