### ISSUE TITLE
Have to put 2 sendBang to make one bang

### ISSUE THREAD

**Issue by tompad2** [libpd/libpd#92]
Hi!
Im doing an app in AndroidStudio with libpd, got it running but have a strange behavior of PdBase.sendBang. Every time I start up app and run it the bang is sent but no sound is coming. However if I send the bang again it will sound. OR if I put 2 PdBase.sendBang in a row THEN it will sound!? What is happening? Is this normal behavior of sendBang?

My code:

    private void triggerBell() {
        Log.d("CB_BellOnOff", String.valueOf(CB_BellOnOff));
        //Just checking if CB_BellOnOff is true - and yes it is
    
        if (CB_BellOnOff) {
            PdBase.sendBang("triggbell");
            // If I put another PdBase.sendBang("triggbell"); in a row it will sound
        }
    }

**Comment by danomatika** [comment]
It's probably something in your patch. Try adding a [print] object to make sure the bang is being received.

**Comment by tompad2** [comment]
Ok, I've done this:

Put a [print] on reciever in pdpatch - output, bang recieved!

The reciever is connected to a "inline" patch called [pd bell], put a  [print] on [inlet] - output, bang recieved!

The [inlet] is connected with a [message] with number 1 in it,  put a  [print] after  [message] - output, 1 (bang recieved!).

The [message] is connected with a "inline" patch called [pd ton1], put a  [print] on [inlet] - output, 1 (bang recieved!).

The [inlet] is connected with a [pd env] ("inline" patch),  put a  [print] after  [inlet] - output, 1 (bang recieved!).

Puuh! ;-)

Outcome after running the first time sendBang in appcode == no sound
Outcome after running the second time sendBang in appcode == SOUND! :-)

Its so strange - is it because I run a metronomsound parallell? If so, why doesn't the sound
drop out when I run metronome and a synthsound parallell? (Same patch)

**Comment by tompad2** [comment]
Uereka!I found that the problem was in the patch, an envelope that didnt work as I expected. Solution - I made a simple envelope with vline! Sorry for taking up time....
