### ISSUE TITLE
Can't push podspec to master

### ISSUE THREAD

**Issue by jasperblues** [libpd/libpd#99]
Hi, 

I can't push the libpod.podspec to CocoaPods master because there's a syntax error in the spec authors. 

Looks like this: 

```ruby
 s.author = { "Peter Brinkmann", "Dan Wilcox", "Rich Eakin" }
```

. . . and it should look like (for example): 

```ruby
  spec.author = {'Jasper Blues, Aleksey Garbarev, Robert Gilliam, Daniel Rodríguez, Erik Sundin & Contributors' => 'info@typhoonframework.org'}
```

**Comment by danomatika** [comment]
I was going off of [this doc page](https://guides.cocoapods.org/syntax/podspec.html#authors) and now I see I didn't the brackets. Whoops.

**Comment by jasperblues** [comment]
I think you want `s.authors` not `s.author` :)

**Comment by jasperblues** [comment]
This uncovers another problem, when attempting to push to CocoaPods master repo: 

```
jblues@toptop:~/ModProductions/libpd[master]$ pod trunk push libpd.podspec 
Validating podspec
 -> libpd (0.8.2)
    - ERROR | [iOS] Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | [iOS]  clang: error: invalid deployment target for -stdlib=libc++ (requires iOS 5.0 or later)

[!] The podspec does not validate.
```

Perhaps marking issues 'Ready for Review' using github labels will help manage things? 

* Who wants to fix this next issue with the podspec? 
* After the issue is fixed who want to push to CocoaPods master? I can do this or hand that role over to someone in the libPd team.

**Comment by danomatika** [comment]
SIgh. None of us use Cocoapods, and debugging this was something I wanted to avoid. Anyway, the error obviously means it wants us to bump up the deployment target.

**Comment by danomatika** [comment]
Bumped to iOS 6.0 an retagged.

**Comment by residuum** [comment]
Deleting and recreating tags is not a good thing, as tags should be used to mark a specific point in the commit log, and users may rely on tags to never change.

Please try to avoid that: https://root.cern.ch/drupal/content/git-tips-and-tricks#Special-notes-on-mis-tagging

**Comment by jasperblues** [comment]
>SIgh. None of us use Cocoapods, and debugging this was something I wanted to avoid.

I'm happy to keep doing it for you. Just offering in case someone preferred to take over it.

**Comment by jasperblues** [comment]
Ok, we've still got some errors. I'll fix and send a pull request. 

```Validating podspec
 -> libpd (0.8.2)
    - ERROR | [iOS] Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | [iOS]  Headers/Private/libpd/z_libpd.h:19:10: fatal error: 'm_pd.h' file not found```

**Comment by danomatika** [comment]
@residuum Normally I don't but I thought the pod spec had been tested before the PR was mad, so a little bump initially made sense.

**Comment by danomatika** [comment]
Also, that error looks like the pure-data sources are missing. Maybe there submodule wasn't cloned properly.

**Comment by jasperblues** [comment]
@danomatika @residuum The podspec just points to a tag, so there can be separate commits to that, without affecting what it points to. 

As for debugging, since I was the original spec author/maintainer, I thought it was reasonable to assume a simple version bump to the spec was all that's required. However, the spec had been subsequently edited incorrectly for one, and the CocoaPods validation rules have become a lot stricter since 2013. So this wasn't the case.

**Comment by yairsz** [comment]
A workaround for this issue is to point to the repo directly in the podfile like this:
`pod 'libpd', :git => 'https://github.com/libpd/libpd'`

**Comment by yairsz** [comment]
Pull request #103 might fix this issue

**Comment by danomatika** [comment]
Ah, that make sense. It couldn't build because it was't checking out the pure-data source submodule. Thanks!

**Comment by danomatika** [comment]
Thanks @yairsz. Fix merged and I added the podfile line to the readme.

**Comment by danomatika** [comment]
Can y'all double check the current libpd.podspec. It should be building/working now. Once everything is good, I'll tag the current version at 0.8.3.

**Comment by yairsz** [comment]
@danomatika added a small PR to correct the podfile install command. It's pointing to my fork instead of the official libpd repo. Happy to contribute a small piece to this awesome repo!

**Comment by danomatika** [comment]
No, thank you. I was busy all summer and recently started a new job, so I'm glad for any help to make this work. If you can confirm we're all good now, I'll tag it.

**Comment by yairsz** [comment]
I've managed to build and run without issues.

**Comment by danomatika** [comment]
@yairsz Great. Thank you.

**Comment by danomatika** [comment]
Ok guys. Looks like we're all good now. Thanks everyone.
